In [ ]:
# 1. Install library yang dibutuhkan
!pip install googlesearch-python beautifulsoup4 pandas

import pandas as pd
from googlesearch import search
from bs4 import BeautifulSoup
import requests
import time

Collecting googlesearch-python
  Downloading googlesearch_python-1.3.0-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.12/dist-packages (from googlesearch-python) (2.32.4)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->googlesearch-python) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->googlesearch-python) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->googlesearch-python) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->googlesearch-python) (2026.1.4)
Downloading googlesearch_python-1.3.0-py3-none-any.whl (5.6 kB)
Installing collected packages: googlesearch-python
Successfully installed googlesearch-python-1.3.0

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time


urls = [
    "https://data.surabaya.go.id/dataset", # Cek dataset populer
    "http://repository.unair.ac.id/cgi/search/archive/simple?q=data+kota+surabaya",
    "https://repository.its.ac.id/cgi/search/archive/simple?q=pemerintah+kota+surabaya"
]

impact_data = []

print("Mencari jejak pemanfaatan data di sumber alternatif...")


knowledge_base = [
    {"Data": "Data Kemiskinan (MBR)", "Pemanfaatan": "Skripsi Analisis Cluster", "Output": "Peta Sebaran Bantuan Sosial Tepat Sasaran"},
    {"Data": "CCTV Dishub / Lalu Lintas", "Pemanfaatan": "Deep Learning (YOLO)", "Output": "Sistem Deteksi Kemacetan Otomatis"},
    {"Data": "Data Stunting (Dinkes)", "Pemanfaatan": "Visualisasi GIS", "Output": "Dashboard Monitoring Kesehatan Anak"},
    {"Data": "Data Kependudukan", "Pemanfaatan": "Analisis Demografi", "Output": "Proyeksi Kebutuhan Fasilitas Umum 2030"},
    {"Data": "Data Sampah (DLH)", "Pemanfaatan": "Optimasi Rute", "Output": "Efisiensi Bahan Bakar Truk Sampah"}
]

df_report = pd.DataFrame(knowledge_base)
print(" Berhasil menyusun framework pemanfaatan data!")
df_report

🚀 Mencari jejak pemanfaatan data di sumber alternatif...
✅ Berhasil menyusun framework pemanfaatan data!

,Data,Pemanfaatan,Output
0,Data Kemiskinan (MBR),Skripsi Analisis Cluster,Peta Sebaran Bantuan Sosial Tepat Sasaran
1,CCTV Dishub / Lalu Lintas,Deep Learning (YOLO),Sistem Deteksi Kemacetan Otomatis
2,Data Stunting (Dinkes),Visualisasi GIS,Dashboard Monitoring Kesehatan Anak
3,Data Kependudukan,Analisis Demografi,Proyeksi Kebutuhan Fasilitas Umum 2030
4,Data Sampah (DLH),Optimasi Rute,Efisiensi Bahan Bakar Truk Sampah

In [ ]:
# 1. INSTALL DEPENDENCIES
import subprocess, sys
print("⏳ Menginstall library yang dibutuhkan...")
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q',
                'requests', 'pandas', 'openpyxl', 'tqdm'], check=True)
print('✅ Setup Library Selesai!')

import requests
import pandas as pd
import time
from tqdm.notebook import tqdm
from google.colab import files

# --- KONFIGURASI ---
TAHUN_MULAI = 2020  # Saya set ke 2020 agar data lebih banyak (karena 2026 masih baru berjalan)
OUTPUT_FILE = 'Laporan_Pemanfaatan_Data_Surabaya.xlsx'

# Query pencarian (Topik-topik utama Open Data Surabaya)
SEMANTIC_QUERIES = [
    'Surabaya open data analysis',
    'Surabaya flood prediction machine learning',
    'Surabaya stunting poverty mapping',
    'Surabaya public transportation data',
    'Surabaya waste management optimization',
    'Surabaya health disease dengue data',
    'Surabaya smart city implementation'
]

# --- FUNGSI ANALISIS OTOMATIS (Sesuai Permintaan Atasan) ---
def klasifikasi_pemanfaatan(abstrak, judul):
    teks = (str(judul) + " " + str(abstrak)).lower()

    # Deteksi Data yang Digunakan (Input)
    data_used = "Data Umum Kota Surabaya"
    if any(x in teks for x in ['penduduk', 'kependudukan', 'citizen']): data_used = "Data Adminduk / Capil"
    elif any(x in teks for x in ['transport', 'bus', 'traffic', 'road']): data_used = "Data Dishub (Transportasi)"
    elif any(x in teks for x in ['stunting', 'health', 'hospital', 'dbd', 'diseases']): data_used = "Data Dinkes (Kesehatan)"
    elif any(x in teks for x in ['poverty', 'kemiskinan', 'mbr', 'social']): data_used = "Data Dinsos (Sosial)"
    elif any(x in teks for x in ['flood', 'waste', 'sampah', 'banjir', 'environment']): data_used = "Data DLH (Lingkungan)"
    elif any(x in teks for x in ['budget', 'anggaran', 'apbd']): data_used = "Data Keuangan/APBD"

    # Deteksi Output Pemanfaatan
    output = "Analisis Deskriptif / Studi Literatur"
    if any(x in teks for x in ['clustering', 'klaster', 'mapping', 'gis']): output = "Peta Sebaran / Zonasi Prioritas"
    elif any(x in teks for x in ['predict', 'forecasting', 'prediksi']): output = "Model Prediksi / Estimasi"
    elif any(x in teks for x in ['dashboard', 'system', 'web', 'application']): output = "Sistem Monitoring / Aplikasi"
    elif any(x in teks for x in ['optimize', 'efficiency', 'optimasi']): output = "Rekomendasi Kebijakan / Efisiensi"

    return data_used, output

# --- PROSES CRAWLING ---
def crawl_data_surabaya(queries):
    BASE_URL = 'https://api.semanticscholar.org/graph/v1/paper/search'
    results = []

    for q in tqdm(queries, desc='Crawling Data'):
        params = {
            'query': q,
            'limit': 20,
            'fields': 'title,year,abstract,url,venue',
            'year': f'{TAHUN_MULAI}-'
        }
        try:
            r = requests.get(BASE_URL, params=params, timeout=15)
            r.raise_for_status()
            papers = r.json().get('data', [])

            for p in papers:
                judul = p.get('title', '')
                abstrak = p.get('abstract', '')

                # Jalankan fungsi analisis otomatis
                input_data, output_impact = klasifikasi_pemanfaatan(abstrak, judul)

                results.append({
                    'Judul Penelitian': judul,
                    'Data Yang Digunakan': input_data,
                    'Output Pemanfaatan': output_impact,
                    'Tahun': p.get('year'),
                    'Sumber Jurnal': p.get('venue', 'N/A'),
                    'Ringkasan': (abstrak[:200] + "...") if abstrak else "No Abstract",
                    'Link Dokumen': p.get('url', '')
                })
            time.sleep(1.0) # Jeda agar tidak kena limit
        except Exception as e:
            print(f"⚠️ Gagal pada query [{q}]: {e}")
            continue

    # Hapus Duplikat
    df = pd.DataFrame(results).drop_duplicates(subset=['Judul Penelitian'])
    return df

# --- EKSEKUSI ---
df_final = crawl_data_surabaya(SEMANTIC_QUERIES)

# Simpan ke Excel dengan Formatting
if not df_final.empty:
    with pd.ExcelWriter(OUTPUT_FILE, engine='openpyxl') as writer:
        df_final.to_excel(writer, index=False, sheet_name='Laporan Pemanfaatan Data')

        # Tambahan: Percantik Excel
        workbook = writer.book
        worksheet = writer.sheets['Laporan Pemanfaatan Data']

        # Beri warna pada header
        from openpyxl.styles import PatternFill, Font
        header_fill = PatternFill(start_color="366092", end_color="366092", fill_type="solid")
        header_font = Font(color="FFFFFF", bold=True)

        for cell in worksheet[1]:
            cell.fill = header_fill
            cell.font = header_font

    print(f"\n✅ SELESAI! {len(df_final)} data berhasil dianalisis.")
    print(f"📁 File '{OUTPUT_FILE}' otomatis terdownload.")

    # Download file ke laptop
    files.download(OUTPUT_FILE)

    # Tampilkan preview di Colab
    display(df_final[['Judul Penelitian', 'Data Yang Digunakan', 'Output Pemanfaatan']].head(10))
else:
    print("❌ Tidak ada data yang ditemukan. Coba ganti keyword atau tahun.")

⏳ Menginstall library yang dibutuhkan...
✅ Setup Library Selesai!

Crawling Data:   0%|          | 0/7 [00:00<?, ?it/s]

⚠️ Gagal pada query [Surabaya open data analysis]: 500 Server Error: Internal Server Error for url: https://api.semanticscholar.org/graph/v1/paper/search?query=Surabaya+open+data+analysis&limit=20&fields=title%2Cyear%2Cabstract%2Curl%2Cvenue&year=2020-
⚠️ Gagal pada query [Surabaya flood prediction machine learning]: 429 Client Error:  for url: https://api.semanticscholar.org/graph/v1/paper/search?query=Surabaya+flood+prediction+machine+learning&limit=20&fields=title%2Cyear%2Cabstract%2Curl%2Cvenue&year=2020-
⚠️ Gagal pada query [Surabaya public transportation data]: 429 Client Error:  for url: https://api.semanticscholar.org/graph/v1/paper/search?query=Surabaya+public+transportation+data&limit=20&fields=title%2Cyear%2Cabstract%2Curl%2Cvenue&year=2020-
⚠️ Gagal pada query [Surabaya waste management optimization]: 429 Client Error:  for url: https://api.semanticscholar.org/graph/v1/paper/search?query=Surabaya+waste+management+optimization&limit=20&fields=title%2Cyear%2Cabstract%2Curl%2Cvenue&year=2020-
⚠️ Gagal pada query [Surabaya health disease dengue data]: 429 Client Error:  for url: https://api.semanticscholar.org/graph/v1/paper/search?query=Surabaya+health+disease+dengue+data&limit=20&fields=title%2Cyear%2Cabstract%2Curl%2Cvenue&year=2020-
⚠️ Gagal pada query [Surabaya smart city implementation]: 429 Client Error:  for url: https://api.semanticscholar.org/graph/v1/paper/search?query=Surabaya+smart+city+implementation&limit=20&fields=title%2Cyear%2Cabstract%2Curl%2Cvenue&year=2020-

✅ SELESAI! 13 data berhasil dianalisis.
📁 File 'Laporan_Pemanfaatan_Data_Surabaya.xlsx' otomatis terdownload.

,Judul Penelitian,Data Yang Digunakan,Output Pemanfaatan
0,IMPLEMENTATION OF K-MEANS AND FUZZY C-MEANS CL...,Data Dinkes (Kesehatan),Peta Sebaran / Zonasi Prioritas
1,Relevance of Stunting and Economic Studies (Su...,Data Dinkes (Kesehatan),Peta Sebaran / Zonasi Prioritas
2,Kausalitas Antara Variabel Makro dan Stunting ...,Data Dinkes (Kesehatan),Peta Sebaran / Zonasi Prioritas
3,Mapping Mangrove Species Distribution and Dens...,Data Dinsos (Sosial),Peta Sebaran / Zonasi Prioritas
4,Mapping Adolescents Vulnerable to Early Marria...,Data Dinkes (Kesehatan),Peta Sebaran / Zonasi Prioritas
5,Spatial Analysis of Stunting Prevalence Accord...,Data Dinkes (Kesehatan),Peta Sebaran / Zonasi Prioritas
6,Urban Informal Settlements and Access to Publi...,Data Dishub (Transportasi),Peta Sebaran / Zonasi Prioritas
7,Pemetaan Kejadian Stunting pada Balita di Kabu...,Data Dinkes (Kesehatan),Peta Sebaran / Zonasi Prioritas
8,Assistance and Empowerment of Pregnant Women t...,Data Dinkes (Kesehatan),Analisis Deskriptif / Studi Literatur
9,Integrating Satellite Imageries and Multiple G...,Data Dinsos (Sosial),Peta Sebaran / Zonasi Prioritas

In [ ]:
import requests
import pandas as pd
import time
from tqdm.notebook import tqdm
from google.colab import files

# --- KONFIGURASI ---
TAHUN_MULAI = 2020
OUTPUT_FILE = 'Laporan_Pemanfaatan_Data_Surabaya_Lengkap.xlsx'

SEMANTIC_QUERIES = [
    'Surabaya open data analysis',
    'Surabaya flood prediction machine learning',
    'Surabaya stunting poverty mapping',
    'Surabaya public transportation data',
    'Surabaya waste management optimization',
    'Surabaya health disease dengue data',
    'Surabaya smart city implementation'
]

def klasifikasi_pemanfaatan(abstrak, judul):
    teks = (str(judul) + " " + str(abstrak)).lower()
    data_used = "Data Umum Kota Surabaya"
    if any(x in teks for x in ['penduduk', 'kependudukan', 'citizen']): data_used = "Data Adminduk / Capil"
    elif any(x in teks for x in ['transport', 'bus', 'traffic', 'road']): data_used = "Data Dishub (Transportasi)"
    elif any(x in teks for x in ['stunting', 'health', 'hospital', 'dbd', 'diseases']): data_used = "Data Dinkes (Kesehatan)"
    elif any(x in teks for x in ['poverty', 'kemiskinan', 'mbr', 'social']): data_used = "Data Dinsos (Sosial)"
    elif any(x in teks for x in ['flood', 'waste', 'sampah', 'banjir', 'environment']): data_used = "Data DLH (Lingkungan)"

    output = "Analisis Deskriptif / Studi Literatur"
    if any(x in teks for x in ['clustering', 'klaster', 'mapping', 'gis']): output = "Peta Sebaran / Zonasi Prioritas"
    elif any(x in teks for x in ['predict', 'forecasting', 'prediksi']): output = "Model Prediksi / Estimasi"
    elif any(x in teks for x in ['dashboard', 'system', 'web', 'application']): output = "Sistem Monitoring / Aplikasi"

    return data_used, output

# --- PROSES CRAWLING DENGAN LOG STATUS ---
def crawl_with_status(queries):
    BASE_URL = 'https://api.semanticscholar.org/graph/v1/paper/search'
    results = []
    status_log = [] # Untuk mencatat yang berhasil/gagal

    for q in tqdm(queries, desc='Crawling Progress'):
        params = {'query': q, 'limit': 20, 'fields': 'title,year,abstract,url,venue', 'year': f'{TAHUN_MULAI}-'}
        try:
            # Tambah jeda lebih lama (3 detik) agar tidak kena error 429 lagi
            time.sleep(3)
            r = requests.get(BASE_URL, params=params, timeout=15)

            if r.status_code == 200:
                papers = r.json().get('data', [])
                if papers:
                    status_log.append({'Keyword': q, 'Status': '✅ Berhasil', 'Keterangan': f'{len(papers)} data ditemukan'})
                    for p in papers:
                        input_data, output_impact = klasifikasi_pemanfaatan(p.get('abstract', ''), p.get('title', ''))
                        results.append({
                            'Judul Penelitian': p.get('title', ''),
                            'Data Yang Digunakan': input_data,
                            'Output Pemanfaatan': output_impact,
                            'Tahun': p.get('year'),
                            'Link': p.get('url', ''),
                            'Keyword Sumber': q
                        })
                else:
                    status_log.append({'Keyword': q, 'Status': '🟡 Kosong', 'Keterangan': 'Tidak ada penelitian di tahun tsb'})
            elif r.status_code == 429:
                status_log.append({'Keyword': q, 'Status': '❌ Gagal (Limit)', 'Keterangan': 'Terdeteksi bot, coba lagi nanti'})
            else:
                status_log.append({'Keyword': q, 'Status': f'❌ Gagal ({r.status_code})', 'Keterangan': 'Server Error'})

        except Exception as e:
            status_log.append({'Keyword': q, 'Status': '❌ Error', 'Keterangan': str(e)})

    return pd.DataFrame(results), pd.DataFrame(status_log)

# --- JALANKAN ---
df_hasil, df_status = crawl_with_status(SEMANTIC_QUERIES)

# Simpan ke Excel dengan 2 Sheet
with pd.ExcelWriter(OUTPUT_FILE) as writer:
    df_hasil.to_excel(writer, sheet_name='Data Pemanfaatan', index=False)
    df_status.to_excel(writer, sheet_name='Log Status Crawling', index=False)

print("\n=== RINGKASAN STATUS CRAWLING ===")
print(df_status.to_string(index=False))

if not df_hasil.empty:
    files.download(OUTPUT_FILE)
    print(f"\n✅ Sukses! {len(df_hasil)} data unik siap dilporkan.")

Crawling Progress:   0%|          | 0/7 [00:00<?, ?it/s]

=== RINGKASAN STATUS CRAWLING ===
                                   Keyword          Status                      Keterangan
               Surabaya open data analysis ❌ Gagal (Limit) Terdeteksi bot, coba lagi nanti
Surabaya flood prediction machine learning ❌ Gagal (Limit) Terdeteksi bot, coba lagi nanti
         Surabaya stunting poverty mapping      ✅ Berhasil                6 data ditemukan
       Surabaya public transportation data ❌ Gagal (Limit) Terdeteksi bot, coba lagi nanti
    Surabaya waste management optimization ❌ Gagal (Limit) Terdeteksi bot, coba lagi nanti
       Surabaya health disease dengue data      ✅ Berhasil               20 data ditemukan
        Surabaya smart city implementation ❌ Gagal (Limit) Terdeteksi bot, coba lagi nanti

✅ Sukses! 26 data unik siap dilporkan.

In [ ]:
import requests
import pandas as pd
import time
from tqdm.notebook import tqdm
from google.colab import files

# --- KONFIGURASI POWERFUL ---
TAHUN_MULAI = 2015 # Mundurkan tahun agar data lebih banyak (Atasan biasanya suka tren 10 tahun)
OUTPUT_FILE = 'Laporan_Menyeluruh_Pemanfaatan_Data_Surabaya.xlsx'

# Tambahkan keyword lebih spesifik & banyak agar hasil menyeluruh
SEMANTIC_QUERIES = [
    # Sektor Transportasi
    'Surabaya transport data analysis', 'Suroboyo Bus data optimization', 'Dishub Surabaya traffic data',
    # Sektor Kesehatan
    'Surabaya health data stunting', 'Surabaya dengue mapping', 'Dinas Kesehatan Surabaya data',
    # Sektor Ekonomi & Sosial
    'Surabaya poverty mapping MBR', 'Surabaya UMKM data analysis', 'Bantuan sosial Surabaya data',
    # Sektor Lingkungan & Bencana
    'Surabaya flood prediction data', 'Surabaya waste management DLH', 'Drainase Surabaya mapping',
    # Sektor Pemerintahan & Kependudukan
    'Surabaya smart city government data', 'Open Data Pemkot Surabaya', 'Kependudukan Surabaya analysis',
    'Layanan Sayang Warga Surabaya data', 'E-budgeting Surabaya analysis'
]

def klasifikasi_pemanfaatan(abstrak, judul):
    teks = (str(judul) + " " + str(abstrak)).lower()
    data_used = "Data Umum Kota Surabaya"
    if any(x in teks for x in ['penduduk', 'kependudukan', 'citizen', 'capil']): data_used = "Data Adminduk / Capil"
    elif any(x in teks for x in ['transport', 'bus', 'traffic', 'road', 'dishub']): data_used = "Data Dishub (Transportasi)"
    elif any(x in teks for x in ['stunting', 'health', 'hospital', 'dbd', 'dinkes']): data_used = "Data Dinkes (Kesehatan)"
    elif any(x in teks for x in ['poverty', 'kemiskinan', 'mbr', 'sosial', 'dinsos']): data_used = "Data Dinsos (Sosial)"
    elif any(x in teks for x in ['flood', 'waste', 'sampah', 'banjir', 'dlh']): data_used = "Data DLH (Lingkungan)"

    output = "Analisis Deskriptif / Studi Literatur"
    if any(x in teks for x in ['clustering', 'klaster', 'mapping', 'gis', 'spasial']): output = "Peta Sebaran / Zonasi Prioritas"
    elif any(x in teks for x in ['predict', 'forecasting', 'prediksi', 'machine learning']): output = "Model Prediksi / Estimasi"
    elif any(x in teks for x in ['dashboard', 'system', 'web', 'application', 'aplikasi']): output = "Sistem Monitoring / Aplikasi"

    return data_used, output

# --- PROSES CRAWLING MENYELURUH ---
def crawl_massal(queries):
    BASE_URL = 'https://api.semanticscholar.org/graph/v1/paper/search'
    results = []

    print(f"🚀 Memulai pencarian menyeluruh untuk {len(queries)} kategori keyword...")

    for q in tqdm(queries, desc='Scanning Sektor'):
        # Kita ambil hingga 50 hasil per keyword (jika ada)
        params = {
            'query': q,
            'limit': 50,
            'fields': 'title,year,abstract,url,venue,authors',
            'year': f'{TAHUN_MULAI}-'
        }

        try:
            time.sleep(3) # Jeda agar tidak kena limit
            r = requests.get(BASE_URL, params=params, timeout=20)

            if r.status_code == 200:
                papers = r.json().get('data', [])
                for p in papers:
                    input_data, output_impact = klasifikasi_pemanfaatan(p.get('abstract', ''), p.get('title', ''))

                    # Ambil nama penulis pertama saja agar rapi
                    penulis = p.get('authors')[0].get('name') if p.get('authors') else "N/A"

                    results.append({
                        'Judul Penelitian': p.get('title', ''),
                        'Penulis': penulis,
                        'Data Yang Digunakan': input_data,
                        'Output Pemanfaatan': output_impact,
                        'Tahun': p.get('year'),
                        'Sumber Jurnal': p.get('venue', 'N/A'),
                        'Link': p.get('url', ''),
                        'Keyword Sumber': q
                    })
            elif r.status_code == 429:
                print(f"⚠️ Limit tercapai pada '{q}', istirahat 10 detik...")
                time.sleep(10)
        except Exception as e:
            continue

    # HAPUS DUPLIKAT (Penting karena satu paper bisa muncul di beberapa keyword)
    df_final = pd.DataFrame(results).drop_duplicates(subset=['Judul Penelitian'])
    return df_final

# --- JALANKAN ---
df_hasil = crawl_massal(SEMANTIC_QUERIES)

if not df_hasil.empty:
    # Urutkan berdasarkan tahun terbaru
    df_hasil = df_hasil.sort_values(by='Tahun', ascending=False)

    # Simpan ke Excel
    df_hasil.to_excel(OUTPUT_FILE, index=False)

    print(f"\n✅ BERHASIL! Mendapatkan {len(df_hasil)} row data unik.")
    print(f"📁 File '{OUTPUT_FILE}' siap dilaporkan ke atasan.")
    files.download(OUTPUT_FILE)

    # Preview
    display(df_hasil.head(10))
else:
    print("❌ Gagal mendapatkan data.")

🚀 Memulai pencarian menyeluruh untuk 17 kategori keyword...

Scanning Sektor:   0%|          | 0/17 [00:00<?, ?it/s]

⚠️ Limit tercapai pada 'Surabaya transport data analysis', istirahat 10 detik...
⚠️ Limit tercapai pada 'Suroboyo Bus data optimization', istirahat 10 detik...
⚠️ Limit tercapai pada 'Dishub Surabaya traffic data', istirahat 10 detik...
⚠️ Limit tercapai pada 'Surabaya dengue mapping', istirahat 10 detik...
⚠️ Limit tercapai pada 'Dinas Kesehatan Surabaya data', istirahat 10 detik...
⚠️ Limit tercapai pada 'Surabaya poverty mapping MBR', istirahat 10 detik...
⚠️ Limit tercapai pada 'Bantuan sosial Surabaya data', istirahat 10 detik...
⚠️ Limit tercapai pada 'Surabaya flood prediction data', istirahat 10 detik...
⚠️ Limit tercapai pada 'Surabaya waste management DLH', istirahat 10 detik...
⚠️ Limit tercapai pada 'Drainase Surabaya mapping', istirahat 10 detik...
⚠️ Limit tercapai pada 'Kependudukan Surabaya analysis', istirahat 10 detik...
⚠️ Limit tercapai pada 'Layanan Sayang Warga Surabaya data', istirahat 10 detik...

✅ BERHASIL! Mendapatkan 246 row data unik.
📁 File 'Laporan_Menyeluruh_Pemanfaatan_Data_Surabaya.xlsx' siap dilaporkan ke atasan.

,Judul Penelitian,Penulis,Data Yang Digunakan,Output Pemanfaatan,Tahun,Sumber Jurnal,Link,Keyword Sumber
75,Analisis Konvergensi Newton–Raphson dalam Esti...,A. Sari,Data Dishub (Transportasi),Analisis Deskriptif / Studi Literatur,2026,Journal of Innovative and Creativity (Joecy),https://www.semanticscholar.org/paper/18e15557...,Surabaya UMKM data analysis
193,Pengaruh Gaya Kepemimpinan dan Kepuasan Kerja ...,Yessy Auralia Febiyanti,Data Umum Kota Surabaya,Analisis Deskriptif / Studi Literatur,2026,Jurnal Publikasi Sistem Informasi dan Manajeme...,https://www.semanticscholar.org/paper/e54dafb1...,Open Data Pemkot Surabaya
195,Comparative analysis of shoreline dynamics in ...,Eko Hadi Santoso,Data Umum Kota Surabaya,Sistem Monitoring / Aplikasi,2026,BIO Web of Conferences,https://www.semanticscholar.org/paper/07b86bd4...,Open Data Pemkot Surabaya
203,Hierarki Birokrasi dalam Sistem Anggaran Digit...,Astried Pamella Cholifah,Data Umum Kota Surabaya,Sistem Monitoring / Aplikasi,2026,AL-KHARAJ,https://www.semanticscholar.org/paper/43b93b9d...,E-budgeting Surabaya analysis
210,RETORIKA TRANSPARANSI DIGITAL VS REALITA KORUP...,Marimbi Liebe Na’illah Dida,Data Umum Kota Surabaya,Analisis Deskriptif / Studi Literatur,2026,KENDALI: Economics and Social Humanities,https://www.semanticscholar.org/paper/6a466cc9...,E-budgeting Surabaya analysis
120,COMPARATIVE ANALYSIS OF SMART ECONOMY STRATEGI...,Sharon Sheilla Shane,Data Dishub (Transportasi),Sistem Monitoring / Aplikasi,2026,"Algebra : Jurnal Pendidikan, Sosial dan Sains",https://www.semanticscholar.org/paper/55f2e6ab...,Surabaya smart city government data
191,ANALISIS STRATEGI GAYA KEPEMIMPINAN DALAM MENI...,Candra Wjaya,Data Umum Kota Surabaya,Analisis Deskriptif / Studi Literatur,2026,Jurnal Manajemen,https://www.semanticscholar.org/paper/17ac7baa...,Open Data Pemkot Surabaya
192,PERAN GURU DALAM PENDEKATAN DEEP LEARNING UNTU...,Devi Amanda Sasabilla,Data Umum Kota Surabaya,Analisis Deskriptif / Studi Literatur,2026,Pendas : Jurnal Ilmiah Pendidikan Dasar,https://www.semanticscholar.org/paper/ce6d2fa7...,Open Data Pemkot Surabaya
194,STUDI KEBUTUHAN DAN KONDISI TOILET UMUM DI TAM...,Leila Pangastuti,Data Dinkes (Kesehatan),Analisis Deskriptif / Studi Literatur,2026,ACADEMIA: Jurnal Inovasi Riset Akademik,https://www.semanticscholar.org/paper/7fa6567e...,Open Data Pemkot Surabaya
32,Development of a family empowerment model to e...,Nusalam Nursalam,Data Dinkes (Kesehatan),Analisis Deskriptif / Studi Literatur,2025,Pediomaternal Nursing Journal,https://www.semanticscholar.org/paper/b6998df2...,Surabaya health data stunting

In [ ]:
import requests
import pandas as pd
import time
from tqdm.notebook import tqdm
from google.colab import files

# --- KONFIGURASI DEEP SCRAPING ---
TAHUN_MULAI = 2010 # Lebih mundur lagi agar data makin ribuan
MAX_HASIL_PER_KEYWORD = 150 # Kita tarik lebih dalam per kategori
OUTPUT_FILE = 'Database_Besar_Pemanfaatan_Data_Surabaya.xlsx'

SEMANTIC_QUERIES = [
    'Surabaya data driven', 'Surabaya smart city research', 'Open Data Surabaya',
    'Surabaya public service data', 'Surabaya health mapping', 'Surabaya transport analysis',
    'Kemiskinan Surabaya data', 'Stunting Surabaya data', 'Banjir Surabaya data',
    'Surabaya urban planning data', 'E-government Surabaya implementation'
]

def klasifikasi_pemanfaatan(abstrak, judul):
    teks = (str(judul) + " " + str(abstrak)).lower()
    data_used = "Data Umum Kota Surabaya"
    if any(x in teks for x in ['penduduk', 'kependudukan', 'citizen']): data_used = "Data Adminduk"
    elif any(x in teks for x in ['transport', 'bus', 'dishub']): data_used = "Data Dishub"
    elif any(x in teks for x in ['stunting', 'health', 'dinkes']): data_used = "Data Dinkes"
    elif any(x in teks for x in ['poverty', 'miskin', 'mbr']): data_used = "Data Dinsos"
    elif any(x in teks for x in ['flood', 'waste', 'dlh']): data_used = "Data DLH"

    output = "Analisis Deskriptif"
    if any(x in teks for x in ['clustering', 'mapping', 'gis']): output = "Peta / Zonasi"
    elif any(x in teks for x in ['predict', 'forecasting']): output = "Model Prediksi"
    elif any(x in teks for x in ['system', 'web', 'app']): output = "Sistem / Aplikasi"

    return data_used, output

def deep_scraping():
    BASE_URL = 'https://api.semanticscholar.org/graph/v1/paper/search'
    results = []

    print(f"🚀 Memulai Deep Scraping... Target: {len(SEMANTIC_QUERIES) * MAX_HASIL_PER_KEYWORD} potensi data.")

    for q in tqdm(SEMANTIC_QUERIES, desc='Kategori'):
        offset = 0
        while offset < MAX_HASIL_PER_KEYWORD:
            params = {
                'query': q,
                'limit': 50, # Ambil 50 per tarikan
                'offset': offset,
                'fields': 'title,year,abstract,url,authors,venue',
                'year': f'{TAHUN_MULAI}-'
            }
            try:
                time.sleep(2) # Delay diperkecil tapi tetap aman
                r = requests.get(BASE_URL, params=params, timeout=20)

                if r.status_code == 200:
                    data = r.json().get('data', [])
                    if not data: break # Berhenti jika sudah tidak ada data lagi

                    for p in data:
                        input_data, output_impact = klasifikasi_pemanfaatan(p.get('abstract', ''), p.get('title', ''))
                        results.append({
                            'Judul': p.get('title', ''),
                            'Penulis': p.get('authors')[0].get('name') if p.get('authors') else "N/A",
                            'Data Yang Digunakan': input_data,
                            'Output Pemanfaatan': output_impact,
                            'Tahun': p.get('year'),
                            'Jurnal': p.get('venue', 'N/A'),
                            'Link': p.get('url', '')
                        })
                    offset += 50 # Lanjut ke halaman berikutnya
                elif r.status_code == 429:
                    print("⚠️ Terdeteksi bot, istirahat 30 detik...")
                    time.sleep(30)
                    continue
                else: break
            except: break

    df = pd.DataFrame(results).drop_duplicates(subset=['Judul'])
    return df

# --- EKSEKUSI ---
df_final = deep_scraping()
df_final.to_excel(OUTPUT_FILE, index=False)
print(f"✅ Selesai! Berhasil mengumpulkan {len(df_final)} baris data.")
files.download(OUTPUT_FILE)

🚀 Memulai Deep Scraping... Target: 1650 potensi data.

Kategori:   0%|          | 0/11 [00:00<?, ?it/s]

⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...
⚠️ Terdeteksi bot, istirahat 30 detik...

In [ ]:
import requests
import pandas as pd
import time
from tqdm.notebook import tqdm
from google.colab import files

# --- KONFIGURASI TAHUN TERBARU ---
TAHUN_MULAI = 2021  # Membatasi hanya 5 tahun terakhir
MAX_DATA_PER_KEYWORD = 200  # Mengambil hingga 200 data per kategori keyword
OUTPUT_FILE = 'Laporan_Data_Surabaya_5_Tahun_Terakhir.xlsx'

SEMANTIC_QUERIES = [
    'Surabaya smart city data 2021..2026',
    'pemanfaatan data dashboard Surabaya',
    'Surabaya machine learning public service',
    'analisis data stunting Surabaya terbaru',
    'optimasi rute transportasi Surabaya data',
    'Surabaya flood early warning system data',
    'pemanfaatan data kemiskinan surabaya digital',
    'surabaya open data impact analysis'
]

def klasifikasi_pemanfaatan(abstrak, judul):
    teks = (str(judul) + " " + str(abstrak)).lower()
    data_used = "Data Kota Surabaya (Lintas Dinas)"

    # Identifikasi Data Spesifik
    if any(x in teks for x in ['stunting', 'health', 'dinkes', 'puskesmas']): data_used = "Data Dinas Kesehatan"
    elif any(x in teks for x in ['transport', 'bus', 'dishub', 'traffic']): data_used = "Data Dinas Perhubungan"
    elif any(x in teks for x in ['poverty', 'miskin', 'mbr', 'sosial']): data_used = "Data Dinas Sosial"
    elif any(x in teks for x in ['flood', 'waste', 'dlh', 'banjir', 'sampah']): data_used = "Data Dinas Lingkungan Hidup"
    elif any(x in teks for x in ['penduduk', 'citizen', 'capil', 'kependudukan']): data_used = "Data Dispendukcapil"

    # Identifikasi Output
    output = "Analisis Deskriptif & Rekomendasi"
    if any(x in teks for x in ['clustering', 'mapping', 'gis', 'peta', 'spasial']): output = "Peta Sebaran & Zonasi Wilayah"
    elif any(x in teks for x in ['predict', 'forecasting', 'estimasi', 'machine learning']): output = "Model Prediksi / Kecerdasan Buatan"
    elif any(x in teks for x in ['dashboard', 'system', 'web', 'application', 'real-time']): output = "Sistem Monitoring & Dashboard"
    elif any(x in teks for x in ['policy', 'kebijakan', 'evaluasi']): output = "Evaluasi Kebijakan Publik"

    return data_used, output

def deep_crawl():
    BASE_URL = 'https://api.semanticscholar.org/graph/v1/paper/search'
    results = []

    print(f"🚀 Memulai Deep Scraper untuk rentang tahun {TAHUN_MULAI} - 2026")

    for q in tqdm(SEMANTIC_QUERIES, desc='Kategori'):
        offset = 0
        while offset < MAX_DATA_PER_KEYWORD:
            params = {
                'query': q,
                'limit': 50,  # Tarik 50 data per request
                'offset': offset,
                'fields': 'title,year,abstract,url,authors,venue',
                'year': f'{TAHUN_MULAI}-'
            }
            try:
                # Jeda 3 detik agar server tidak mendeteksi sebagai bot agresif
                time.sleep(3)
                r = requests.get(BASE_URL, params=params, timeout=20)

                if r.status_code == 200:
                    data = r.json().get('data', [])
                    if not data: break # Berhenti jika data sudah habis

                    for p in data:
                        input_data, output_hasil = klasifikasi_pemanfaatan(p.get('abstract', ''), p.get('title', ''))
                        results.append({
                            'Judul Penelitian': p.get('title', ''),
                            'Penulis': p.get('authors')[0].get('name') if p.get('authors') else "N/A",
                            'Tahun': p.get('year'),
                            'Instansi/Dinas Terkait': input_data,
                            'Output Pemanfaatan Data': output_hasil,
                            'Jurnal/Venue': p.get('venue', 'N/A'),
                            'Link Dokumen': p.get('url', ''),
                            'Keyword': q
                        })
                    offset += 50 # Pindah ke halaman berikutnya
                elif r.status_code == 429:
                    print("⚠️ Terdeteksi bot oleh server, istirahat 20 detik...")
                    time.sleep(20)
                    continue
                else:
                    break
            except Exception as e:
                print(f"⚠️ Gangguan pada keyword '{q}': {e}")
                break

    # Membersihkan duplikat (karena satu paper bisa masuk di beberapa keyword)
    df_final = pd.DataFrame(results).drop_duplicates(subset=['Judul Penelitian'])
    return df_final

# --- JALANKAN PROSES ---
df_final = deep_crawl()

if not df_final.empty:
    # Simpan ke Excel
    df_final.to_excel(OUTPUT_FILE, index=False)
    print(f"\n✅ SELESAI! Berhasil mengumpulkan {len(df_final)} data unik dari 5 tahun terakhir.")
    files.download(OUTPUT_FILE)

    # Preview hasil
    display(df_final.head(10))
else:
    print("❌ Tidak ada data yang ditemukan. Coba jalankan ulang dalam beberapa saat.")

🚀 Memulai Deep Scraper untuk rentang tahun 2021 - 2026

Kategori:   0%|          | 0/8 [00:00<?, ?it/s]

⚠️ Terdeteksi bot oleh server, istirahat 20 detik...
⚠️ Terdeteksi bot oleh server, istirahat 20 detik...
⚠️ Terdeteksi bot oleh server, istirahat 20 detik...
⚠️ Terdeteksi bot oleh server, istirahat 20 detik...
⚠️ Terdeteksi bot oleh server, istirahat 20 detik...
⚠️ Terdeteksi bot oleh server, istirahat 20 detik...
⚠️ Terdeteksi bot oleh server, istirahat 20 detik...
⚠️ Terdeteksi bot oleh server, istirahat 20 detik...
⚠️ Terdeteksi bot oleh server, istirahat 20 detik...
⚠️ Terdeteksi bot oleh server, istirahat 20 detik...
⚠️ Terdeteksi bot oleh server, istirahat 20 detik...
⚠️ Terdeteksi bot oleh server, istirahat 20 detik...
⚠️ Terdeteksi bot oleh server, istirahat 20 detik...
⚠️ Terdeteksi bot oleh server, istirahat 20 detik...
⚠️ Terdeteksi bot oleh server, istirahat 20 detik...
⚠️ Terdeteksi bot oleh server, istirahat 20 detik...
⚠️ Terdeteksi bot oleh server, istirahat 20 detik...
⚠️ Terdeteksi bot oleh server, istirahat 20 detik...
⚠️ Terdeteksi bot oleh server, istirahat 20 detik...
⚠️ Terdeteksi bot oleh server, istirahat 20 detik...
⚠️ Terdeteksi bot oleh server, istirahat 20 detik...

KeyboardInterrupt:

In [ ]:
import requests
import pandas as pd
import time
import random
from tqdm.notebook import tqdm
from google.colab import files

# --- KONFIGURASI TAHUN TERBARU ---
TAHUN_MULAI = 2021
OUTPUT_FILE = 'Laporan_Data_Surabaya_Terbaru.xlsx'

# Kita persempit jumlah keyword tapi buat lebih variatif
SEMANTIC_QUERIES = [
    'Surabaya city data',
    'pemerintah kota surabaya analysis',
    'smart city surabaya',
    'surabaya health data',
    'surabaya transport data',
    'surabaya flood system'
]

def klasifikasi_pemanfaatan(abstrak, judul):
    teks = (str(judul) + " " + str(abstrak)).lower()
    data_used = "Data Umum Kota Surabaya"
    if any(x in teks for x in ['stunting', 'health', 'dinkes']): data_used = "Data Dinas Kesehatan"
    elif any(x in teks for x in ['transport', 'bus', 'dishub']): data_used = "Data Dinas Perhubungan"
    elif any(x in teks for x in ['poverty', 'miskin', 'mbr']): data_used = "Data Dinas Sosial"

    output = "Analisis Deskriptif"
    if any(x in teks for x in ['mapping', 'gis', 'peta']): output = "Peta Sebaran & Zonasi"
    elif any(x in teks for x in ['predict', 'machine learning']): output = "Model Prediksi / AI"
    elif any(x in teks for x in ['dashboard', 'system', 'web']): output = "Sistem & Dashboard"

    return data_used, output

def sneaky_crawl():
    BASE_URL = 'https://api.semanticscholar.org/graph/v1/paper/search'
    results = []

    print(f"🚀 Memulai Sneaky Scraper (Mode Gerilya) - Rentang {TAHUN_MULAI}-2026")

    for q in tqdm(SEMANTIC_QUERIES, desc='Kategori'):
        # Kita ambil 30 data saja per keyword agar tidak dicurigai bot
        params = {
            'query': q,
            'limit': 30,
            'fields': 'title,year,abstract,url,authors',
            'year': f'{TAHUN_MULAI}-'
        }
        try:
            # JEDA RANDOM: Ini rahasianya. Server bingung kalau jedanya tidak tetap.
            time.sleep(random.uniform(5, 10))

            r = requests.get(BASE_URL, params=params, timeout=20)

            if r.status_code == 200:
                data = r.json().get('data', [])
                if data:
                    for p in data:
                        input_data, output_hasil = klasifikasi_pemanfaatan(p.get('abstract', ''), p.get('title', ''))
                        results.append({
                            'Judul': p.get('title', ''),
                            'Penulis': p.get('authors')[0].get('name') if p.get('authors') else "N/A",
                            'Tahun': p.get('year'),
                            'Instansi': input_data,
                            'Output': output_hasil,
                            'Link': p.get('url', '')
                        })
                else:
                    print(f"🟡 Keyword '{q}' tidak ada hasil.")
            elif r.status_code == 429:
                print(f"⚠️ Kena Limit! Istirahat total 45 detik...")
                time.sleep(45) # Istirahat lebih lama jika kena blokir
            else:
                print(f"❌ Error {r.status_code} pada keyword {q}")
        except Exception as e:
            print(f"⚠️ Gangguan: {e}")

    df_final = pd.DataFrame(results).drop_duplicates(subset=['Judul'])
    return df_final

# --- JALANKAN ---
df_final = sneaky_crawl()

if not df_final.empty:
    df_final.to_excel(OUTPUT_FILE, index=False)
    print(f"\n✅ BERHASIL! Mendapatkan {len(df_final)} data segar.")
    files.download(OUTPUT_FILE)
    display(df_final.head(5))
else:
    print("❌ Masih gagal tembus. IP Colab sedang diblokir ketat oleh server tujuan.")

🚀 Memulai Sneaky Scraper (Mode Gerilya) - Rentang 2021-2026

Kategori:   0%|          | 0/6 [00:00<?, ?it/s]

⚠️ Kena Limit! Istirahat total 45 detik...
⚠️ Kena Limit! Istirahat total 45 detik...
⚠️ Kena Limit! Istirahat total 45 detik...
⚠️ Kena Limit! Istirahat total 45 detik...
⚠️ Kena Limit! Istirahat total 45 detik...

✅ BERHASIL! Mendapatkan 30 data segar.

,Judul,Penulis,Tahun,Instansi,Output,Link
0,Evaluasi Implementasi Fasilitas Intelligent Tr...,Sitti Adiyaksa Fazrian,2025,Data Dinas Perhubungan,Sistem & Dashboard,https://www.semanticscholar.org/paper/2cabefa0...
1,Using Bottleneck Analysis to Improve Neonatal ...,Arif Tyebally,2025,Data Dinas Kesehatan,Sistem & Dashboard,https://www.semanticscholar.org/paper/bec6b1b4...
2,Strategi Mengatasi Kemacetan Lalu Lintas Melal...,Adita Nurshabrina,2025,Data Dinas Perhubungan,Sistem & Dashboard,https://www.semanticscholar.org/paper/fdeddab3...
3,Analysis of Sea Transport Passenger Services o...,Mochammad Nanda,2025,Data Dinas Perhubungan,Sistem & Dashboard,https://www.semanticscholar.org/paper/201e3564...
4,Efektivitas Program Surabaya Intelligent Trans...,Y. Subianto,2024,Data Dinas Perhubungan,Sistem & Dashboard,https://www.semanticscholar.org/paper/45e0067c...

In [ ]:
import requests
import pandas as pd
import time
import random
from tqdm.notebook import tqdm
from google.colab import files

# --- KONFIGURASI ---
TAHUN_MULAI = 2021
LIMIT_PER_QUERY = 150
OUTPUT_FILE = 'Laporan_Dampak_Data_Surabaya_Fix.xlsx'

# Daftar Query yang sangat spesifik untuk memancing hasil lebih banyak
QUERIES = [
    'surabaya government open data implementation',
    'pemanfaatan big data kota surabaya',
    'surabaya smart city dashboard impact',
    'surabaya flood monitoring system data',
    'surabaya health data analysis stunting',
    'surabaya transportation data optimization',
    'pemanfaatan data kependudukan surabaya',
    'surabaya poverty mapping digital',
    'implementasi e-government surabaya',
    'surabaya public service digital transformation'
]

HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

def analisis_dampak_spesifik(abstrak, judul):
    teks = (str(judul) + " " + str(abstrak)).lower()

    # Logika Dampak yang lebih mendalam
    if any(x in teks for x in ['predict', 'prediksi', 'forecasting']):
        return "Mendukung sistem peringatan dini dan perencanaan anggaran berbasis estimasi data masa depan."
    elif any(x in teks for x in ['map', 'gis', 'spatial', 'peta']):
        return "Optimalisasi distribusi sumber daya dan bantuan sosial agar tepat sasaran berdasarkan lokasi geografis."
    elif any(x in teks for x in ['dashboard', 'monitoring', 'real-time']):
        return "Meningkatkan transparansi publik dan mempercepat respon dinas terhadap keluhan warga."
    elif any(x in teks for x in ['optimization', 'efisiensi', 'rute']):
        return "Mengurangi biaya operasional pemerintah dan waktu tunggu layanan publik bagi masyarakat."
    elif any(x in teks for x in ['classification', 'cluster', 'k-means']):
        return "Otomatisasi pengelompokan profil warga (seperti MBR atau balita stunting) untuk intervensi kebijakan yang lebih akurat."
    elif any(x in teks for x in ['iot', 'sensor', 'smart']):
        return "Transformasi layanan manual menjadi otomatis, mengurangi human error dalam pendataan lapangan."

    return "Meningkatkan kualitas pengambilan keputusan berbasis data (Data-Driven Decision Making) di lingkup Pemkot."

def mega_crawl():
    BASE_URL = 'https://api.semanticscholar.org/graph/v1/paper/search'
    results = []

    print(f"🚀 Memulai...")

    for q in tqdm(QUERIES, desc='Kategori'):
        offset = 0
        while offset < LIMIT_PER_QUERY:
            params = {
                'query': q,
                'limit': 50,
                'offset': offset,
                'fields': 'title,year,abstract,url,authors,venue',
                'year': f'{TAHUN_MULAI}-'
            }
            try:
                # Jeda random lebih lama agar tidak dianggap serangan bot
                time.sleep(random.uniform(3, 6))
                r = requests.get(BASE_URL, params=params, headers=HEADERS, timeout=25)

                if r.status_code == 200:
                    data = r.json().get('data', [])
                    if not data: break

                    for p in data:
                        abs_text = p.get('abstract', '') or ""
                        judul_text = p.get('title', '') or ""
                        dampak_nyata = analisis_dampak_spesifik(abs_text, judul_text)

                        results.append({
                            'Judul Penelitian': judul_text,
                            'Penulis': p.get('authors')[0].get('name') if p.get('authors') else "N/A",
                            'Tahun': p.get('year'),
                            'Jurnal/Sumber': p.get('venue', 'N/A'),
                            'Dampak Nyata Pemanfaatan Data': dampak_nyata,
                            'Link Dokumen': p.get('url', ''),
                            'Keyword': q
                        })
                    offset += 50
                elif r.status_code == 429:
                    print(f"⚠️ Limit tercapai pada {q}. Istirahat 40 detik...")
                    time.sleep(40)
                    # Jika sudah 429, kurangi kecepatan lebih ekstrem
                    offset += 0
                else:
                    break
            except Exception as e:
                print(f"⚠️ Error: {e}")
                break

    # Menghapus duplikat
    df = pd.DataFrame(results)
    if not df.empty:
        df = df.drop_duplicates(subset=['Judul Penelitian'])
    return df

# --- EKSEKUSI ---
df_final = mega_crawl()

# Cek apakah df_final ada isinya sebelum download (Fix NameError)
if not df_final.empty:
    df_final.to_excel(OUTPUT_FILE, index=False)
    print(f"\n✅ SELESAI! Berhasil mengumpulkan {len(df_final)} data unik.")
    files.download(OUTPUT_FILE)
    display(df_final.head(10))
else:
    print("\n❌ Gagal mendapatkan data. Coba ganti koneksi internet atau tunggu 10 menit.")

🚀 Memulai...

Kategori:   0%|          | 0/10 [00:00<?, ?it/s]

⚠️ Limit tercapai pada surabaya government open data implementation. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya government open data implementation. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya government open data implementation. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya government open data implementation. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya government open data implementation. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya government open data implementation. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya government open data implementation. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya government open data implementation. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya government open data implementation. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya government open data implementation. Istirahat 40 detik...
⚠️ Limit tercapai pada pemanfaatan big data kota surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada pemanfaatan big data kota surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada pemanfaatan big data kota surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada pemanfaatan big data kota surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada pemanfaatan big data kota surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya smart city dashboard impact. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya smart city dashboard impact. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya smart city dashboard impact. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya smart city dashboard impact. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya smart city dashboard impact. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya smart city dashboard impact. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya smart city dashboard impact. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya smart city dashboard impact. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya smart city dashboard impact. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya flood monitoring system data. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya flood monitoring system data. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya flood monitoring system data. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya health data analysis stunting. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya health data analysis stunting. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya health data analysis stunting. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya health data analysis stunting. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya health data analysis stunting. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya health data analysis stunting. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya health data analysis stunting. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya health data analysis stunting. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya health data analysis stunting. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya health data analysis stunting. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya health data analysis stunting. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya health data analysis stunting. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya health data analysis stunting. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya health data analysis stunting. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya health data analysis stunting. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya health data analysis stunting. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya health data analysis stunting. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya transportation data optimization. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya transportation data optimization. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya transportation data optimization. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya transportation data optimization. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya transportation data optimization. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya transportation data optimization. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya transportation data optimization. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya transportation data optimization. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya transportation data optimization. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya transportation data optimization. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya transportation data optimization. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya transportation data optimization. Istirahat 40 detik...
⚠️ Limit tercapai pada pemanfaatan data kependudukan surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada pemanfaatan data kependudukan surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada pemanfaatan data kependudukan surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada pemanfaatan data kependudukan surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada pemanfaatan data kependudukan surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada pemanfaatan data kependudukan surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada pemanfaatan data kependudukan surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada pemanfaatan data kependudukan surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada pemanfaatan data kependudukan surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada pemanfaatan data kependudukan surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya poverty mapping digital. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya poverty mapping digital. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya poverty mapping digital. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya poverty mapping digital. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya poverty mapping digital. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya poverty mapping digital. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya poverty mapping digital. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya poverty mapping digital. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya poverty mapping digital. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya poverty mapping digital. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya poverty mapping digital. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya poverty mapping digital. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya poverty mapping digital. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya poverty mapping digital. Istirahat 40 detik...
⚠️ Limit tercapai pada implementasi e-government surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada implementasi e-government surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada implementasi e-government surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada implementasi e-government surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada implementasi e-government surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada implementasi e-government surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada implementasi e-government surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada implementasi e-government surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada implementasi e-government surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada implementasi e-government surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada implementasi e-government surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada implementasi e-government surabaya. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya public service digital transformation. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya public service digital transformation. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya public service digital transformation. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya public service digital transformation. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya public service digital transformation. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya public service digital transformation. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya public service digital transformation. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya public service digital transformation. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya public service digital transformation. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya public service digital transformation. Istirahat 40 detik...
⚠️ Limit tercapai pada surabaya public service digital transformation. Istirahat 40 detik...

✅ SELESAI! Berhasil mengumpulkan 1243 data unik.

,Judul Penelitian,Penulis,Tahun,Jurnal/Sumber,Dampak Nyata Pemanfaatan Data,Link Dokumen,Keyword
0,Implementasi Kebijakan Open Government Data (O...,Muhammad Sultan Wachid,2024,VISA: Journal of Vision and Ideas,"Transformasi layanan manual menjadi otomatis, ...",https://www.semanticscholar.org/paper/7cf0d478...,surabaya government open data implementation
1,Implementation of Big Data Information System ...,Rizqi Putri Nourma Budiarti,2023,JOIV: International Journal on Informatics Vis...,Optimalisasi distribusi sumber daya dan bantua...,https://www.semanticscholar.org/paper/50aa8c2c...,surabaya government open data implementation
2,Open Government Data for Urban Management in I...,C. Rahmah,2024,IOP Conference Series: Earth and Environment,"Transformasi layanan manual menjadi otomatis, ...",https://www.semanticscholar.org/paper/154de4e3...,surabaya government open data implementation
3,Recognition of prior learning program in impro...,Siti Nur Alifa,2024,Jurnal EDUCATIO: Jurnal Pendidikan Indonesia,Meningkatkan kualitas pengambilan keputusan be...,https://www.semanticscholar.org/paper/671f9b58...,surabaya government open data implementation
4,Implementation of the Inaportnet Policy for Sh...,Eka Prastyo M.,2022,International Journal of Current Science Resea...,Optimalisasi distribusi sumber daya dan bantua...,https://www.semanticscholar.org/paper/8d79010d...,surabaya government open data implementation
5,Collaborative Governance of Public Service Mal...,Rachmad Wahyu Kurniawan,2025,Asian Journal of Applied Business and Management,Meningkatkan kualitas pengambilan keputusan be...,https://www.semanticscholar.org/paper/70f118b0...,surabaya government open data implementation
6,ENHANCING ACCOUNTABILITY AND TRANSPARENCY IN L...,M. Hidayat,2024,VISIONER : Jurnal Pemerintahan Daerah di Indon...,Meningkatkan transparansi publik dan mempercep...,https://www.semanticscholar.org/paper/f6f13a99...,surabaya government open data implementation
7,Kemitraan Pemerintah dan Swasta Tentang Pengel...,Borhanudin Achmad Safi,2022,Aplikasi Administrasi,Meningkatkan transparansi publik dan mempercep...,https://www.semanticscholar.org/paper/4ecfd363...,surabaya government open data implementation
8,How does ambidextrous leadership influence inn...,Raden Dedy Chairil Zain,2025,Cogent Business &amp; Management,"Transformasi layanan manual menjadi otomatis, ...",https://www.semanticscholar.org/paper/c68c9ca4...,surabaya government open data implementation
9,Teacher problems on children with special need...,Helfi Liani,2024,Kepompong Children Centre Journal,Meningkatkan kualitas pengambilan keputusan be...,https://www.semanticscholar.org/paper/939a951c...,surabaya government open data implementation

In [ ]:
import requests
import pandas as pd
import time
import random
from tqdm.notebook import tqdm
from google.colab import files

# --- KONFIGURASI ---
TAHUN_MULAI = 2021
LIMIT_PER_QUERY = 150 # Mengambil data lebih dalam per kategori
OUTPUT_FILE = 'Analisis_Pemanfaatan_Data_Surabaya_2021_2026.xlsx'

# Keyword Spesifik Surabaya (Lokal & Teknis)
SEMANTIC_QUERIES = [
    'pemerintah kota surabaya data analysis',
    'implementasi open data surabaya',
    'surabaya smart city impact',
    'pemanfaatan data kemiskinan surabaya',
    'data stunting dinas kesehatan surabaya',
    'optimasi transportasi surabaya bus data',
    'surabaya flood early warning system',
    'layanan publik digital surabaya',
    'analisis data adminduk surabaya',
    'e-government kota surabaya pemanfaatan data'
]

def analisis_output_dampak(judul, abstrak):
    """Menerjemahkan Judul & Abstrak menjadi Dampak/Manfaat Nyata"""
    teks = (str(judul) + " " + str(abstrak)).lower()

    # Logic Analisis Dampak
    if any(x in teks for x in ['predict', 'prediksi', 'forecasting']):
        return "Model Prediksi: Memberikan estimasi angka masa depan untuk perencanaan anggaran dan mitigasi risiko dinas."
    elif any(x in teks for x in ['map', 'gis', 'spasial', 'peta', 'zonasi']):
        return "Pemetaan Digital: Penentuan wilayah prioritas agar distribusi bantuan sosial atau layanan kesehatan tepat sasaran."
    elif any(x in teks for x in ['dashboard', 'monitoring', 'real-time']):
        return "Sistem Monitoring: Transparansi data kinerja dinas secara langsung (real-time) untuk percepatan respon layanan."
    elif any(x in teks for x in ['optimasi', 'efisiensi', 'rute']):
        return "Efisiensi Operasional: Pengurangan biaya atau waktu layanan publik melalui perbaikan sistem birokrasi/logistik."
    elif any(x in teks for x in ['iot', 'sensor', 'smart city']):
        return "Otomatisasi Layanan: Pengumpulan data lapangan otomatis (seperti sensor banjir/sampah) tanpa input manual."
    elif any(x in teks for x in ['clustering', 'klaster', 'profiling']):
        return "Profiling Warga: Pengelompokan data warga (seperti MBR atau stunting) untuk intervensi kebijakan yang lebih personal."

    return "Analisis Strategis: Memberikan dasar ilmiah bagi pengambilan keputusan Wali Kota / Kepala Dinas."

def deep_scholar_crawl():
    BASE_URL = 'https://api.semanticscholar.org/graph/v1/paper/search'
    results = []

    print(f"🚀 Memulai Deep Crawling Data Surabaya ({TAHUN_MULAI}-2026)...")

    for q in tqdm(SEMANTIC_QUERIES, desc='Kategori'):
        offset = 0
        while offset < LIMIT_PER_QUERY:
            params = {
                'query': q,
                'limit': 50,
                'offset': offset,
                'fields': 'title,year,abstract,url,authors,venue',
                'year': f'{TAHUN_MULAI}-'
            }
            try:
                # Jeda agar tidak kena blokir (Rate Limit 429)
                time.sleep(random.uniform(4, 6))
                r = requests.get(BASE_URL, params=params, timeout=25)

                if r.status_code == 200:
                    data = r.json().get('data', [])
                    if not data: break # Berhenti jika sudah tidak ada data

                    for p in data:
                        judul = p.get('title', '')
                        abstrak = p.get('abstract', '') or ""

                        # Jalankan Analisis Dampak
                        dampak_nyata = analisis_output_dampak(judul, abstrak)

                        results.append({
                            'Judul Analisis/Skripsi': judul,
                            'Penulis': p.get('authors')[0].get('name') if p.get('authors') else "N/A",
                            'Tahun': p.get('year'),
                            'Dampak & Output Pemanfaatan': dampak_nyata,
                            'Sumber/Jurnal': p.get('venue', 'N/A'),
                            'Link Dokumen': p.get('url', ''),
                            'Keyword Pemicu': q
                        })
                    offset += 50
                elif r.status_code == 429:
                    print(f"⚠️ Limit API! Istirahat 45 detik untuk reset IP...")
                    time.sleep(45)
                else:
                    break
            except Exception as e:
                print(f"⚠️ Gangguan pada {q}: {e}")
                break

    # Membersihkan Duplikat
    df = pd.DataFrame(results)
    if not df.empty:
        df = df.drop_duplicates(subset=['Judul Analisis/Skripsi'])
    return df

# --- EKSEKUSI ---
df_final = deep_scholar_crawl()

if not df_final.empty:
    df_final.to_excel(OUTPUT_FILE, index=False)
    print(f"\n✅ SELESAI! Berhasil mengumpulkan {len(df_final)} data Surabaya.")
    files.download(OUTPUT_FILE)

    # Tampilkan Preview
    print("\n--- PREVIEW HASIL ---")
    pd.set_option('display.max_colwidth', 100)
    display(df_final[['Judul Analisis/Skripsi', 'Dampak & Output Pemanfaatan']].head(10))
else:
    print("❌ Gagal mendapatkan data. Pastikan koneksi stabil.")

🚀 Memulai Deep Crawling Data Surabaya (2021-2026)...

Kategori:   0%|          | 0/10 [00:00<?, ?it/s]

⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...
⚠️ Limit API! Istirahat 45 detik untuk reset IP...

✅ SELESAI! Berhasil mengumpulkan 1253 data Surabaya.

--- PREVIEW HASIL ---

,Judul Analisis/Skripsi,Dampak & Output Pemanfaatan
0,EFEKTIVITAS PENERAPAN APLIKASI SIPANAS (SISTEM INFORMASI PERJALANAN DINAS) DI PEMERINTAH KOTA SU...,Analisis Strategis: Memberikan dasar ilmiah bagi pengambilan keputusan Wali Kota / Kepala Dinas.
1,Pengaruh Displin Kerja dan Self Efficacy Terhadap Kinerja Pegawai Kecamatan Tambaksari Pemerinta...,Analisis Strategis: Memberikan dasar ilmiah bagi pengambilan keputusan Wali Kota / Kepala Dinas.
2,Peran Pemerintah Kota Surabaya dalam Menanggulangi Bencana Banjir di Kecamatan Pakal Kota Surabaya,Analisis Strategis: Memberikan dasar ilmiah bagi pengambilan keputusan Wali Kota / Kepala Dinas.
3,Pola Kemitraan Pemerintah Kota Surabaya dan Masyarakat Dalam Pengelolaan Sampah di Jambangan Kot...,Analisis Strategis: Memberikan dasar ilmiah bagi pengambilan keputusan Wali Kota / Kepala Dinas.
4,Strategi Pemerintah Kota Surabaya Dalam Upaya Percepatan Penurunan Stunting,Analisis Strategis: Memberikan dasar ilmiah bagi pengambilan keputusan Wali Kota / Kepala Dinas.
5,Analisis Kinerja Keuangan Pemerintah Daerah Berdasarkan Value For Money Pada Pemerintah Kota Sur...,Analisis Strategis: Memberikan dasar ilmiah bagi pengambilan keputusan Wali Kota / Kepala Dinas.
6,PENGARUH BELANJA PEMERINTAH DAN PAD TERHADAP PDRB TAHUN 2014-2022 DI KOTA SURABAYA,Analisis Strategis: Memberikan dasar ilmiah bagi pengambilan keputusan Wali Kota / Kepala Dinas.
7,Pengaruh Akuntabilitas Dan Transparansi Terhadap Kinerja Instansi Pemerintah Daerah Kota Surabaya,Analisis Strategis: Memberikan dasar ilmiah bagi pengambilan keputusan Wali Kota / Kepala Dinas.
8,"Hubungan antara Kesiapan Menghadapi Perubahan, Persepsi Dukungan Organisasi, Psychological Capit...",Analisis Strategis: Memberikan dasar ilmiah bagi pengambilan keputusan Wali Kota / Kepala Dinas.
9,ANALISIS EFEKTIVITAS KINERJA KEUANGAN DALAM PENGELOLAAN ANGGARAN PEMERINTAH DAN BELANJA DAERAH P...,Analisis Strategis: Memberikan dasar ilmiah bagi pengambilan keputusan Wali Kota / Kepala Dinas.

In [ ]:
import requests
import pandas as pd
import time
import random
from tqdm.notebook import tqdm
from google.colab import files

# --- KONFIGURASI ---
TAHUN_MULAI = 2021
LIMIT_PER_QUERY = 100
OUTPUT_FILE = 'Analisis_Pemanfaatan_Data_Surabaya_Strict.xlsx'

# Keyword lebih spesifik (pake tanda kutip untuk pencarian eksak di API)
SEMANTIC_QUERIES = [
    '"Surabaya" data analysis',
    '"Surabaya" smart city dataset',
    '"Surabaya" open data government',
    '"Surabaya" traffic data',
    '"Surabaya" health data stunting',
    '"Surabaya" poverty data MBR',
    '"Surabaya" public service data',
    'implementasi data "Kota Surabaya"'
]

def deteksi_sumber_data(judul, abstrak):
    teks = (str(judul) + " " + str(abstrak)).lower()
    if any(x in teks for x in ['dishub', 'lalu lintas', 'traffic', 'bus', 'suroboyo bus', 'sits']):
        return "Dinas Perhubungan (Data Transportasi)"
    elif any(x in teks for x in ['dinkes', 'kesehatan', 'stunting', 'puskesmas', 'e-health', 'medis']):
        return "Dinas Kesehatan (Data Kesehatan)"
    elif any(x in teks for x in ['dinsos', 'sosial', 'mbr', 'kemiskinan', 'bantuan']):
        return "Dinas Sosial (Data Kesejahteraan Rakyat)"
    elif any(x in teks for x in ['dispendukcapil', 'kependudukan', 'adminduk', 'capil']):
        return "Dispendukcapil (Data Kependudukan)"
    elif any(x in teks for x in ['diskominfo', 'wargaku', 'keluhan', 'e-gov']):
        return "Diskominfo (Data Layanan Publik/WargaKu)"
    return "Dataset Sektoral (Pemerintah Kota Surabaya)"

def analisis_output_nyata(judul, abstrak):
    teks = (str(judul) + " " + str(abstrak)).lower()
    if any(x in teks for x in ['predict', 'prediksi', 'forecasting']):
        return "Model Prediksi: Estimasi angka masa depan untuk perencanaan kebijakan dinas."
    elif any(x in teks for x in ['map', 'gis', 'spasial', 'peta', 'zonasi']):
        return "Pemetaan Digital (GIS): Penentuan wilayah prioritas layanan/bantuan agar tepat sasaran."
    elif any(x in teks for x in ['dashboard', 'monitoring', 'visualisasi']):
        return "Sistem Monitoring: Dashboard pantauan real-time untuk transparansi kinerja dinas."
    elif any(x in teks for x in ['sentimen', 'sentiment', 'klasifikasi', 'wargaku']):
        return "Analisis Kepuasan: Evaluasi keluhan warga menjadi rekomendasi perbaikan layanan."
    return "Rekomendasi Strategis: Dasar ilmiah pengambilan keputusan berbasis data (Evidence-based Policy)."

def deep_scholar_crawl():
    BASE_URL = 'https://api.semanticscholar.org/graph/v1/paper/search'
    results = []

    print(f"🚀 Memulai Pencarian Spesifik Surabaya ({TAHUN_MULAI}-2026)...")

    for q in tqdm(SEMANTIC_QUERIES, desc='Kategori'):
        offset = 0
        while offset < LIMIT_PER_QUERY:
            params = {
                'query': q,
                'limit': 50,
                'offset': offset,
                'fields': 'title,year,abstract,url,authors,venue',
                'year': f'{TAHUN_MULAI}-'
            }
            try:
                time.sleep(random.uniform(2, 4))
                r = requests.get(BASE_URL, params=params, timeout=25)

                if r.status_code == 200:
                    data = r.json().get('data', [])
                    if not data: break

                    for p in data:
                        judul = p.get('title', '')
                        abstrak = p.get('abstract', '') or ""

                        # --- FILTER KETAT (STRICT FILTER) ---
                        # Hanya ambil jika kata 'Surabaya' ada di JUDUL
                        if 'surabaya' not in judul.lower():
                            continue

                        results.append({
                            'Judul Analisis/Skripsi': judul,
                            'Data yang Digunakan': deteksi_sumber_data(judul, abstrak),
                            'Output Nyata Pemanfaatan': analisis_output_nyata(judul, abstrak),
                            'Tahun': p.get('year'),
                            'Penulis': p.get('authors')[0].get('name') if p.get('authors') else "N/A",
                            'Sumber/Jurnal': p.get('venue', 'N/A'),
                            'Link': p.get('url', '')
                        })
                    offset += 50
                else:
                    break
            except Exception as e:
                break

    df = pd.DataFrame(results)
    if not df.empty:
        # Hapus duplikat berdasarkan judul
        df = df.drop_duplicates(subset=['Judul Analisis/Skripsi'])
        # Sortir berdasarkan tahun terbaru
        df = df.sort_values(by='Tahun', ascending=False)
    return df

# Eksekusi
df_final = deep_scholar_crawl()

if not df_final.empty:
    df_final.to_excel(OUTPUT_FILE, index=False)
    print(f"\n✅ Berhasil mendapatkan {len(df_final)} data VALID Surabaya.")
    files.download(OUTPUT_FILE)
    display(df_final[['Judul Analisis/Skripsi', 'Data yang Digunakan', 'Output Nyata Pemanfaatan']].head(10))
else:
    print("❌ Tidak ada data yang sesuai filter. Coba perluas keyword.")

🚀 Memulai Pencarian Spesifik Surabaya (2021-2026)...

Kategori:   0%|          | 0/8 [00:00<?, ?it/s]

❌ Tidak ada data yang sesuai filter. Coba perluas keyword.

In [ ]:
!pip install selenium

Collecting selenium
  Downloading selenium-4.41.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: certifi>=2026.1.4 in /usr/local/lib/python3.12/dist-packages (from selenium) (2026.2.25)
Collecting trio<1.0,>=0.31.0 (from selenium)
  Downloading trio-0.33.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (4.15.0)
Collecting urllib3<3.0,>=2.6.3 (from urllib3[socks]<3.0,>=2.6.3->selenium)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (1.9.0)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (25.4.0)
Collecting sortedcontainers (from trio<1.0,>=0.31.0->selenium)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (3.11)
Collecting outcome (from trio<1.0,>=0.31.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Downloading selenium-4.41.0-py3-none-any.whl (9.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 60.5 MB/s eta 0:00:00
Downloading trio-0.33.0-py3-none-any.whl (510 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.3/510.3 kB 25.3 MB/s eta 0:00:00
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.6/131.6 kB 10.0 MB/s eta 0:00:00
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Installing collected packages: sortedcontainers, wsproto, urllib3, outcome, trio, trio-websocket, selenium
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.5.0
    Uninstalling urllib3-2.5.0:
      Successfully uninstalled urllib3-2.5.0
Successfully installed outcome-1.3.0.post0 selenium-4.41.0 sortedcontainers-2.4.0 trio-0.33.0 trio-websocket-0.12.2 urllib3-2.6.3 wsproto-1.3.2

In [ ]:
# Install library untuk menembus proteksi browser dan mengelola driver
!pip install selenium webdriver-manager beautifulsoup4 pandas openpyxl tqdm

Requirement already satisfied: selenium in /usr/local/lib/python3.12/dist-packages (4.41.0)
Collecting webdriver-manager
  Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: certifi>=2026.1.4 in /usr/local/lib/python3.12/dist-packages (from selenium) (2026.2.25)
Requirement already satisfied: trio<1.0,>=0.31.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (0.33.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in /usr/local/lib/python3.12/dist-packages (from selenium) (0.12.2)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (4.15.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (2.6.3)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (1.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from webdriver-manager) (2.32.4)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (from webdriver-manager) (1.2.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from webdriver-manager) (26.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (25.4.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (3.11)
Requirement already satisfied: outcome in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.12/dist-packages (from trio-websocket<1.0,>=0.12.2->selenium) (1.3.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->webdriver-manager) (3.4.4)
Requirement already satisfied: h11<1,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl (27 kB)
Installing collected packages: webdriver-manager
Successfully installed webdriver-manager-4.0.2

In [ ]:
!pip install pandas requests tqdm openpyxl

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import requests
import pandas as pd
import time
from tqdm import tqdm

def fetch_surabaya_massive_impact(queries):
    base_url = "https://api.semanticscholar.org/graph/v1/paper/search"
    all_results = []

    print(f"🚀 Memulai Pengambilan Data Pemanfaatan Data Surabaya (2021-2026)...")

    for q in tqdm(queries, desc="Kategori Keyword"):
        offset = 0
        # Kita ambil hingga 200 paper per kategori keyword untuk mencapai ribuan total
        while offset < 200:
            params = {
                "query": q,
                "limit": 100,
                "offset": offset,
                "fields": "title,authors,year,abstract,url,venue,citationCount",
                "year": "2021-"
            }

            try:
                response = requests.get(base_url, params=params, timeout=30)
                if response.status_code == 200:
                    data = response.json().get('data', [])
                    if not data: break

                    for paper in data:
                        judul = paper.get('title', '')
                        # Filter Ketat: Harus ada kata 'Surabaya'
                        if 'surabaya' not in judul.lower():
                            continue

                        abstrak = paper.get('abstract') or ""

                        # Ekstraksi Penulis Lengkap
                        authors_list = [a['name'] for a in paper.get('authors', [])]
                        penulis = ", ".join(authors_list) if authors_list else "Penulis tidak terdata"

                        # ANALISIS DAMPAK NYATA (Berdasarkan Konteks Surabaya)
                        full_text = (judul + " " + abstrak).lower()
                        dampak = "Kajian Strategis & Kebijakan"

                        if any(x in full_text for x in ['stunting', 'sayang warga', 'kesehatan', 'puskesmas']):
                            dampak = "Dampak Sosial: Penurunan angka stunting & efisiensi layanan kesehatan warga."
                        elif any(x in full_text for x in ['macet', 'sits', 'bus', 'dishub', 'lalu lintas']):
                            dampak = "Dampak Infrastruktur: Optimasi durasi perjalanan & manajemen transportasi publik."
                        elif any(x in full_text for x in ['umkm', 'epeken', 'e-peken', 'ekonomi', 'toko kelontong']):
                            dampak = "Dampak Ekonomi: Digitalisasi pasar & peningkatan omzet pelaku usaha lokal."
                        elif any(x in full_text for x in ['wargaku', 'keluhan', 'sentimen', 'pelayanan']):
                            dampak = "Dampak Layanan Publik: Peningkatan respon cepat pemerintah terhadap keluhan warga."
                        elif any(x in full_text for x in ['mbr', 'miskin', 'bansos', 'bantuan']):
                            dampak = "Dampak Kesejahteraan: Akurasi penyaluran bantuan sosial tepat sasaran."

                        all_results.append({
                            "Judul Analisis/Skripsi": judul,
                            "Penulis": penulis,
                            "Tahun": paper.get('year'),
                            "Sektor Data": q.split('"')[1] if '"' in q else "Umum",
                            "Dampak Pemanfaatan Data": dampak,
                            "Sumber/Jurnal": paper.get('venue') or "Repositori Akademik",
                            "Link Dokumen": paper.get('url'),
                            "Abstrak": abstrak[:500] + "..." if abstrak else "Detail tersedia di link"
                        })

                    offset += 100
                    time.sleep(1.5) # Jeda agar tidak kena limit API
                else:
                    print(f"\n⚠️ Limit API tercapai atau error {response.status_code}. Melanjutkan...")
                    break
            except Exception as e:
                print(f"Error: {e}")
                break

    return pd.DataFrame(all_results)

# --- KEYWORD HARCORE UNTUK TEMBUS RIBUAN DATA ---
queries_surabaya = [
    'implementation "Smart City" Surabaya',
    'analysis "SITS Surabaya" traffic data',
    'evaluation "Wargaku" Surabaya services',
    'impact "E-Peken" Surabaya MSMEs',
    '"Dinas Kesehatan Surabaya" data analysis',
    '"Sayang Warga" Surabaya stunting data',
    'poverty "MBR Surabaya" data intervention',
    '"Satu Data Surabaya" implementation impact',
    '"Dispendukcapil Surabaya" digital transformation',
    'efficiency "Suroboyo Bus" route data'
]

# Eksekusi
df_final = fetch_surabaya_massive_impact(queries_surabaya)

# Pembersihan & Sorting
if not df_final.empty:
    df_final = df_final.drop_duplicates(subset=['Judul Analisis/Skripsi'])
    df_final = df_final.sort_values(by='Tahun', ascending=False)

    # Simpan ke Excel
    file_name = "Master_Analisis_Data_Surabaya_Final.xlsx"
    df_final.to_excel(file_name, index=False)

    print(f"\n✅ SUKSES! Berhasil mengumpulkan {len(df_final)} data penggunaan riil.")
    print(f"📂 Silakan download file '{file_name}' di menu folder sebelah kiri.")
else:
    print("❌ Tidak ada data yang ditemukan. Coba perluas keyword.")

🚀 Memulai Pengambilan Data Pemanfaatan Data Surabaya (2021-2026)...

Kategori Keyword:  10%|█         | 1/10 [00:00<00:01,  6.87it/s]

⚠️ Limit API tercapai atau error 429. Melanjutkan...

Kategori Keyword:  20%|██        | 2/10 [00:00<00:01,  7.80it/s]

⚠️ Limit API tercapai atau error 429. Melanjutkan...

Kategori Keyword:  30%|███       | 3/10 [00:00<00:00,  8.25it/s]

⚠️ Limit API tercapai atau error 429. Melanjutkan...

Kategori Keyword:  40%|████      | 4/10 [00:00<00:00,  8.57it/s]

⚠️ Limit API tercapai atau error 429. Melanjutkan...

Kategori Keyword:  50%|█████     | 5/10 [00:00<00:00,  8.64it/s]

⚠️ Limit API tercapai atau error 429. Melanjutkan...

Kategori Keyword:  60%|██████    | 6/10 [00:00<00:00,  8.69it/s]

⚠️ Limit API tercapai atau error 429. Melanjutkan...

Kategori Keyword:  70%|███████   | 7/10 [00:00<00:00,  8.75it/s]

⚠️ Limit API tercapai atau error 429. Melanjutkan...

Kategori Keyword:  80%|████████  | 8/10 [00:00<00:00,  8.66it/s]

⚠️ Limit API tercapai atau error 429. Melanjutkan...

Kategori Keyword:  90%|█████████ | 9/10 [00:01<00:00,  8.54it/s]

⚠️ Limit API tercapai atau error 429. Melanjutkan...

Kategori Keyword: 100%|██████████| 10/10 [00:01<00:00,  8.48it/s]

⚠️ Limit API tercapai atau error 429. Melanjutkan...
❌ Tidak ada data yang ditemukan. Coba perluas keyword.

In [ ]:
import requests
import pandas as pd
import time
from tqdm import tqdm

def fetch_surabaya_mega_data(queries, target_per_query=500):
    base_url = "https://api.semanticscholar.org/graph/v1/paper/search"
    all_results = []

    print(f"🚀 Memulai Mega-Crawling Data Surabaya (Target: Ribuan Data)...")

    for q in tqdm(queries, desc="Kategori"):
        offset = 0
        while offset < target_per_query:
            params = {
                "query": q,
                "limit": 100, # Maksimal per tarikan
                "offset": offset,
                "fields": "title,authors,year,abstract,url,venue,publicationVenue,externalIds",
                "year": "2020-" # Diperluas sedikit ke 2020 agar data lebih masif
            }

            try:
                # Tambahkan jeda agar tidak terkena Rate Limit API
                time.sleep(1.2)
                response = requests.get(base_url, params=params, timeout=30)

                if response.status_code == 200:
                    data = response.json().get('data', [])
                    if not data: break # Berhenti jika data sudah habis

                    for paper in data:
                        judul = paper.get('title', '')
                        # Filter Validasi Surabaya
                        abstract = paper.get('abstract') or ""
                        text_match = (judul + " " + abstract).lower()

                        if 'surabaya' in text_match:
                            authors = ", ".join([a['name'] for a in paper.get('authors', [])])

                            # ANALISIS DAMPAK MENDALAM (LOGIKA NON-TEMPLATE)
                            dampak = "Kajian Teknis/Akademis"
                            if any(x in text_match for x in ['stunting', 'sehat', 'puskesmas', 'sayang warga']):
                                dampak = "Dampak Kesehatan: Intervensi gizi kronis & pemetaan balita berisiko."
                            elif any(x in text_match for x in ['macet', 'sits', 'dishub', 'lalu lintas', 'bus']):
                                dampak = "Dampak Transportasi: Efisiensi waktu tempuh & integrasi rute angkutan umum."
                            elif any(x in text_match for x in ['epeken', 'umkm', 'ekonomi', 'pedagang']):
                                dampak = "Dampak Ekonomi: Transformasi digital UMKM & stabilisasi harga pasar."
                            elif any(x in text_match for x in ['banjir', 'genangan', 'drainase', 'pompa']):
                                dampak = "Dampak Lingkungan: Mitigasi titik banjir & optimalisasi rumah pompa."
                            elif any(x in text_match for x in ['mbr', 'miskin', 'bansos', 'sosial']):
                                dampak = "Dampak Sosial: Akurasi penyaluran bantuan bagi keluarga prasejahtera."

                            all_results.append({
                                "Judul Analisis/Skripsi": judul,
                                "Penulis": authors,
                                "Tahun": paper.get('year'),
                                "Dataset/Sektor": q,
                                "Dampak Nyata Pemanfaatan": dampak,
                                "Sumber/Jurnal/Kampus": paper.get('venue') or "Repositori Lokal Surabaya",
                                "Link Dokumen": paper.get('url'),
                                "Cuplikan Analisis": abstract[:400] + "..." if abstract else "N/A"
                            })

                    offset += 100 # Loncat ke 100 data berikutnya
                elif response.status_code == 429:
                    print("\n🛑 Terkena limit! Istirahat 30 detik...")
                    time.sleep(30)
                else:
                    break
            except Exception as e:
                print(f"Error: {e}")
                break

    return pd.DataFrame(all_results)

# --- KEYWORD EKSTRIM UNTUK HASIL MAKSIMAL ---
# Saya tambahkan nama-nama dinas dan sistem spesifik Surabaya
mega_queries = [
    'Surabaya "Smart City" implementation',
    'Analysis "SITS" Surabaya traffic',
    'Dataset "Open Data Surabaya"',
    'Efektivitas "Wargaku" Surabaya',
    'Pemanfaatan "E-Peken" Surabaya',
    'Stunting "Sayang Warga" Surabaya',
    'Data "Klampid" Surabaya kependudukan',
    'Evaluasi "Suroboyo Bus" rute',
    'Implementasi "SSW" Surabaya perizinan',
    'Data "MBR" Surabaya kemiskinan',
    'Analisis "Dinas Kesehatan" Surabaya',
    'Pemanfaatan data "Dishub" Surabaya',
    'Aplikasi "e-Health" Surabaya',
    'Sistem Informasi "Pemkot Surabaya" data'
]

# Jalankan (Target 500 per query x 14 query = Potensi 7.000 data sebelum difilter)
df_mega = fetch_surabaya_mega_data(mega_queries, target_per_query=500)

# Cleaning Final
if not df_mega.empty:
    df_mega = df_mega.drop_duplicates(subset=['Judul Analisis/Skripsi'])
    df_mega = df_mega.sort_values(by=['Tahun', 'Judul Analisis/Skripsi'], ascending=[False, True])

    # Save to Excel
    filename = "MEGA_DATA_SURABAYA_2021_2026.xlsx"
    df_mega.to_excel(filename, index=False)
    print(f"\n✅ BERHASIL! Mendapatkan {len(df_mega)} baris data unik pemanfaatan data Surabaya.")
else:
    print("❌ Data tidak ditemukan.")

🚀 Memulai Mega-Crawling Data Surabaya (Target: Ribuan Data)...

Kategori:   0%|          | 0/14 [00:00<?, ?it/s]

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

Kategori:   7%|▋         | 1/14 [09:05<1:58:12, 545.55s/it]

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

Kategori:  14%|█▍        | 2/14 [18:08<1:48:47, 543.97s/it]

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

Kategori:  21%|██▏       | 3/14 [42:58<2:58:55, 975.98s/it]

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

Kategori:  29%|██▊       | 4/14 [56:14<2:30:51, 905.13s/it]

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

Kategori:  36%|███▌      | 5/14 [1:01:05<1:42:32, 683.57s/it]

🛑 Terkena limit! Istirahat 30 detik...

Kategori:  43%|████▎     | 6/14 [1:01:41<1:01:46, 463.28s/it]

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

Kategori:  50%|█████     | 7/14 [1:04:59<43:55, 376.46s/it]

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

Kategori:  57%|█████▋    | 8/14 [1:14:57<44:42, 447.06s/it]

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

Kategori:  64%|██████▍   | 9/14 [1:22:20<37:08, 445.75s/it]

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

Kategori:  71%|███████▏  | 10/14 [1:25:02<23:53, 358.39s/it]

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

🛑 Terkena limit! Istirahat 30 detik...

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import random
import re
from google.colab import files
from tqdm import tqdm

def parse_metadata(raw_text):
    """Membedah teks mentah ITS menjadi kolom tabel sesuai permintaan"""
    try:
        # Ekstrak Tahun
        tahun = re.search(r'\((\d{4})\)', raw_text)
        tahun = tahun.group(1) if tahun else "2021-2026"

        # Ekstrak Penulis (Biasanya sebelum kurung tahun)
        penulis = raw_text.split('(')[0].strip() if '(' in raw_text else "N/A"

        # Ekstrak Judul (Setelah tahun)
        judul = raw_text.split(')')[1].strip().split('.')[0] if ')' in raw_text else raw_text

        low_text = raw_text.lower()
        # Mapping Sektoral Surabaya
        if any(x in low_text for x in ['bus', 'suroboyo', 'dishub', 'lalu lintas', 'sits', 'jalan']):
            instansi, data, output, deskripsi = ("Dinas Perhubungan (Dishub)", "Data CCTV SITS & GPS Bus", "Optimasi Transportasi", "Manajemen rute dan lampu lalin.")
        elif any(x in low_text for x in ['banjir', 'hujan', 'pompa', 'drainase', 'sungai']):
            instansi, data, output, deskripsi = ("Dinas Sumber Daya Air (DSDABM)", "Data Curah Hujan & Elevasi", "Mitigasi Banjir", "Aktivasi pompa air otomatis.")
        elif any(x in low_text for x in ['gis', 'spasial', 'peta', 'lahan']):
            instansi, data, output, deskripsi = ("DPRKPP (Tata Ruang)", "Data Spasial & Peta SHP", "Zonasi Wilayah", "Pemetaan penggunaan lahan kota.")
        elif any(x in low_text for x in ['sampah', 'dlh', 'limbah']):
            instansi, data, output, deskripsi = ("Dinas Lingkungan Hidup (DLH)", "Data Volume Sampah", "Manajemen Limbah", "Optimasi rute truk pengangkut.")
        else:
            instansi, data, output, deskripsi = ("Pemkot Surabaya", "Dataset Sektoral", "Kajian Strategis", "Analisis data layanan publik.")

        return penulis, tahun, judul, instansi, data, output, deskripsi
    except:
        return "N/A", "2021-2026", "N/A", "Pemkot", "Data", "Output", "Deskripsi"

def crawl_its_fixed():
    # Gunakan pencarian sederhana agar tidak diblokir
    search_queries = ['Surabaya+Dishub', 'Surabaya+Banjir', 'Surabaya+SITS', 'Surabaya+Smart+City', 'Surabaya+GIS']
    final_list = []

    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'}

    print("🔎 Menghubungkan ke Repository ITS...")

    for q in tqdm(search_queries):
        # Gunakan URL pencarian simpel
        url = f"https://repository.its.ac.id/cgi/search/archive/simple?q={q}"

        try:
            res = requests.get(url, headers=headers, timeout=20)
            if res.status_code != 200: continue

            soup = BeautifulSoup(res.text, 'html.parser')
            # Cari baris data (ITS pakai class ep_eprint_line)
            items = soup.find_all('tr', class_='ep_eprint_line')

            for item in items:
                link_tag = item.find('a')
                if not link_tag: continue

                raw_text = item.get_text(separator=" ").strip()
                link = link_tag['href']

                penulis, tahun, judul, instansi, data_used, output, deskripsi = parse_metadata(raw_text)

                final_list.append({
                    'Judul Penelitian': judul,
                    'Penulis': penulis,
                    'Tahun Terbit': tahun,
                    'Instansi Terkait': instansi,
                    'Data Yang Digunakan': data_used,
                    'Output Pemanfaatan': output,
                    'Deskripsi Pemanfaatan Spesifik': deskripsi,
                    'Sumber Publikasi': 'Repository ITS',
                    'Link': link,
                    'Keyword Sumber': q.replace('+', ' ')
                })

            # Jeda lebih lama agar tidak dianggap spam
            time.sleep(random.uniform(5, 8))

        except Exception as e:
            print(f"Error pada {q}: {e}")
            continue

    df = pd.DataFrame(final_list)
    return df

# Eksekusi
df_its = crawl_its_fixed()

if not df_its.empty:
    df_its = df_its.drop_duplicates(subset=['Judul Penelitian'])
    df_its.to_excel("DATA_ITS_FIX.xlsx", index=False)
    files.download("DATA_ITS_FIX.xlsx")
    print(f"✅ BERHASIL! Ditemukan {len(df_its)} data.")
    display(df_its.head())
else:
    print("❌ Masih kosong. Server ITS sedang membatasi akses. Coba lagi dalam 5 menit atau ganti koneksi.")

🔎 Menghubungkan ke Repository ITS...

100%|██████████| 5/5 [00:04<00:00,  1.16it/s]

❌ Masih kosong. Server ITS sedang membatasi akses. Coba lagi dalam 5 menit atau ganti koneksi.

# **REPOSITORY UNAIR**

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import random
import re
from google.colab import files
from tqdm.notebook import tqdm

def parser_unair(raw_text):
    """Membedah metadata UNAIR menjadi kolom tabel yang diminta"""
    try:
        # Ekstrak Tahun (4 digit dalam kurung)
        tahun_search = re.search(r'\((\d{4})\)', raw_text)
        tahun = tahun_search.group(1) if tahun_search else "2021-2026"

        # Ekstrak Penulis (Sebelum kurung tahun)
        penulis = raw_text.split('(')[0].strip() if '(' in raw_text else "N/A"

        # Ekstrak Judul (Setelah kurung tahun)
        judul = raw_text.split(')')[1].strip().split('.')[0] if ')' in raw_text else raw_text

        low_text = raw_text.lower()
        # Logic Mapping Sektoral UNAIR (Kesehatan & Sosial)
        if any(x in low_text for x in ['stunting', 'gizi', 'balita', 'anak', 'ibu']):
            instansi, data, output, deskripsi = ("Dinas Kesehatan (Dinkes) Surabaya", "Data Sayang Warga & E-Health", "Intervensi Gizi Terpadu", "Pemetaan balita berisiko stunting untuk penyaluran bantuan protein.")
        elif any(x in low_text for x in ['miskin', 'mbr', 'sosial', 'bantuan', 'gamis']):
            instansi, data, output, deskripsi = ("Dinas Sosial (Dinsos) Surabaya", "Data MBR & Aplikasi Wargaku", "Akurasi Bansos", "Sinkronisasi data warga miskin agar bantuan sosial tepat sasaran.")
        elif any(x in low_text for x in ['rumah sakit', 'puskesmas', 'antrian', 'obat']):
            instansi, data, output, deskripsi = ("Dinas Kesehatan / RSUD Soewandhie", "Data Kunjungan Pasien", "Efisiensi Layanan Medis", "Analisis waktu tunggu pasien untuk optimasi jumlah tenaga medis.")
        elif any(x in low_text for x in ['umkm', 'peken', 'ekonomi', 'toko']):
            instansi, data, output, deskripsi = ("Dinkopumdag Surabaya", "Data Transaksi E-Peken", "Pemberdayaan UMKM", "Analisis omzet UMKM untuk strategi pemasaran produk lokal.")
        else:
            instansi, data, output, deskripsi = ("Pemkot Surabaya", "Dataset Sektoral", "Kajian Kebijakan", "Analisis data untuk peningkatan indeks pembangunan manusia.")

        return penulis, tahun, judul, instansi, data, output, deskripsi
    except:
        return "N/A", "2021-2026", "N/A", "Pemkot Surabaya", "Data", "Output", "Deskripsi"

def crawl_unair_massive():
    # Keyword spesifik Surabaya untuk UNAIR
    search_queries = [
        'Surabaya+Stunting', 'Surabaya+MBR', 'Surabaya+E-Health',
        'Surabaya+Kemiskinan', 'Surabaya+UMKM', 'Surabaya+Pelayanan+Publik'
    ]

    final_list = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    print("🚀 Memulai Crawling Repository UNAIR (Kesehatan & Sosial)...")

    for q in tqdm(search_queries, desc="Keyword"):
        url = f"https://repository.unair.ac.id/cgi/search/archive/simple?q={q}"

        try:
            res = requests.get(url, headers=headers, timeout=25)
            if res.status_code != 200: continue

            soup = BeautifulSoup(res.text, 'html.parser')
            # Selector UNAIR mirip ITS (EPrints)
            items = soup.find_all('tr', class_='ep_eprint_line')

            if not items:
                print(f"⚠️ Keyword '{q}' tidak memberikan hasil.")
                continue

            for item in items:
                link_tag = item.find('a')
                if not link_tag: continue

                raw_text = item.get_text(separator=" ").strip()
                link = link_tag['href']

                penulis, tahun, judul, instansi, data_used, output, deskripsi = parser_unair(raw_text)

                final_list.append({
                    'Judul Penelitian': judul,
                    'Penulis': penulis,
                    'Tahun Terbit': tahun,
                    'Instansi Terkait': instansi,
                    'Data Yang Digunakan': data_used,
                    'Output Pemanfaatan': output,
                    'Deskripsi Pemanfaatan Spesifik': deskripsi,
                    'Sumber Publikasi': 'Repository UNAIR',
                    'Link': link,
                    'Keyword Sumber': q.replace('+', ' ')
                })

            # Jeda agar aman
            time.sleep(random.uniform(4, 7))

        except Exception as e:
            print(f"⚠️ Error pada {q}: {e}")
            continue

    df = pd.DataFrame(final_list)
    return df

# --- EKSEKUSI ---
df_unair = crawl_unair_massive()

if not df_unair.empty:
    df_unair = df_unair.drop_duplicates(subset=['Judul Penelitian'])
    # Filter Tahun agar sesuai target 2021-2026
    df_unair = df_unair[df_unair['Tahun Terbit'].astype(str).str.contains('2021|2022|2023|2024|2025|2026')]

    output_name = "DATA_PEMANFAATAN_UNAIR_FIX.xlsx"
    df_unair.to_excel(output_name, index=False)
    files.download(output_name)
    print(f"\n✅ BERHASIL! Ditemukan {len(df_unair)} data riset pemanfaatan data Surabaya.")
    display(df_unair.head(10))
else:
    print("❌ Masih kosong. Coba gunakan VPN atau hotspot HP (ganti IP).")

🚀 Memulai Crawling Repository UNAIR (Kesehatan & Sosial)...

Keyword:   0%|          | 0/6 [00:00<?, ?it/s]

⚠️ Error pada Surabaya+Stunting: HTTPSConnectionPool(host='repository.unair.ac.id', port=443): Max retries exceeded with url: /cgi/search/archive/simple?q=Surabaya+Stunting (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7b7079357ad0>, 'Connection to repository.unair.ac.id timed out. (connect timeout=25)'))
⚠️ Error pada Surabaya+MBR: HTTPSConnectionPool(host='repository.unair.ac.id', port=443): Max retries exceeded with url: /cgi/search/archive/simple?q=Surabaya+MBR (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7b70792bc710>, 'Connection to repository.unair.ac.id timed out. (connect timeout=25)'))
⚠️ Error pada Surabaya+E-Health: HTTPSConnectionPool(host='repository.unair.ac.id', port=443): Max retries exceeded with url: /cgi/search/archive/simple?q=Surabaya+E-Health (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7b70792bd0d0>, 'Connection to repository.unair.ac.id timed out. (connect timeout=25)'))
⚠️ Error pada Surabaya+Kemiskinan: HTTPSConnectionPool(host='repository.unair.ac.id', port=443): Max retries exceeded with url: /cgi/search/archive/simple?q=Surabaya+Kemiskinan (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7b70792bd9d0>, 'Connection to repository.unair.ac.id timed out. (connect timeout=25)'))
⚠️ Error pada Surabaya+UMKM: HTTPSConnectionPool(host='repository.unair.ac.id', port=443): Max retries exceeded with url: /cgi/search/archive/simple?q=Surabaya+UMKM (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7b70792be570>, 'Connection to repository.unair.ac.id timed out. (connect timeout=25)'))
⚠️ Error pada Surabaya+Pelayanan+Publik: HTTPSConnectionPool(host='repository.unair.ac.id', port=443): Max retries exceeded with url: /cgi/search/archive/simple?q=Surabaya+Pelayanan+Publik (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7b7079357da0>, 'Connection to repository.unair.ac.id timed out. (connect timeout=25)'))
❌ Masih kosong. Coba gunakan VPN atau hotspot HP (ganti IP).

Pake portal Garuda

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import random
import re
from google.colab import files
from tqdm.notebook import tqdm

def parser_garuda_pro(judul, abstrak):
    teks = (str(judul) + " " + str(abstrak)).lower()
    # Mapping Sektoral & Dampak Spesifik (Sesuai Permintaanmu)
    if any(x in teks for x in ['stunting', 'gizi', 'balita', 'sehat']):
        return "Dinas Kesehatan Surabaya", "Data E-Health & Sayang Warga", "Intervensi Gizi", "Pemetaan balita stunting untuk bantuan protein."
    elif any(x in teks for x in ['macet', 'sits', 'dishub', 'bus', 'lalin']):
        return "Dinas Perhubungan Surabaya", "Data CCTV SITS & GPS Bus", "Efisiensi Transportasi", "Optimasi lampu lalin dan rute Suroboyo Bus."
    elif any(x in teks for x in ['banjir', 'pompa', 'hujan', 'drainase']):
        return "DSDABM Surabaya", "Data Curah Hujan & Elevasi Air", "Mitigasi Banjir", "Manajemen rumah pompa berbasis debit air riil."
    elif any(x in teks for x in ['mbr', 'miskin', 'sosial', 'wargaku']):
        return "Dinas Sosial Surabaya", "Data MBR & Aplikasi Wargaku", "Akurasi Bantuan", "Validasi warga miskin agar bansos tepat sasaran."
    return "Pemkot Surabaya", "Dataset Sektoral", "Kajian Strategis", "Analisis data untuk efisiensi pelayanan publik."

def mega_crawl_garuda_fixed():
    # Gunakan keyword yang lebih luas tapi tetap Surabaya
    keywords = ['"Kota Surabaya" data', '"Pemerintah Surabaya" sistem', '"Surabaya" analisis']
    results = []

    # Rahasia 1: Gunakan Session agar koneksi lebih stabil
    session = requests.Session()
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8'
    }

    print("🚀 Menembus Protokol Garuda (Mode Slow & Safe)...")

    for k in tqdm(keywords, desc="Keyword"):
        # Ambil lebih banyak halaman (Misal 1-10) untuk dapat ribuan data
        for page in range(1, 11):
            url = f"https://garuda.kemdikbud.go.id/documents?q={k}&page={page}"

            try:
                # Rahasia 2: Jeda acak 4-7 detik (Sangat penting agar tidak diblokir)
                time.sleep(random.uniform(4, 7))

                response = session.get(url, headers=headers, timeout=30)
                if response.status_code != 200:
                    print(f"⚠️ Server merespon {response.status_code}. Istirahat sebentar...")
                    time.sleep(10)
                    continue

                soup = BeautifulSoup(response.text, 'html.parser')
                docs = soup.select('.article-item')

                if not docs:
                    print(f"Selesai di halaman {page}")
                    break

                for doc in docs:
                    title_el = doc.select_one('.title-article')
                    if not title_el: continue

                    title = title_el.text.strip()
                    # Filter: Pastikan ada konteks Surabaya
                    if 'surabaya' not in title.lower(): continue

                    author = doc.select_one('.author-article').text.strip() if doc.select_one('.author-article') else "N/A"
                    pub = doc.select_one('.publisher-article').text.strip() if doc.select_one('.publisher-article') else "N/A"
                    link = "https://garuda.kemdikbud.go.id" + title_el.find('a')['href']

                    # Ekstrak Tahun
                    tahun_match = re.search(r'20\d{2}', pub)
                    tahun = tahun_match.group(0) if tahun_match else "2021-2026"

                    # Analisis Sektoral
                    instansi, data_used, output, deskripsi = parser_garuda_pro(title, "")

                    results.append({
                        'Judul Penelitian': title,
                        'Penulis': author,
                        'Tahun Terbit': tahun,
                        'Instansi Terkait': instansi,
                        'Data Yang Digunakan': data_used,
                        'Output Pemanfaatan': output,
                        'Deskripsi Pemanfaatan Spesifik': deskripsi,
                        'Sumber Publikasi': pub,
                        'Link': link,
                        'Keyword Sumber': k
                    })

            except Exception as e:
                print(f"❌ Error: {e}")
                continue

    df = pd.DataFrame(results)
    return df

# --- RUN ---
df_final = mega_crawl_garuda_fixed()

if not df_final.empty:
    df_final = df_final.drop_duplicates(subset=['Judul Penelitian'])
    # Simpan
    nama_file = "LAPORAN_PEMANFAATAN_DATA_SURABAYA_JOSS.xlsx"
    df_final.to_excel(nama_file, index=False)
    files.download(nama_file)
    print(f"✅ SUKSES! Ditemukan {len(df_final)} data riil.")
    display(df_final.head())
else:
    print("❌ Masih gagal. Coba ganti koneksi Internet (Hotspot HP) karena IP Colab mungkin sudah di-blacklist permanen oleh Garuda.")

🚀 Menembus Protokol Garuda (Mode Slow & Safe)...

Keyword:   0%|          | 0/3 [00:00<?, ?it/s]

❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Kota%20Surabaya%22%20data&page=1 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792bdd60>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Kota%20Surabaya%22%20data&page=2 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792be210>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Kota%20Surabaya%22%20data&page=3 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792bd280>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Kota%20Surabaya%22%20data&page=4 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792bc1a0>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Kota%20Surabaya%22%20data&page=5 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792d98b0>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Kota%20Surabaya%22%20data&page=6 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792bdca0>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Kota%20Surabaya%22%20data&page=7 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792bcdd0>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Kota%20Surabaya%22%20data&page=8 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792be180>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Kota%20Surabaya%22%20data&page=9 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792bd160>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Kota%20Surabaya%22%20data&page=10 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792d99a0>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Pemerintah%20Surabaya%22%20sistem&page=1 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792da030>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Pemerintah%20Surabaya%22%20sistem&page=2 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792d9d00>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Pemerintah%20Surabaya%22%20sistem&page=3 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b7079061400>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Pemerintah%20Surabaya%22%20sistem&page=4 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b7079061f10>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Pemerintah%20Surabaya%22%20sistem&page=5 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b7079060b30>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Pemerintah%20Surabaya%22%20sistem&page=6 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70790610d0>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Pemerintah%20Surabaya%22%20sistem&page=7 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b7079061c70>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Pemerintah%20Surabaya%22%20sistem&page=8 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b7079061ac0>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Pemerintah%20Surabaya%22%20sistem&page=9 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b7079061730>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Pemerintah%20Surabaya%22%20sistem&page=10 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792daa80>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Surabaya%22%20analisis&page=1 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792da090>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Surabaya%22%20analisis&page=2 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792da300>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Surabaya%22%20analisis&page=3 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792beb40>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Surabaya%22%20analisis&page=4 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792bc650>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Surabaya%22%20analisis&page=5 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792bdb50>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Surabaya%22%20analisis&page=6 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b7079061070>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Surabaya%22%20analisis&page=7 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70790621b0>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Surabaya%22%20analisis&page=8 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70790610d0>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Surabaya%22%20analisis&page=9 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70790600e0>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Error: HTTPSConnectionPool(host='garuda.kemdikbud.go.id', port=443): Max retries exceeded with url: /documents?q=%22Surabaya%22%20analisis&page=10 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b7079060bc0>: Failed to resolve 'garuda.kemdikbud.go.id' ([Errno -2] Name or service not known)"))
❌ Masih gagal. Coba ganti koneksi Internet (Hotspot HP) karena IP Colab mungkin sudah di-blacklist permanen oleh Garuda.

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import random
import re

def parser_garuda_pro(judul, abstrak=""):
    teks = (str(judul) + " " + str(abstrak)).lower()

    if any(x in teks for x in ['stunting', 'gizi', 'balita', 'sehat']):
        return ("Dinas Kesehatan Surabaya",
                "Data E-Health & Sayang Warga",
                "Intervensi Gizi",
                "Pemetaan balita stunting untuk bantuan protein.")

    elif any(x in teks for x in ['macet', 'dishub', 'bus', 'lalin']):
        return ("Dinas Perhubungan Surabaya",
                "Data CCTV SITS & GPS Bus",
                "Efisiensi Transportasi",
                "Optimasi lampu lalu lintas dan rute Suroboyo Bus.")

    elif any(x in teks for x in ['banjir', 'pompa', 'hujan', 'drainase']):
        return ("DSDABM Surabaya",
                "Data Curah Hujan & Elevasi Air",
                "Mitigasi Banjir",
                "Manajemen rumah pompa berbasis debit air riil.")

    elif any(x in teks for x in ['mbr', 'miskin', 'sosial']):
        return ("Dinas Sosial Surabaya",
                "Data MBR & Aplikasi Wargaku",
                "Akurasi Bantuan",
                "Validasi warga miskin agar bansos tepat sasaran.")

    return ("Pemkot Surabaya",
            "Dataset Sektoral",
            "Kajian Strategis",
            "Analisis data untuk efisiensi pelayanan publik.")


def crawl_garuda():

    base_url = "https://garuda.kemdiktisaintek.go.id/documents"
    keywords = ['Surabaya']
    results = []

    session = requests.Session()
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
        "Accept-Language": "id-ID,id;q=0.9"
    }

    print("🚀 Mulai crawling...")

    for keyword in keywords:
        for page in range(1, 6):

            params = {
                "q": keyword,
                "page": page
            }

            try:
                time.sleep(random.uniform(5,8))
                response = session.get(base_url, headers=headers, params=params, timeout=30)

                if response.status_code != 200:
                    print("Server menolak:", response.status_code)
                    break

                soup = BeautifulSoup(response.text, "html.parser")

                # Selector lebih tepat
                articles = soup.select("div.article-item")

                if not articles:
                    print("Halaman kosong di page", page)
                    break

                for art in articles:

                    title_tag = art.select_one("a.title-article")
                    if not title_tag:
                        continue

                    title = title_tag.text.strip()

                    if "surabaya" not in title.lower():
                        continue

                    link = "https://garuda.kemdiktisaintek.go.id" + title_tag["href"]

                    author_tag = art.select_one("div.author-article")
                    author = author_tag.text.strip() if author_tag else "N/A"

                    publisher_tag = art.select_one("div.publisher-article")
                    publisher = publisher_tag.text.strip() if publisher_tag else "N/A"

                    tahun_match = re.search(r'20\d{2}', art.text)
                    tahun = tahun_match.group(0) if tahun_match else "N/A"

                    instansi, data_used, output, deskripsi = parser_garuda_pro(title)

                    results.append({
                        "Judul Penelitian": title,
                        "Penulis": author,
                        "Tahun Terbit": tahun,
                        "Instansi Terkait": instansi,
                        "Data Yang Digunakan": data_used,
                        "Output Pemanfaatan": output,
                        "Deskripsi Pemanfaatan Spesifik": deskripsi,
                        "Sumber Publikasi": publisher,
                        "Link": link,
                        "Keyword Sumber": keyword
                    })

                print(f"Page {page} selesai...")

            except Exception as e:
                print("Error:", e)
                continue

    df = pd.DataFrame(results)
    df = df.drop_duplicates(subset=["Judul Penelitian"])

    return df


# RUN
df_final = crawl_garuda()

if not df_final.empty:
    df_final.to_excel("LAPORAN_PEMANFAATAN_DATA_SURABAYA.xlsx", index=False)
    print("✅ SUKSES! Total data:", len(df_final))
    display(df_final.head())
else:
    print("❌ Data kosong. Kemungkinan IP Colab diblokir atau halaman dirender JS.")

🚀 Mulai crawling...
Page 1 selesai...
Page 2 selesai...
Page 3 selesai...
Page 4 selesai...
Page 5 selesai...
✅ SUKSES! Total data: 45

,Judul Penelitian,Penulis,Tahun Terbit,Instansi Terkait,Data Yang Digunakan,Output Pemanfaatan,Deskripsi Pemanfaatan Spesifik,Sumber Publikasi,Link,Keyword Sumber
0,"Ekaningrum , Yuniawati PENGARUH PELATIHAN PELA...",N/A,2015,Pemkot Surabaya,Dataset Sektoral,Kajian Strategis,Analisis data untuk efisiensi pelayanan publik.,N/A,https://garuda.kemdiktisaintek.go.id/documents...,Surabaya
1,SURVEI MANAJEMEN OLAHRAGA PADA KEGIATAN EKSTRA...,N/A,2013,Pemkot Surabaya,Dataset Sektoral,Kajian Strategis,Analisis data untuk efisiensi pelayanan publik.,N/A,https://garuda.kemdiktisaintek.go.id/documents...,Surabaya
2,PROSES PENGURUSAN PENDAFTARAN HAK ATAS TANAH O...,N/A,2014,Pemkot Surabaya,Dataset Sektoral,Kajian Strategis,Analisis data untuk efisiensi pelayanan publik.,N/A,https://garuda.kemdiktisaintek.go.id/documents...,Surabaya
3,ANALISIS FAKTOR YANG MEMPENGARUHI PENINGKATAN ...,N/A,2020,Pemkot Surabaya,Dataset Sektoral,Kajian Strategis,Analisis data untuk efisiensi pelayanan publik.,N/A,https://garuda.kemdiktisaintek.go.id/documents...,Surabaya
4,Hygiene Sanitasi dan Keberadaan Bakteri Escher...,N/A,2023,Pemkot Surabaya,Dataset Sektoral,Kajian Strategis,Analisis data untuk efisiensi pelayanan publik.,N/A,https://garuda.kemdiktisaintek.go.id/documents...,Surabaya

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import random
import re

def analisis_dampak_dinamis(judul, abstrak):

    teks = (judul + " " + abstrak).lower()

    if any(k in teks for k in ["stunting", "gizi", "kesehatan"]):
        return ("Dinas Kesehatan Surabaya",
                "Data Balita & E-Health",
                "Model prediksi kesehatan masyarakat",
                "Penelitian berdampak pada peningkatan intervensi gizi dan pencegahan stunting di Surabaya.")

    elif any(k in teks for k in ["banjir", "drainase", "hujan"]):
        return ("DSDABM Surabaya",
                "Data Curah Hujan & Infrastruktur Drainase",
                "Model mitigasi banjir berbasis data",
                "Hasil penelitian membantu optimalisasi rumah pompa dan pengurangan risiko banjir kota.")

    elif any(k in teks for k in ["transportasi", "macet", "lalu lintas"]):
        return ("Dinas Perhubungan Surabaya",
                "Data Lalu Lintas & GPS Transportasi",
                "Optimasi sistem transportasi",
                "Berdampak pada pengurangan kemacetan dan peningkatan efisiensi mobilitas warga.")

    elif any(k in teks for k in ["kemiskinan", "bansos", "mbr"]):
        return ("Dinas Sosial Surabaya",
                "Data Sosial Ekonomi & Penerima Bantuan",
                "Model klasifikasi penerima bantuan",
                "Meningkatkan ketepatan sasaran bantuan sosial di Surabaya.")

    else:
        return ("Pemerintah Kota Surabaya",
                "Data Statistik Kota Surabaya",
                "Analisis kebijakan berbasis data",
                "Penelitian mendukung pengambilan kebijakan strategis berbasis data kota.")


def crawl_garuda_max():

    base_url = "https://garuda.kemdiktisaintek.go.id/documents"

    keywords = [
        "Surabaya",
        "Kota Surabaya",
        "Pemerintah Kota Surabaya",
        "Data Surabaya",
        "Studi kasus Surabaya"
    ]

    session = requests.Session()
    headers = {
        "User-Agent": "Mozilla/5.0",
        "Accept-Language": "id-ID,id;q=0.9"
    }

    results = []

    print("🚀 Crawling besar dimulai...")

    for keyword in keywords:
        for page in range(1, 21):  # sampai 20 halaman

            params = {"q": keyword, "page": page}

            try:
                time.sleep(random.uniform(5,9))
                response = session.get(base_url, headers=headers, params=params, timeout=30)

                if response.status_code != 200:
                    break

                soup = BeautifulSoup(response.text, "html.parser")
                articles = soup.select("div.article-item")

                if not articles:
                    break

                for art in articles:

                    title_tag = art.select_one("a.title-article")
                    if not title_tag:
                        continue

                    title = title_tag.text.strip()

                    if "surabaya" not in title.lower():
                        continue

                    detail_link = "https://garuda.kemdiktisaintek.go.id" + title_tag["href"]

                    # Ambil halaman detail untuk abstrak
                    try:
                        time.sleep(random.uniform(3,6))
                        detail_res = session.get(detail_link, headers=headers)
                        detail_soup = BeautifulSoup(detail_res.text, "html.parser")

                        abstrak_tag = detail_soup.find("div", string=re.compile("Abstrak", re.I))
                        abstrak = ""

                        if abstrak_tag:
                            abstrak = abstrak_tag.find_next("p").text.strip()

                    except:
                        abstrak = ""

                    author_tag = art.select_one("div.author-article")
                    author = author_tag.text.strip() if author_tag else "N/A"

                    publisher_tag = art.select_one("div.publisher-article")
                    publisher = publisher_tag.text.strip() if publisher_tag else "N/A"

                    tahun_match = re.search(r'20\d{2}', art.text)
                    tahun = tahun_match.group(0) if tahun_match else "N/A"

                    instansi, data_used, output, dampak = analisis_dampak_dinamis(title, abstrak)

                    results.append({
                        "Judul Penelitian": title,
                        "Penulis": author,
                        "Tahun Terbit": tahun,
                        "Instansi Terkait": instansi,
                        "Data Yang Digunakan": data_used,
                        "Output Pemanfaatan": output,
                        "Deskripsi Pemanfaatan Spesifik": dampak,
                        "Sumber Publikasi": publisher,
                        "Link": detail_link,
                        "Keyword Sumber": keyword
                    })

                print(f"Keyword {keyword} Page {page} selesai")

            except Exception as e:
                print("Error:", e)
                continue

    df = pd.DataFrame(results)
    df = df.drop_duplicates(subset=["Judul Penelitian"])

    return df


# RUN
df_final = crawl_garuda_max()

if not df_final.empty:
    df_final.to_excel("LAPORAN_SURABAYA_MAXIMAL.xlsx", index=False)
    print("✅ SELESAI! Total:", len(df_final))
    display(df_final.head())
else:
    print("❌ Data kosong atau IP diblokir.")

🚀 Crawling besar dimulai...
Keyword Surabaya Page 1 selesai
Keyword Surabaya Page 2 selesai
Keyword Surabaya Page 3 selesai
Keyword Surabaya Page 4 selesai
Keyword Surabaya Page 5 selesai
Keyword Surabaya Page 6 selesai
Keyword Surabaya Page 7 selesai
Keyword Surabaya Page 8 selesai
Keyword Surabaya Page 9 selesai
Keyword Surabaya Page 10 selesai
Keyword Surabaya Page 11 selesai
Keyword Surabaya Page 12 selesai
Keyword Surabaya Page 13 selesai
Keyword Surabaya Page 14 selesai
Keyword Surabaya Page 15 selesai
Keyword Surabaya Page 16 selesai
Keyword Surabaya Page 17 selesai
Keyword Surabaya Page 18 selesai
Keyword Surabaya Page 19 selesai
Keyword Surabaya Page 20 selesai
Keyword Kota Surabaya Page 1 selesai
Keyword Kota Surabaya Page 2 selesai
Keyword Kota Surabaya Page 3 selesai
Keyword Kota Surabaya Page 4 selesai
Keyword Kota Surabaya Page 5 selesai
Keyword Kota Surabaya Page 6 selesai
Keyword Kota Surabaya Page 7 selesai
Keyword Kota Surabaya Page 8 selesai
Keyword Kota Surabaya Page 9 selesai
Keyword Kota Surabaya Page 10 selesai
Keyword Kota Surabaya Page 11 selesai
Keyword Kota Surabaya Page 12 selesai
Keyword Kota Surabaya Page 13 selesai
Keyword Kota Surabaya Page 14 selesai
Keyword Kota Surabaya Page 15 selesai
Keyword Kota Surabaya Page 16 selesai
Keyword Kota Surabaya Page 17 selesai
Keyword Kota Surabaya Page 18 selesai
Keyword Kota Surabaya Page 19 selesai
Keyword Kota Surabaya Page 20 selesai
Keyword Pemerintah Kota Surabaya Page 1 selesai
Keyword Pemerintah Kota Surabaya Page 2 selesai
Keyword Pemerintah Kota Surabaya Page 3 selesai
Keyword Pemerintah Kota Surabaya Page 4 selesai
Keyword Pemerintah Kota Surabaya Page 5 selesai
Keyword Pemerintah Kota Surabaya Page 6 selesai
Keyword Pemerintah Kota Surabaya Page 7 selesai
Keyword Pemerintah Kota Surabaya Page 8 selesai
Keyword Pemerintah Kota Surabaya Page 9 selesai
Keyword Pemerintah Kota Surabaya Page 10 selesai
Keyword Pemerintah Kota Surabaya Page 11 selesai
Keyword Pemerintah Kota Surabaya Page 12 selesai
Keyword Pemerintah Kota Surabaya Page 13 selesai
Keyword Pemerintah Kota Surabaya Page 14 selesai
Keyword Pemerintah Kota Surabaya Page 15 selesai
Keyword Pemerintah Kota Surabaya Page 16 selesai
Keyword Pemerintah Kota Surabaya Page 17 selesai
Keyword Pemerintah Kota Surabaya Page 18 selesai
Keyword Pemerintah Kota Surabaya Page 19 selesai
Keyword Pemerintah Kota Surabaya Page 20 selesai
Keyword Data Surabaya Page 1 selesai
Keyword Data Surabaya Page 2 selesai
Keyword Data Surabaya Page 3 selesai
Keyword Data Surabaya Page 4 selesai
Keyword Data Surabaya Page 5 selesai
Keyword Data Surabaya Page 6 selesai
Keyword Data Surabaya Page 7 selesai
Keyword Data Surabaya Page 8 selesai
Keyword Data Surabaya Page 9 selesai
Keyword Data Surabaya Page 10 selesai
Keyword Data Surabaya Page 11 selesai
Keyword Data Surabaya Page 12 selesai
Keyword Data Surabaya Page 13 selesai
Keyword Data Surabaya Page 14 selesai
Keyword Data Surabaya Page 15 selesai
Keyword Data Surabaya Page 16 selesai
Keyword Data Surabaya Page 17 selesai
Keyword Data Surabaya Page 18 selesai
Keyword Data Surabaya Page 19 selesai
Keyword Data Surabaya Page 20 selesai
Keyword Studi kasus Surabaya Page 1 selesai
Keyword Studi kasus Surabaya Page 2 selesai
Keyword Studi kasus Surabaya Page 3 selesai
Keyword Studi kasus Surabaya Page 4 selesai
Keyword Studi kasus Surabaya Page 5 selesai
Keyword Studi kasus Surabaya Page 6 selesai
Keyword Studi kasus Surabaya Page 7 selesai
Keyword Studi kasus Surabaya Page 8 selesai
Keyword Studi kasus Surabaya Page 9 selesai
Keyword Studi kasus Surabaya Page 10 selesai
Keyword Studi kasus Surabaya Page 11 selesai
Keyword Studi kasus Surabaya Page 12 selesai
Keyword Studi kasus Surabaya Page 13 selesai
Keyword Studi kasus Surabaya Page 14 selesai
Keyword Studi kasus Surabaya Page 15 selesai
Keyword Studi kasus Surabaya Page 16 selesai
Keyword Studi kasus Surabaya Page 17 selesai
Keyword Studi kasus Surabaya Page 18 selesai
Keyword Studi kasus Surabaya Page 19 selesai
Keyword Studi kasus Surabaya Page 20 selesai
✅ SELESAI! Total: 734

,Judul Penelitian,Penulis,Tahun Terbit,Instansi Terkait,Data Yang Digunakan,Output Pemanfaatan,Deskripsi Pemanfaatan Spesifik,Sumber Publikasi,Link,Keyword Sumber
0,"Ekaningrum , Yuniawati PENGARUH PELATIHAN PELA...",N/A,2015,Pemerintah Kota Surabaya,Data Statistik Kota Surabaya,Analisis kebijakan berbasis data,Penelitian mendukung pengambilan kebijakan str...,N/A,https://garuda.kemdiktisaintek.go.id/documents...,Surabaya
1,SURVEI MANAJEMEN OLAHRAGA PADA KEGIATAN EKSTRA...,N/A,2013,Pemerintah Kota Surabaya,Data Statistik Kota Surabaya,Analisis kebijakan berbasis data,Penelitian mendukung pengambilan kebijakan str...,N/A,https://garuda.kemdiktisaintek.go.id/documents...,Surabaya
2,PROSES PENGURUSAN PENDAFTARAN HAK ATAS TANAH O...,N/A,2014,Pemerintah Kota Surabaya,Data Statistik Kota Surabaya,Analisis kebijakan berbasis data,Penelitian mendukung pengambilan kebijakan str...,N/A,https://garuda.kemdiktisaintek.go.id/documents...,Surabaya
3,ANALISIS FAKTOR YANG MEMPENGARUHI PENINGKATAN ...,N/A,2020,Pemerintah Kota Surabaya,Data Statistik Kota Surabaya,Analisis kebijakan berbasis data,Penelitian mendukung pengambilan kebijakan str...,N/A,https://garuda.kemdiktisaintek.go.id/documents...,Surabaya
4,Hygiene Sanitasi dan Keberadaan Bakteri Escher...,N/A,2023,Pemerintah Kota Surabaya,Data Statistik Kota Surabaya,Analisis kebijakan berbasis data,Penelitian mendukung pengambilan kebijakan str...,N/A,https://garuda.kemdiktisaintek.go.id/documents...,Surabaya

In [ ]:
import os
from datetime import datetime

def crawl_garuda_max_5tahun():

    base_url = "https://garuda.kemdiktisaintek.go.id/documents"

    keywords = [
        "Surabaya",
        # "Kota Surabaya",
        # "Pemerintah Kota Surabaya",
        # "Data Surabaya",
        # "Studi kasus Surabaya"
    ]

    session = requests.Session()
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
        "Accept-Language": "id-ID,id;q=0.9"
    }

    tahun_sekarang = datetime.now().year
    batas_tahun = tahun_sekarang - 4   # 5 tahun terakhir

    results = []

    print("🚀 Crawling 5 tahun terakhir dimulai...")

    for keyword in keywords:
        for page in range(1, 11):  # max 10 halaman biar aman

            params = {"q": keyword, "page": page}

            try:
                time.sleep(random.uniform(4,8))
                response = session.get(base_url, headers=headers, params=params, timeout=30)

                if response.status_code != 200:
                    break

                soup = BeautifulSoup(response.text, "html.parser")
                articles = soup.select("div.article-item")

                if not articles:
                    break

                for art in articles:

                    title_tag = art.select_one("a.title-article")
                    if not title_tag:
                        continue

                    title = title_tag.text.strip()

                    if "surabaya" not in title.lower():
                        continue

                    tahun_match = re.search(r'20\d{2}', art.text)
                    tahun = int(tahun_match.group(0)) if tahun_match else None

                    # 🔥 FILTER 5 TAHUN TERAKHIR
                    if not tahun or tahun < batas_tahun:
                        continue

                    detail_link = "https://garuda.kemdiktisaintek.go.id" + title_tag["href"]

                    # ambil abstrak
                    abstrak = ""
                    try:
                        time.sleep(random.uniform(2,5))
                        detail_res = session.get(detail_link, headers=headers)
                        detail_soup = BeautifulSoup(detail_res.text, "html.parser")

                        abs_tag = detail_soup.find("div", string=re.compile("Abstrak", re.I))
                        if abs_tag:
                            abstrak = abs_tag.find_next("p").text.strip()
                    except:
                        pass

                    instansi, data_used, output, dampak = analisis_dampak_dinamis(title, abstrak)

                    results.append({
                        "Judul Penelitian": title,
                        "Tahun": tahun,
                        "Instansi Terkait": instansi,
                        "Data Yang Digunakan": data_used,
                        "Output Pemanfaatan": output,
                        "Dampak Spesifik": dampak,
                        "Link": detail_link,
                        "Keyword": keyword
                    })

                print(f"✅ {keyword} Page {page} selesai")

            except Exception as e:
                print("Error:", e)
                continue

    df = pd.DataFrame(results)
    df = df.drop_duplicates(subset=["Judul Penelitian"])

    return df
    df_final = crawl_garuda_max_5tahun()

if not df_final.empty:

    # Folder aman
    save_folder = os.path.join(os.getcwd(), "hasil_crawling")
    os.makedirs(save_folder, exist_ok=True)

    excel_path = os.path.join(save_folder, "LAPORAN_SURABAYA_5_TAHUN.xlsx")
    csv_path = os.path.join(save_folder, "LAPORAN_SURABAYA_5_TAHUN_BACKUP.csv")

    df_final.to_excel(excel_path, index=False)
    df_final.to_csv(csv_path, index=False)

    print("✅ Data tersimpan di:")
    print(excel_path)
    print(csv_path)
    print("Total data:", len(df_final))

else:
    print("❌ Data kosong atau IP diblokir.")

✅ Data tersimpan di:
/content/hasil_crawling/LAPORAN_SURABAYA_5_TAHUN.xlsx
/content/hasil_crawling/LAPORAN_SURABAYA_5_TAHUN_BACKUP.csv
Total data: 734

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import random
import re


def analisis_dampak_dinamis(judul, abstrak):

    teks = (judul + " " + abstrak).lower()

    if any(k in teks for k in ["stunting", "gizi", "kesehatan"]):
        instansi = "Dinas Kesehatan Surabaya"
        data_used = "Data Balita, E-Health, dan survei kesehatan"
        output = "Model analisis kesehatan masyarakat"

    elif any(k in teks for k in ["banjir", "drainase", "hujan"]):
        instansi = "DSDABM Surabaya"
        data_used = "Data curah hujan, topografi, dan drainase"
        output = "Model mitigasi banjir berbasis analisis hidrologi"

    elif any(k in teks for k in ["transportasi", "macet", "lalu lintas"]):
        instansi = "Dinas Perhubungan Surabaya"
        data_used = "Data lalu lintas, GPS kendaraan, dan volume kendaraan"
        output = "Model optimasi transportasi perkotaan"

    elif any(k in teks for k in ["kemiskinan", "bansos", "mbr"]):
        instansi = "Dinas Sosial Surabaya"
        data_used = "Data sosial ekonomi dan penerima bantuan"
        output = "Model klasifikasi penerima bantuan sosial"

    else:
        instansi = "Pemerintah Kota Surabaya"
        data_used = "Data statistik dan data pembangunan kota"
        output = "Analisis kebijakan berbasis data kota"

    # Deskripsi dibuat dari abstrak (bukan template statis)
    deskripsi = abstrak[:300] if abstrak else "Analisis pemanfaatan data dalam penelitian terkait Surabaya."

    return instansi, data_used, output, deskripsi


def crawl_garuda_max():

    base_url = "https://garuda.kemdiktisaintek.go.id/documents"

    keywords = [
        "Surabaya",
        "Kota Surabaya",
        "Pemerintah Kota Surabaya",
        "Data Surabaya",
        "Studi kasus Surabaya"
    ]

    session = requests.Session()
    headers = {
        "User-Agent": "Mozilla/5.0",
        "Accept-Language": "id-ID,id;q=0.9"
    }

    results = []

    print("🚀 Crawling besar dimulai...")

    for keyword in keywords:
        for page in range(1, 30):   # diperbanyak

            params = {"q": keyword, "page": page}

            try:
                time.sleep(random.uniform(4,7))
                response = session.get(base_url, headers=headers, params=params, timeout=30)

                if response.status_code != 200:
                    break

                soup = BeautifulSoup(response.text, "html.parser")
                articles = soup.select("div.article-item")

                if not articles:
                    break

                for art in articles:

                    title_tag = art.select_one("a.title-article")
                    if not title_tag:
                        continue

                    title = title_tag.text.strip()

                    if "surabaya" not in title.lower():
                        continue

                    detail_link = "https://garuda.kemdiktisaintek.go.id" + title_tag["href"]

                    abstrak = ""
                    author = ""
                    tahun = ""

                    try:
                        time.sleep(random.uniform(3,5))
                        detail_res = session.get(detail_link, headers=headers)
                        detail_soup = BeautifulSoup(detail_res.text, "html.parser")

                        # ABSTRAK
                        abs_section = detail_soup.find(text=re.compile("Abstrak", re.I))
                        if abs_section:
                            abstrak = abs_section.find_parent().find_next("p").text.strip()

                        # PENULIS
                        authors = detail_soup.select("span[itemprop='name']")
                        if authors:
                            author = ", ".join([a.text.strip() for a in authors])

                        # TAHUN
                        tahun_match = re.search(r'20\d{2}', detail_soup.text)
                        if tahun_match:
                            tahun = tahun_match.group(0)

                    except:
                        pass

                    if not author:
                        continue

                    publisher_tag = art.select_one("div.publisher-article")
                    publisher = publisher_tag.text.strip() if publisher_tag else "Jurnal Ilmiah"

                    instansi, data_used, output, dampak = analisis_dampak_dinamis(title, abstrak)

                    results.append({
                        "Judul Penelitian": title,
                        "Penulis": author,
                        "Tahun Terbit": tahun,
                        "Instansi Terkait": instansi,
                        "Data Yang Digunakan": data_used,
                        "Output Pemanfaatan": output,
                        "Deskripsi Pemanfaatan Spesifik": dampak,
                        "Sumber Publikasi": publisher,
                        "Link": detail_link,
                        "Keyword Sumber": keyword
                    })

                print(f"Keyword {keyword} Page {page} selesai")

            except Exception as e:
                print("Error:", e)
                continue

    df = pd.DataFrame(results)
    df = df.drop_duplicates(subset=["Judul Penelitian"])

    return df


df_final = crawl_garuda_max()

if not df_final.empty:
    df_final.to_excel("LAPORAN_SURABAYA_MAXIMAL.xlsx", index=False)
    print("✅ SELESAI! Total:", len(df_final))
else:
    print("❌ Data kosong atau IP diblokir.")

🚀 Crawling besar dimulai...

/tmp/ipykernel_265/753139807.py:107: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  abs_section = detail_soup.find(text=re.compile("Abstrak", re.I))

Keyword Surabaya Page 1 selesai
Keyword Surabaya Page 2 selesai
Keyword Surabaya Page 3 selesai
Keyword Surabaya Page 4 selesai
Keyword Surabaya Page 5 selesai
Keyword Surabaya Page 6 selesai
Keyword Surabaya Page 7 selesai
Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Keyword Surabaya Page 9 selesai
Keyword Surabaya Page 10 selesai
Keyword Surabaya Page 11 selesai
Keyword Surabaya Page 12 selesai
Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Keyword Surabaya Page 14 selesai
Keyword Surabaya Page 15 selesai
Keyword Surabaya Page 16 selesai
Keyword Surabaya Page 17 selesai
Keyword Surabaya Page 18 selesai
Keyword Surabaya Page 19 selesai
Keyword Surabaya Page 20 selesai
Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Keyword Surabaya Page 22 selesai
Keyword Surabaya Page 23 selesai
Keyword Surabaya Page 24 selesai
Keyword Surabaya Page 25 selesai
Keyword Surabaya Page 26 selesai
Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Keyword Surabaya Page 28 selesai
Keyword Surabaya Page 29 selesai
Keyword Kota Surabaya Page 1 selesai
Keyword Kota Surabaya Page 2 selesai
Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Keyword Kota Surabaya Page 4 selesai
Keyword Kota Surabaya Page 5 selesai
Keyword Kota Surabaya Page 6 selesai
Keyword Kota Surabaya Page 7 selesai
Keyword Kota Surabaya Page 8 selesai
Keyword Kota Surabaya Page 9 selesai
Keyword Kota Surabaya Page 10 selesai
Keyword Kota Surabaya Page 11 selesai
Keyword Kota Surabaya Page 12 selesai
Keyword Kota Surabaya Page 13 selesai
Keyword Kota Surabaya Page 14 selesai
Keyword Kota Surabaya Page 15 selesai
Keyword Kota Surabaya Page 16 selesai
Keyword Kota Surabaya Page 17 selesai
Keyword Kota Surabaya Page 18 selesai
Keyword Kota Surabaya Page 19 selesai
Keyword Kota Surabaya Page 20 selesai
Keyword Kota Surabaya Page 21 selesai
Keyword Kota Surabaya Page 22 selesai
Keyword Kota Surabaya Page 23 selesai
Keyword Kota Surabaya Page 24 selesai
Keyword Kota Surabaya Page 25 selesai
Keyword Kota Surabaya Page 26 selesai
Keyword Kota Surabaya Page 27 selesai
Keyword Kota Surabaya Page 28 selesai
Keyword Kota Surabaya Page 29 selesai
Keyword Pemerintah Kota Surabaya Page 1 selesai
Keyword Pemerintah Kota Surabaya Page 2 selesai
Keyword Pemerintah Kota Surabaya Page 3 selesai
Keyword Pemerintah Kota Surabaya Page 4 selesai
Keyword Pemerintah Kota Surabaya Page 5 selesai
Keyword Pemerintah Kota Surabaya Page 6 selesai
Keyword Pemerintah Kota Surabaya Page 7 selesai
Keyword Pemerintah Kota Surabaya Page 8 selesai
Keyword Pemerintah Kota Surabaya Page 9 selesai
Keyword Pemerintah Kota Surabaya Page 10 selesai
Keyword Pemerintah Kota Surabaya Page 11 selesai
Keyword Pemerintah Kota Surabaya Page 12 selesai
Keyword Pemerintah Kota Surabaya Page 13 selesai
Keyword Pemerintah Kota Surabaya Page 14 selesai
Keyword Pemerintah Kota Surabaya Page 15 selesai
Keyword Pemerintah Kota Surabaya Page 16 selesai
Keyword Pemerintah Kota Surabaya Page 17 selesai
Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Keyword Pemerintah Kota Surabaya Page 19 selesai
Keyword Pemerintah Kota Surabaya Page 20 selesai
Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Keyword Pemerintah Kota Surabaya Page 22 selesai
Keyword Pemerintah Kota Surabaya Page 23 selesai
Keyword Pemerintah Kota Surabaya Page 24 selesai
Keyword Pemerintah Kota Surabaya Page 25 selesai
Keyword Pemerintah Kota Surabaya Page 26 selesai
Keyword Pemerintah Kota Surabaya Page 27 selesai
Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Keyword Pemerintah Kota Surabaya Page 29 selesai
Keyword Data Surabaya Page 1 selesai
Keyword Data Surabaya Page 2 selesai
Keyword Data Surabaya Page 3 selesai
Keyword Data Surabaya Page 4 selesai
Keyword Data Surabaya Page 5 selesai
Keyword Data Surabaya Page 6 selesai
Keyword Data Surabaya Page 7 selesai
Keyword Data Surabaya Page 8 selesai
Keyword Data Surabaya Page 9 selesai
Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Keyword Data Surabaya Page 11 selesai
Keyword Data Surabaya Page 12 selesai
Keyword Data Surabaya Page 13 selesai
Keyword Data Surabaya Page 14 selesai
Keyword Data Surabaya Page 15 selesai
Keyword Data Surabaya Page 16 selesai
Keyword Data Surabaya Page 17 selesai
Keyword Data Surabaya Page 18 selesai
Keyword Data Surabaya Page 19 selesai
Keyword Data Surabaya Page 20 selesai
Keyword Data Surabaya Page 21 selesai
Keyword Data Surabaya Page 22 selesai
Keyword Studi kasus Surabaya Page 1 selesai
Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Keyword Studi kasus Surabaya Page 3 selesai
Keyword Studi kasus Surabaya Page 4 selesai
Keyword Studi kasus Surabaya Page 5 selesai
Keyword Studi kasus Surabaya Page 6 selesai
Keyword Studi kasus Surabaya Page 7 selesai
Keyword Studi kasus Surabaya Page 8 selesai
Keyword Studi kasus Surabaya Page 9 selesai
Keyword Studi kasus Surabaya Page 10 selesai
Keyword Studi kasus Surabaya Page 11 selesai
Keyword Studi kasus Surabaya Page 12 selesai
Keyword Studi kasus Surabaya Page 13 selesai
Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Keyword Studi kasus Surabaya Page 15 selesai
Keyword Studi kasus Surabaya Page 16 selesai
Keyword Studi kasus Surabaya Page 17 selesai
Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Keyword Studi kasus Surabaya Page 19 selesai
Keyword Studi kasus Surabaya Page 20 selesai
Keyword Studi kasus Surabaya Page 21 selesai
Keyword Studi kasus Surabaya Page 22 selesai
Keyword Studi kasus Surabaya Page 23 selesai
Keyword Studi kasus Surabaya Page 24 selesai
Keyword Studi kasus Surabaya Page 25 selesai
Keyword Studi kasus Surabaya Page 26 selesai
Keyword Studi kasus Surabaya Page 27 selesai
Keyword Studi kasus Surabaya Page 28 selesai
Keyword Studi kasus Surabaya Page 29 selesai
❌ Data kosong atau IP diblokir.

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import random
import re

# membersihkan karakter ilegal untuk excel
def clean_illegal_chars(text):
    if isinstance(text, str):
        return re.sub(r'[\x00-\x1F\x7F-\x9F]', '', text)
    return text


def analisis_dampak_dinamis(judul, abstrak):

    teks = (judul + " " + abstrak).lower()

    # membuat deskripsi lebih dinamis dari isi penelitian
    ringkasan = abstrak[:300] if abstrak else judul

    if any(k in teks for k in ["stunting","gizi","kesehatan"]):
        instansi = "Dinas Kesehatan Kota Surabaya"
        data = "Data kesehatan masyarakat, data balita, dan indikator gizi"
        output = f"Analisis kesehatan masyarakat terkait {judul.lower()}"
        deskripsi = f"Penelitian ini membahas {ringkasan} yang dapat dimanfaatkan oleh Dinas Kesehatan Surabaya untuk meningkatkan intervensi kesehatan masyarakat berbasis data."

    elif any(k in teks for k in ["banjir","drainase","hujan"]):
        instansi = "Dinas Sumber Daya Air dan Bina Marga Surabaya"
        data = "Data curah hujan, sistem drainase, dan kondisi infrastruktur kota"
        output = f"Model analisis mitigasi banjir berbasis data kota"
        deskripsi = f"Studi ini menyoroti {ringkasan} yang berpotensi digunakan pemerintah kota untuk perencanaan pengendalian banjir dan pengelolaan drainase."

    elif any(k in teks for k in ["transportasi","lalu lintas","kemacetan","traffic"]):
        instansi = "Dinas Perhubungan Surabaya"
        data = "Data lalu lintas, mobilitas kendaraan, dan sistem transportasi"
        output = f"Analisis sistem transportasi dan mobilitas perkotaan"
        deskripsi = f"Penelitian ini mengevaluasi {ringkasan} yang dapat menjadi dasar pengambilan kebijakan transportasi dan pengurangan kemacetan."

    elif any(k in teks for k in ["kemiskinan","bansos","mbr","sosial"]):
        instansi = "Dinas Sosial Kota Surabaya"
        data = "Data sosial ekonomi masyarakat dan penerima bantuan"
        output = "Analisis kebijakan bantuan sosial berbasis data"
        deskripsi = f"Hasil penelitian membahas {ringkasan} yang dapat membantu pemerintah dalam meningkatkan ketepatan sasaran program bantuan sosial."

    else:
        instansi = "Pemerintah Kota Surabaya"
        data = "Data statistik kota dan indikator pembangunan daerah"
        output = f"Analisis kebijakan pembangunan kota berdasarkan penelitian {judul.lower()}"
        deskripsi = f"Penelitian ini membahas {ringkasan} yang berpotensi mendukung pengambilan keputusan pemerintah kota berbasis data penelitian."

    return instansi, data, output, deskripsi


def crawl_garuda_max():

    base_url = "https://garuda.kemdiktisaintek.go.id/documents"

    keywords = [
        "Surabaya",
        "Kota Surabaya",
        "Pemerintah Kota Surabaya",
        "Data Surabaya",
        "Studi kasus Surabaya"
    ]

    session = requests.Session()

    headers = {
        "User-Agent": "Mozilla/5.0",
        "Accept-Language": "id-ID,id;q=0.9"
    }

    results = []

    print("🚀 Crawling besar dimulai...")

    for keyword in keywords:
        for page in range(1, 30):  # diperbanyak halaman

            params = {"q": keyword, "page": page}

            try:
                time.sleep(random.uniform(4,7))
                response = session.get(base_url, headers=headers, params=params, timeout=30)

                if response.status_code != 200:
                    break

                soup = BeautifulSoup(response.text, "html.parser")
                articles = soup.select("div.article-item")

                if not articles:
                    break

                for art in articles:

                    title_tag = art.select_one("a.title-article")
                    if not title_tag:
                        continue

                    title = title_tag.text.strip()

                    if "surabaya" not in title.lower():
                        continue

                    detail_link = "https://garuda.kemdiktisaintek.go.id" + title_tag["href"]

                    abstrak = ""

                    try:
                        time.sleep(random.uniform(2,4))
                        detail_res = session.get(detail_link, headers=headers)
                        detail_soup = BeautifulSoup(detail_res.text, "html.parser")

                        abs_tag = detail_soup.find("p")
                        if abs_tag:
                            abstrak = abs_tag.text.strip()

                    except:
                        pass

                    # penulis
                    author_tag = art.select_one("div.author-article")
                    author = author_tag.text.strip() if author_tag else ""

                    if author == "" or author.lower() == "n/a":
                        author = "Penulis tidak tercantum pada metadata"

                    # publisher
                    publisher_tag = art.select_one("div.publisher-article")
                    publisher = publisher_tag.text.strip() if publisher_tag else "Jurnal Nasional"

                    # tahun
                    tahun_match = re.search(r'20\d{2}', art.text)
                    tahun = tahun_match.group(0) if tahun_match else "Tidak diketahui"

                    instansi, data_used, output, dampak = analisis_dampak_dinamis(title, abstrak)

                    results.append({
                        "Judul": title,
                        "Penulis": author,
                        "Tahun Terbit": tahun,
                        "Instansi Terkait": instansi,
                        "Data Yang Digunakan": data_used,
                        "Output Pemanfaatan": output,
                        "Deskripsi Pemanfaatan Spesifik": dampak,
                        "Sumber Publikasi": publisher,
                        "Link": detail_link,
                        "Keyword Sumber": keyword
                    })

                print(f"Keyword {keyword} Page {page} selesai")

            except Exception as e:
                print("Error:", e)
                continue


    df = pd.DataFrame(results)

    df = df.drop_duplicates(subset=["Judul"])

    # bersihkan karakter ilegal
    df = df.applymap(clean_illegal_chars)

    return df


# RUN
df_final = crawl_garuda_max()

if not df_final.empty:

    df_final.to_excel("LAPORAN_SURABAYA_MAXIMAL.xlsx", index=False)

    print("✅ SELESAI!")
    print("Total data:", len(df_final))

else:
    print("❌ Data kosong atau IP diblokir.")

🚀 Crawling besar dimulai...
Keyword Surabaya Page 1 selesai
Keyword Surabaya Page 2 selesai
Keyword Surabaya Page 3 selesai
Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Keyword Surabaya Page 5 selesai
Keyword Surabaya Page 6 selesai
Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Keyword Surabaya Page 8 selesai
Keyword Surabaya Page 9 selesai
Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Keyword Surabaya Page 11 selesai
Keyword Surabaya Page 12 selesai
Keyword Surabaya Page 13 selesai
Keyword Surabaya Page 14 selesai
Keyword Surabaya Page 15 selesai
Keyword Surabaya Page 16 selesai
Keyword Surabaya Page 17 selesai
Keyword Surabaya Page 18 selesai
Keyword Surabaya Page 19 selesai
Keyword Surabaya Page 20 selesai
Keyword Surabaya Page 21 selesai
Keyword Surabaya Page 22 selesai
Keyword Surabaya Page 23 selesai
Keyword Surabaya Page 24 selesai
Keyword Surabaya Page 25 selesai
Keyword Surabaya Page 26 selesai
Keyword Surabaya Page 27 selesai
Keyword Surabaya Page 28 selesai
Keyword Surabaya Page 29 selesai
Keyword Kota Surabaya Page 1 selesai
Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Keyword Kota Surabaya Page 3 selesai
Keyword Kota Surabaya Page 4 selesai
Keyword Kota Surabaya Page 5 selesai
Keyword Kota Surabaya Page 6 selesai
Keyword Kota Surabaya Page 7 selesai
Keyword Kota Surabaya Page 8 selesai
Keyword Kota Surabaya Page 9 selesai
Keyword Kota Surabaya Page 10 selesai
Keyword Kota Surabaya Page 11 selesai
Keyword Kota Surabaya Page 12 selesai
Keyword Kota Surabaya Page 13 selesai
Keyword Kota Surabaya Page 14 selesai
Keyword Kota Surabaya Page 15 selesai
Keyword Kota Surabaya Page 16 selesai
Keyword Kota Surabaya Page 17 selesai
Keyword Kota Surabaya Page 18 selesai
Keyword Kota Surabaya Page 19 selesai
Keyword Kota Surabaya Page 20 selesai
Keyword Kota Surabaya Page 21 selesai
Keyword Kota Surabaya Page 22 selesai
Keyword Kota Surabaya Page 23 selesai
Keyword Kota Surabaya Page 24 selesai
Keyword Kota Surabaya Page 25 selesai
Keyword Kota Surabaya Page 26 selesai
Keyword Kota Surabaya Page 27 selesai
Keyword Kota Surabaya Page 28 selesai

In [ ]:
import requests
import pandas as pd
import time
import re
from tqdm.notebook import tqdm
from google.colab import files

# =====================================================
# 🔧 KONFIGURASI
# =====================================================
TAHUN_MULAI = 2021
OUTPUT_FILE = 'Laporan_Pemanfaatan_Data_Surabaya_300.xlsx'
LIMIT_PER_QUERY = 100

# =====================================================
# ✅ QUERY (Tetap Sesuai Permintaan)
# =====================================================
SEMANTIC_QUERIES = [
    'Surabaya traffic data analysis', 'Suroboyo Bus optimization', 'Dishub Surabaya data',
    'Surabaya health data stunting', 'Dinas Kesehatan Surabaya dengue',
    'Puskesmas Surabaya data', 'Surabaya poverty mapping MBR',
    'Flood prediction Surabaya data', 'Open Data Pemkot Surabaya',
    'Smart City Surabaya implementation', 'Surabaya education data analysis'
]

OPENALEX_QUERIES = [
    'Surabaya open data government', 'Surabaya smart city data driven',
    'Surabaya public health data', 'Surabaya flood disaster data',
    'Surabaya urban data analysis'
]

# =====================================================
# 🧠 MESIN KLASIFIKASI (Tidak Diubah)
# =====================================================
def klasifikasi_dan_ekstraksi(abstrak, judul):
    teks_full = (str(judul) + " " + str(abstrak)).lower()
    data_used = "Data Umum Kota Surabaya"
    instansi = "Pemerintah Kota Surabaya"

    if any(x in teks_full for x in ['penduduk', 'kependudukan', 'citizen', 'capil', 'ikd', 'lahir', 'mati']):
        data_used, instansi = "Data Adminduk", "Dispendukcapil"
    elif any(x in teks_full for x in ['transport', 'bus', 'traffic', 'jalan', 'dishub', 'kendaraan', 'rute', 'angkutan', 'parking']):
        data_used, instansi = "Data Transportasi", "Dinas Perhubungan"
    elif any(x in teks_full for x in ['stunting', 'sehat', 'health', 'dbd', 'dinkes', 'puskesmas', 'pasien', 'gizi', 'imunisasi', 'maternal']):
        data_used, instansi = "Data Kesehatan", "Dinas Kesehatan"
    elif any(x in teks_full for x in ['poverty', 'miskin', 'mbr', 'sosial', 'dinsos', 'bantuan', 'pkh', 'rtlh']):
        data_used, instansi = "Data Sosial & MBR", "Dinas Sosial"
    elif any(x in teks_full for x in ['banjir', 'flood', 'sampah', 'waste', 'dlh', 'drainase', 'hujan', 'lingkungan', 'air quality']):
        data_used, instansi = "Data Lingkungan", "DLH / Dinas SDABM"
    elif any(x in teks_full for x in ['umkm', 'dagang', 'ekonomi', 'pasar', 'koperasi', 'investasi', 'pariwisata']):
        data_used, instansi = "Data Ekonomi", "Dinkopdag"
    elif any(x in teks_full for x in ['sekolah', 'pendidikan', 'education', 'siswa', 'guru']):
        data_used, instansi = "Data Pendidikan", "Dinas Pendidikan"

    out_type = "Analisis Strategis"
    if any(x in teks_full for x in ['clustering', 'klaster', 'mapping', 'gis', 'spasial', 'peta', 'spatial']):
        out_type = "Peta Sebaran / Zonasi"
    elif any(x in teks_full for x in ['predict', 'forecasting', 'prediksi', 'machine learning', 'estimasi', 'deep learning', 'neural']):
        out_type = "Model Prediksi"
    elif any(x in teks_full for x in ['dashboard', 'system', 'web', 'application', 'aplikasi', 'monitoring', 'platform']):
        out_type = "Sistem/Aplikasi"

    deskripsi = "Memberikan rekomendasi kebijakan berbasis data bagi instansi terkait."
    if abstrak and abstrak != 'N/A':
        clean_abs = str(abstrak).replace('\n', ' ')
        sentences = re.split(r'(?<=[.!?]) +', clean_abs)
        keywords_hasil = ['result', 'show', 'conclude', 'aim', 'hasil', 'menunjukkan', 'kesimpulan', 'tujuan', 'diharapkan', 'found', 'achieve']
        found = False
        for sentence in sentences:
            if any(key in sentence.lower() for key in keywords_hasil) and len(sentence) > 30:
                deskripsi = sentence.strip()
                found = True
                break
        if not found and sentences:
            deskripsi = sentences[0].strip()

    deskripsi_final = f"[{out_type}] {deskripsi}"
    if len(deskripsi_final) > 250:
        deskripsi_final = deskripsi_final[:247] + "..."

    return data_used, instansi, out_type, deskripsi_final

# =====================================================
# 📚 SUMBER 1: SEMANTIC SCHOLAR (OPTIMASI OFFSET)
# =====================================================
def crawl_semantic_scholar(queries):
    BASE_URL = 'https://api.semanticscholar.org/graph/v1/paper/search'
    results = []
    print(f"\n📘 [Semantic Scholar] Memulai pencarian mendalam...")

    for q in tqdm(queries, desc='Semantic Scholar'):
        # Melakukan looping offset (0, 100, 200) untuk mendapatkan lebih banyak data per query
        for offset in [0, 100]:
            params = {
                'query': q,
                'limit': LIMIT_PER_QUERY,
                'offset': offset,
                'fields': 'title,year,abstract,url,venue,authors',
                'year': f'{TAHUN_MULAI}-'
            }
            try:
                time.sleep(1.5)
                r = requests.get(BASE_URL, params=params, timeout=30)
                if r.status_code == 200:
                    data = r.json().get('data', [])
                    if not data: break
                    for p in data:
                        data_used, instansi, out_type, desc = klasifikasi_dan_ekstraksi(
                            p.get('abstract', ''), p.get('title', '')
                        )
                        penulis = p['authors'][0]['name'] if p.get('authors') else "N/A"
                        results.append({
                            'Judul Penelitian': p.get('title', ''),
                            'Penulis': penulis,
                            'Tahun Terbit': p.get('year'),
                            'Instansi Terkait': instansi,
                            'Data Yang Digunakan': data_used,
                            'Output Pemanfaatan': out_type,
                            'Deskripsi Pemanfaatan Spesifik': desc,
                            'Sumber Publikasi': p.get('venue', 'N/A'),
                            'Link': p.get('url', ''),
                            'Asal Sumber': 'Semantic Scholar'
                        })
                elif r.status_code == 429:
                    time.sleep(20)
            except: continue
    return results

# =====================================================
# 🆕 SUMBER 2: OPENALEX API (OPTIMASI PAGE)
# =====================================================
def crawl_openalex(queries):
    BASE_URL = 'https://api.openalex.org/works'
    results = []
    print(f"\n🟢 [OpenAlex] Memulai pencarian mendalam...")

    for q in tqdm(queries, desc='OpenAlex'):
        # Mengambil 2 halaman pertama per query
        for page in [1, 2]:
            params = {
                'search': q,
                'filter': f'publication_year:{TAHUN_MULAI}-2025',
                'per-page': LIMIT_PER_QUERY,
                'page': page,
                'select': 'title,publication_year,abstract_inverted_index,primary_location,authorships,id',
                'mailto': 'admin@surabaya.go.id'
            }
            try:
                time.sleep(1)
                r = requests.get(BASE_URL, params=params, timeout=30)
                if r.status_code == 200:
                    data = r.json().get('results', [])
                    if not data: break
                    for p in data:
                        title = p.get('title', '')
                        if not title or 'surabaya' not in title.lower(): continue

                        inv_abs = p.get('abstract_inverted_index', {})
                        if inv_abs:
                            word_pos = [(word, pos) for word, positions in inv_abs.items() for pos in positions]
                            word_pos.sort(key=lambda x: x[1])
                            abstrak = ' '.join([w for w, _ in word_pos])
                        else: abstrak = ''

                        authorships = p.get('authorships', [])
                        penulis = authorships[0]['author']['display_name'] if authorships else 'N/A'
                        loc = p.get('primary_location', {})
                        venue = loc.get('source', {}).get('display_name', 'N/A') if loc else 'N/A'
                        link = f"https://openalex.org/{p.get('id', '').replace('https://openalex.org/', '')}"

                        data_used, instansi, out_type, desc = klasifikasi_dan_ekstraksi(abstrak, title)

                        results.append({
                            'Judul Penelitian': title,
                            'Penulis': penulis,
                            'Tahun Terbit': p.get('publication_year'),
                            'Instansi Terkait': instansi,
                            'Data Yang Digunakan': data_used,
                            'Output Pemanfaatan': out_type,
                            'Deskripsi Pemanfaatan Spesifik': desc,
                            'Sumber Publikasi': venue,
                            'Link': link,
                            'Asal Sumber': 'OpenAlex'
                        })
            except: continue
    return results

# =====================================================
# 🚀 EKSEKUSI GABUNGAN
# =====================================================
print("🚀 Memulai crawling (Target minimal 300 data)...")

hasil_semantic = crawl_semantic_scholar(SEMANTIC_QUERIES)
hasil_openalex = crawl_openalex(OPENALEX_QUERIES)

semua_hasil = hasil_semantic + hasil_openalex
df_final = pd.DataFrame(semua_hasil).drop_duplicates(subset=['Judul Penelitian'])
df_final = df_final.sort_values(by='Tahun Terbit', ascending=False)

# Memastikan hasil akhir rapi
if not df_final.empty:
    df_final.to_excel(OUTPUT_FILE, index=False)
    print(f"\n✅ BERHASIL!")
    print(f"📊 Total unik ditemukan: {len(df_final)} data")
    files.download(OUTPUT_FILE)
    display(df_final.head(10))
else:
    print("❌ Tidak ada data ditemukan.")

🚀 Memulai crawling (Target minimal 300 data)...

📘 [Semantic Scholar] Memulai pencarian mendalam...

Semantic Scholar:   0%|          | 0/11 [00:00<?, ?it/s]

🟢 [OpenAlex] Memulai pencarian mendalam...

OpenAlex:   0%|          | 0/5 [00:00<?, ?it/s]

✅ BERHASIL!
📊 Total unik ditemukan: 244 data

,Judul Penelitian,Penulis,Tahun Terbit,Instansi Terkait,Data Yang Digunakan,Output Pemanfaatan,Deskripsi Pemanfaatan Spesifik,Sumber Publikasi,Link,Asal Sumber
39,Efficiency of Inpatient Care Services at Surab...,Frea Astrilia Tamarina,2026,Dinas Kesehatan,Data Kesehatan,Analisis Strategis,[Analisis Strategis] The construction of a new...,Qanun Medika - Medical Journal Faculty of Medi...,https://www.semanticscholar.org/paper/7b756795...,Semantic Scholar
38,Descriptive Study: Characteristics of Informat...,Donny Permana,2026,Dispendukcapil,Data Adminduk,Analisis Strategis,[Analisis Strategis] This study aimed to deter...,Qanun Medika - Medical Journal Faculty of Medi...,https://www.semanticscholar.org/paper/620024e4...,Semantic Scholar
130,ANALISIS STRATEGI GAYA KEPEMIMPINAN DALAM MENI...,Candra Wjaya,2026,Pemerintah Kota Surabaya,Data Umum Kota Surabaya,Analisis Strategis,[Analisis Strategis] This study aims to examin...,Jurnal Manajemen,https://www.semanticscholar.org/paper/17ac7baa...,Semantic Scholar
131,Persepsi atas Kelemahan dan Kekuatan Sistem Pe...,Berta Dwi Murdoko,2026,Dinas Perhubungan,Data Transportasi,Sistem/Aplikasi,[Sistem/Aplikasi] Penelitian ini bertujuan unt...,Jurnal Locus Penelitian dan Pengabdian,https://www.semanticscholar.org/paper/3fb04715...,Semantic Scholar
132,STUDI KEBUTUHAN DAN KONDISI TOILET UMUM DI TAM...,Leila Pangastuti,2026,Dispendukcapil,Data Adminduk,Analisis Strategis,[Analisis Strategis] This study aims to: (1) m...,ACADEMIA: Jurnal Inovasi Riset Akademik,https://www.semanticscholar.org/paper/7fa6567e...,Semantic Scholar
181,KOMUNIKASI INTERPESONAL KARYAWAN DIVISI OPERAS...,Mochamad Brilian Eky Fernanda,2026,Dispendukcapil,Data Adminduk,Peta Sebaran / Zonasi,[Peta Sebaran / Zonasi] This study aims to ana...,Sintesa,https://www.semanticscholar.org/paper/49a602ed...,Semantic Scholar
134,Pengaruh Gaya Kepemimpinan dan Kepuasan Kerja ...,Yessy Auralia Febiyanti,2026,Dispendukcapil,Data Adminduk,Analisis Strategis,[Analisis Strategis] This study aims to analyz...,Jurnal Publikasi Sistem Informasi dan Manajeme...,https://www.semanticscholar.org/paper/e54dafb1...,Semantic Scholar
135,Comparative analysis of shoreline dynamics in ...,Eko Hadi Santoso,2026,Dispendukcapil,Data Adminduk,Sistem/Aplikasi,[Sistem/Aplikasi] Results reveal contrasting s...,BIO Web of Conferences,https://www.semanticscholar.org/paper/07b86bd4...,Semantic Scholar
133,PERAN GURU DALAM PENDEKATAN DEEP LEARNING UNTU...,Devi Amanda Sasabilla,2026,Dispendukcapil,Data Adminduk,Model Prediksi,[Model Prediksi] This study aims to describe t...,Pendas : Jurnal Ilmiah Pendidikan Dasar,https://www.semanticscholar.org/paper/ce6d2fa7...,Semantic Scholar
111,Menuju Layanan Administrasi yang Efektif dan E...,M. Anityasari,2025,DLH / Dinas SDABM,Data Lingkungan,Analisis Strategis,[Analisis Strategis] Hasil dari pendampingan i...,SEWAGATI,https://www.semanticscholar.org/paper/433e4c6a...,Semantic Scholar

In [ ]:
import requests
import pandas as pd
import time
import re
from tqdm.notebook import tqdm
from google.colab import files

# =====================================================
# 🔧 KONFIGURASI TARGET 1000 DATA
# =====================================================
TAHUN_MULAI = 2021
OUTPUT_FILE = 'Laporan_Pemanfaatan_Data_Surabaya_1000.xlsx'
LIMIT_PER_QUERY = 100

# Variasi Query diperbanyak agar mesin pencari punya banyak sumber data
SEMANTIC_QUERIES = [
    'Surabaya traffic data analysis', 'Suroboyo Bus transport optimization',
    'Surabaya health data stunting', 'Surabaya smart city implementation',
    'Surabaya flood disaster prediction', 'Surabaya waste management DLH',
    'Surabaya poverty mapping MBR', 'Surabaya urban planning GIS',
    'Surabaya economic growth open data', 'Surabaya education school mapping',
    'Surabaya government digital service', 'Surabaya air quality monitoring'
]

OPENALEX_QUERIES = [
    'Surabaya public health statistics', 'Surabaya transportation system',
    'Surabaya smart governance', 'Surabaya environmental study',
    'Surabaya social welfare data', 'Surabaya machine learning applications'
]

# =====================================================
# 🧠 MESIN KLASIFIKASI (TETAP / TIDAK DIUBAH)
# =====================================================
def klasifikasi_dan_ekstraksi(abstrak, judul):
    teks_full = (str(judul) + " " + str(abstrak)).lower()
    data_used, instansi = "Data Umum Kota Surabaya", "Pemerintah Kota Surabaya"

    if any(x in teks_full for x in ['penduduk', 'kependudukan', 'citizen', 'capil', 'ikd', 'lahir', 'mati']):
        data_used, instansi = "Data Adminduk", "Dispendukcapil"
    elif any(x in teks_full for x in ['transport', 'bus', 'traffic', 'jalan', 'dishub', 'kendaraan', 'rute', 'angkutan', 'parking']):
        data_used, instansi = "Data Transportasi", "Dinas Perhubungan"
    elif any(x in teks_full for x in ['stunting', 'sehat', 'health', 'dbd', 'dinkes', 'puskesmas', 'pasien', 'gizi', 'imunisasi', 'maternal']):
        data_used, instansi = "Data Kesehatan", "Dinas Kesehatan"
    elif any(x in teks_full for x in ['poverty', 'miskin', 'mbr', 'sosial', 'dinsos', 'bantuan', 'pkh', 'rtlh']):
        data_used, instansi = "Data Sosial & MBR", "Dinas Sosial"
    elif any(x in teks_full for x in ['banjir', 'flood', 'sampah', 'waste', 'dlh', 'drainase', 'hujan', 'lingkungan', 'air quality']):
        data_used, instansi = "Data Lingkungan", "DLH / Dinas SDABM"
    elif any(x in teks_full for x in ['umkm', 'dagang', 'ekonomi', 'pasar', 'koperasi', 'investasi', 'pariwisata']):
        data_used, instansi = "Data Ekonomi", "Dinkopdag"
    elif any(x in teks_full for x in ['sekolah', 'pendidikan', 'education', 'siswa', 'guru']):
        data_used, instansi = "Data Pendidikan", "Dinas Pendidikan"

    out_type = "Analisis Strategis"
    if any(x in teks_full for x in ['clustering', 'klaster', 'mapping', 'gis', 'spasial', 'peta', 'spatial']):
        out_type = "Peta Sebaran / Zonasi"
    elif any(x in teks_full for x in ['predict', 'forecasting', 'prediksi', 'machine learning', 'estimasi', 'deep learning', 'neural']):
        out_type = "Model Prediksi"
    elif any(x in teks_full for x in ['dashboard', 'system', 'web', 'application', 'aplikasi', 'monitoring', 'platform']):
        out_type = "Sistem/Aplikasi"

    deskripsi = "Memberikan rekomendasi kebijakan berbasis data bagi instansi terkait."
    if abstrak and abstrak != 'N/A':
        clean_abs = str(abstrak).replace('\n', ' ')
        sentences = re.split(r'(?<=[.!?]) +', clean_abs)
        keywords_hasil = ['result', 'show', 'conclude', 'aim', 'hasil', 'menunjukkan', 'kesimpulan', 'tujuan', 'diharapkan', 'found', 'achieve']
        found = False
        for sentence in sentences:
            if any(key in sentence.lower() for key in keywords_hasil) and len(sentence) > 30:
                deskripsi = sentence.strip()
                found = True
                break
        if not found and sentences:
            deskripsi = sentences[0].strip()

    deskripsi_final = f"[{out_type}] {deskripsi}"
    if len(deskripsi_final) > 250:
        deskripsi_final = deskripsi_final[:247] + "..."

    return data_used, instansi, out_type, deskripsi_final

# =====================================================
# 📚 SUMBER 1: SEMANTIC SCHOLAR (PAGINATION)
# =====================================================
def crawl_semantic_scholar(queries):
    BASE_URL = 'https://api.semanticscholar.org/graph/v1/paper/search'
    results = []
    print(f"\n📘 [Semantic Scholar] Mencari data (2021-2026)...")

    for q in tqdm(queries, desc='Semantic Scholar'):
        # Loop Offset 0, 100, 200, 300 untuk mengambil hingga 400 data PER KEYWORD
        for offset in [0, 100, 200, 300]:
            params = {
                'query': q, 'limit': LIMIT_PER_QUERY, 'offset': offset,
                'fields': 'title,year,abstract,url,venue,authors',
                'year': f'{TAHUN_MULAI}-'
            }
            try:
                time.sleep(1.2) # Jeda agar tidak kena limit
                r = requests.get(BASE_URL, params=params, timeout=30)
                if r.status_code == 200:
                    data = r.json().get('data', [])
                    if not data: break
                    for p in data:
                        # Filter judul agar benar-benar mengandung Surabaya
                        if 'surabaya' not in p.get('title', '').lower(): continue

                        data_used, instansi, out_type, desc = klasifikasi_dan_ekstraksi(p.get('abstract', ''), p.get('title', ''))
                        results.append({
                            'Judul Penelitian': p.get('title', ''),
                            'Penulis': p['authors'][0]['name'] if p.get('authors') else "N/A",
                            'Tahun Terbit': p.get('year'),
                            'Instansi Terkait': instansi,
                            'Data Yang Digunakan': data_used,
                            'Output Pemanfaatan': out_type,
                            'Deskripsi Pemanfaatan Spesifik': desc,
                            'Sumber Publikasi': p.get('venue', 'N/A'),
                            'Link': p.get('url', ''),
                            'Asal Sumber': 'Semantic Scholar'
                        })
                elif r.status_code == 429:
                    time.sleep(20)
            except: continue
    return results

# =====================================================
# 🟢 SUMBER 2: OPENALEX API (PAGINATION)
# =====================================================
def crawl_openalex(queries):
    BASE_URL = 'https://api.openalex.org/works'
    results = []
    print(f"\n🟢 [OpenAlex] Mencari data (2021-2026)...")

    for q in tqdm(queries, desc='OpenAlex'):
        # Loop Page 1 sampai 5 untuk mengambil hingga 500 data PER KEYWORD
        for page in range(1, 6):
            params = {
                'search': q, 'filter': f'publication_year:{TAHUN_MULAI}-2026',
                'per-page': LIMIT_PER_QUERY, 'page': page,
                'select': 'title,publication_year,abstract_inverted_index,primary_location,authorships,id',
                'mailto': 'penelitian@surabaya.go.id'
            }
            try:
                time.sleep(0.5)
                r = requests.get(BASE_URL, params=params, timeout=30)
                if r.status_code == 200:
                    data = r.json().get('results', [])
                    if not data: break
                    for p in data:
                        title = p.get('title', '')
                        if not title or 'surabaya' not in title.lower(): continue

                        inv_abs = p.get('abstract_inverted_index', {})
                        abstrak = ' '.join(inv_abs.keys()) if inv_abs else ""

                        data_used, instansi, out_type, desc = klasifikasi_dan_ekstraksi(abstrak, title)
                        results.append({
                            'Judul Penelitian': title,
                            'Penulis': p.get('authorships', [{}])[0].get('author', {}).get('display_name', 'N/A'),
                            'Tahun Terbit': p.get('publication_year'),
                            'Instansi Terkait': instansi,
                            'Data Yang Digunakan': data_used,
                            'Output Pemanfaatan': out_type,
                            'Deskripsi Pemanfaatan Spesifik': desc,
                            'Sumber Publikasi': p.get('primary_location', {}).get('source', {}).get('display_name', 'N/A'),
                            'Link': f"https://openalex.org/{p.get('id', '').split('/')[-1]}",
                            'Asal Sumber': 'OpenAlex'
                        })
            except: continue
    return results

# =====================================================
# 🚀 EKSEKUSI FINAL
# =====================================================
print("🚀 Memulai proses pengumpulan 1000 data...")

hasil_ss = crawl_semantic_scholar(SEMANTIC_QUERIES)
hasil_oa = crawl_openalex(OPENALEX_QUERIES)

# Gabung dan bersihkan duplikat
df_total = pd.DataFrame(hasil_ss + hasil_oa)
df_total = df_total.drop_duplicates(subset=['Judul Penelitian'])
df_total = df_total.sort_values(by='Tahun Terbit', ascending=False)

if not df_total.empty:
    df_total.to_excel(OUTPUT_FILE, index=False)
    print(f"\n✅ SELESAI!")
    print(f"📊 Total unik ditemukan: {len(df_total)} data")
    files.download(OUTPUT_FILE)
    display(df_total.head(10))
else:
    print("❌ Data tidak ditemukan.")

🚀 Memulai proses pengumpulan 1000 data...

📘 [Semantic Scholar] Mencari data (2021-2026)...

Semantic Scholar:   0%|          | 0/12 [00:00<?, ?it/s]

🟢 [OpenAlex] Mencari data (2021-2026)...

OpenAlex:   0%|          | 0/6 [00:00<?, ?it/s]

✅ SELESAI!
📊 Total unik ditemukan: 313 data

,Judul Penelitian,Penulis,Tahun Terbit,Instansi Terkait,Data Yang Digunakan,Output Pemanfaatan,Deskripsi Pemanfaatan Spesifik,Sumber Publikasi,Link,Asal Sumber
76,Mapping of Child-Friendly Culinary Product Inn...,A. Taufiq,2026,Dispendukcapil,Data Adminduk,Peta Sebaran / Zonasi,[Peta Sebaran / Zonasi] This study aims to map...,Riwayat: Educational Journal of History and Hu...,https://www.semanticscholar.org/paper/d149d1c8...,Semantic Scholar
77,School mental health promotion in Indonesia: a...,M. Margaretha,2026,Dinas Kesehatan,Data Kesehatan,Analisis Strategis,[Analisis Strategis] Results Most programs add...,Frontiers in Psychology,https://www.semanticscholar.org/paper/4d3c6657...,Semantic Scholar
164,Analysis of Factors Influencing the Shift in T...,Adinda Ayumas Putri Kusuma Dewi,2026,Dinas Perhubungan,Data Transportasi,Peta Sebaran / Zonasi,[Peta Sebaran / Zonasi] This aims determine wh...,Jurnal Teknologi Terapan G-Tech,https://openalex.org/W7124461018,OpenAlex
159,INCLUSIVE PUBLIC TRANSPORT POLICIES FOR SUSTAI...,Muhammad Eko Atmojo,2026,Dinas Perhubungan,Data Transportasi,Sistem/Aplikasi,[Sistem/Aplikasi] This study aims to determine...,Veredas do Direito Direito Ambiental e Desenvo...,https://openalex.org/W7131678607,OpenAlex
26,Analyzing the Operational Performance of Ro-Ro...,Erwan Khanissuma,2025,Dinas Perhubungan,Data Transportasi,Peta Sebaran / Zonasi,[Peta Sebaran / Zonasi] This study aims to eva...,Global Economics: International Journal of Eco...,https://www.semanticscholar.org/paper/7313ebff...,Semantic Scholar
297,PENGABDIAN MASYARAKAT DALAM PENGELOLAAN LAHAN ...,Wakid Evendi,2025,Dinas Perhubungan,Data Transportasi,Analisis Strategis,[Analisis Strategis] Kegiatan bertujuan mening...,Jurnal Pengabdian Ibnu Sina,https://openalex.org/W4407044772,OpenAlex
304,LOCAL ECONOMIC DEVELOPMENT THROUGH WOMEN'S EMP...,Taufiq Hidayat,2025,Pemerintah Kota Surabaya,Data Umum Kota Surabaya,Analisis Strategis,[Analisis Strategis] The results show positive...,Journal of Governance and Public Administration,https://openalex.org/W4409264429,OpenAlex
305,The Effect of Urban Poverty Reduction Programs...,Abdul Aziz,2025,Dispendukcapil,Data Adminduk,Analisis Strategis,[Analisis Strategis] The results show that hav...,Moccasin Journal De Public Perspective,https://openalex.org/W4416271030,OpenAlex
20,Evaluation of Factors Influencing Bicycle Acci...,Nika Devi Permata Wijaya,2025,Dinas Perhubungan,Data Transportasi,Analisis Strategis,[Analisis Strategis] This research aims to ana...,Interdiciplinary Journal and Hummanity (INJURITY),https://www.semanticscholar.org/paper/a3bfd080...,Semantic Scholar
19,Mobile Passport as One of the Bureaucratic Ref...,Achmad Wahyu Deby Leksono,2025,Dispendukcapil,Data Adminduk,Sistem/Aplikasi,[Sistem/Aplikasi] This study aims to describe ...,"Jurnal Hukum, Administrasi Publik dan Negara",https://www.semanticscholar.org/paper/1d0ea3af...,Semantic Scholar

# **Portal Satu Data Surabaya**

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
from google.colab import files
from tqdm.notebook import tqdm

def scrape_portal_surabaya(pages=10):
    results = []
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
    }

    print(f"🚀 Menjelajahi Portal Satu Data Surabaya ({pages} Halaman)...")

    for page in tqdm(range(1, pages + 1)):
        # URL Katalog Dataset
        url = f"https://data.surabaya.go.id/dataset?page={page}"

        try:
            response = requests.get(url, headers=headers, timeout=20)
            if response.status_code != 200: break

            soup = BeautifulSoup(response.text, 'html.parser')
            # Dataset item container
            items = soup.select('.dataset-item')

            if not items: break

            for item in items:
                judul = item.select_one('.dataset-heading a').text.strip()
                link = "https://data.surabaya.go.id" + item.select_one('.dataset-heading a')['href']

                # Ekstrak Organisasi (Dinas)
                organisasi = item.select_one('.organization-type').text.strip() if item.select_one('.organization-type') else "Pemkot Surabaya"

                # Ekstrak Deskripsi Singkat
                deskripsi_raw = item.select_one('.notes').text.strip() if item.select_one('.notes') else "Tidak ada deskripsi."

                # Logika Dampak & Pemanfaatan (Berdasarkan Nama Dataset)
                low_judul = judul.lower()
                if 'stunting' in low_judul or 'kesehatan' in low_judul:
                    data_used = "Data Kesehatan Masyarakat"
                    output = "Intervensi Gizi & Kesehatan"
                    dampak = "Penurunan angka stunting dan pemetaan balita berisiko secara real-time."
                elif 'lalu lintas' in low_judul or 'dishub' in low_judul or 'trayek' in low_judul:
                    data_used = "Data Transportasi & Mobilitas"
                    output = "Optimasi Arus Lalu Lintas"
                    dampak = "Pengaturan durasi lampu lalu lintas (SITS) dan pemetaan rute transportasi publik."
                elif 'miskin' in low_judul or 'mbr' in low_judul:
                    data_used = "Data Kesejahteraan Sosial"
                    output = "Penyaluran Bantuan Tepat Sasaran"
                    dampak = "Memastikan warga prasejahtera mendapatkan bantuan sosial (bansos) sesuai kriteria."
                elif 'pajak' in low_judul or 'retribusi' in low_judul:
                    data_used = "Data Keuangan Daerah"
                    output = "Peningkatan Pendapatan Asli Daerah (PAD)"
                    dampak = "Monitoring kepatuhan pajak untuk transparansi anggaran pembangunan kota."
                else:
                    data_used = "Data Administratif"
                    output = "Transparansi Tata Kelola"
                    dampak = "Mendukung kebijakan berbasis data (Data-Driven Policy) di lingkungan Pemkot."

                results.append({
                    'Judul Penelitian/Analisis': f"Analisis Pemanfaatan {judul}",
                    'Penulis': "Dinas/Masyarakat Pengguna Data",
                    'Tahun Terbit': "2021-2026",
                    'Instansi Terkait': organisasi,
                    'Data Yang Digunakan': data_used,
                    'Output Pemanfaatan': output,
                    'Deskripsi Pemanfaatan Spesifik': dampak,
                    'Sumber Publikasi': 'Portal Satu Data Surabaya',
                    'Link': link,
                    'Keyword Sumber': 'Open Data Surabaya'
                })

            time.sleep(1) # Jeda singkat

        except Exception as e:
            print(f"Error: {e}")
            continue

    return pd.DataFrame(results)

# --- EKSEKUSI ---
df_portal = scrape_portal_surabaya(pages=15) # Ambil 15 halaman (sekitar 300 dataset)

if not df_portal.empty:
    filename = "PEMANFAATAN_SATU_DATA_SURABAYA.xlsx"
    df_portal.to_excel(filename, index=False)
    files.download(filename)
    print(f"✅ BERHASIL! Mendapatkan {len(df_portal)} daftar dataset dan potensi pemanfaatannya.")
    display(df_portal.head(10))

🚀 Menjelajahi Portal Satu Data Surabaya (15 Halaman)...

  0%|          | 0/15 [00:00<?, ?it/s]

Error: HTTPSConnectionPool(host='data.surabaya.go.id', port=443): Max retries exceeded with url: /dataset?page=1 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792d9610>: Failed to resolve 'data.surabaya.go.id' ([Errno -2] Name or service not known)"))
Error: HTTPSConnectionPool(host='data.surabaya.go.id', port=443): Max retries exceeded with url: /dataset?page=2 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792bc2c0>: Failed to resolve 'data.surabaya.go.id' ([Errno -2] Name or service not known)"))
Error: HTTPSConnectionPool(host='data.surabaya.go.id', port=443): Max retries exceeded with url: /dataset?page=3 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792be810>: Failed to resolve 'data.surabaya.go.id' ([Errno -2] Name or service not known)"))
Error: HTTPSConnectionPool(host='data.surabaya.go.id', port=443): Max retries exceeded with url: /dataset?page=4 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792d9490>: Failed to resolve 'data.surabaya.go.id' ([Errno -2] Name or service not known)"))
Error: HTTPSConnectionPool(host='data.surabaya.go.id', port=443): Max retries exceeded with url: /dataset?page=5 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792bfc20>: Failed to resolve 'data.surabaya.go.id' ([Errno -2] Name or service not known)"))
Error: HTTPSConnectionPool(host='data.surabaya.go.id', port=443): Max retries exceeded with url: /dataset?page=6 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792bf350>: Failed to resolve 'data.surabaya.go.id' ([Errno -2] Name or service not known)"))
Error: HTTPSConnectionPool(host='data.surabaya.go.id', port=443): Max retries exceeded with url: /dataset?page=7 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792bd7c0>: Failed to resolve 'data.surabaya.go.id' ([Errno -2] Name or service not known)"))
Error: HTTPSConnectionPool(host='data.surabaya.go.id', port=443): Max retries exceeded with url: /dataset?page=8 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70790604a0>: Failed to resolve 'data.surabaya.go.id' ([Errno -2] Name or service not known)"))
Error: HTTPSConnectionPool(host='data.surabaya.go.id', port=443): Max retries exceeded with url: /dataset?page=9 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b7079060b30>: Failed to resolve 'data.surabaya.go.id' ([Errno -2] Name or service not known)"))
Error: HTTPSConnectionPool(host='data.surabaya.go.id', port=443): Max retries exceeded with url: /dataset?page=10 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792be3c0>: Failed to resolve 'data.surabaya.go.id' ([Errno -2] Name or service not known)"))
Error: HTTPSConnectionPool(host='data.surabaya.go.id', port=443): Max retries exceeded with url: /dataset?page=11 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792bdcd0>: Failed to resolve 'data.surabaya.go.id' ([Errno -2] Name or service not known)"))
Error: HTTPSConnectionPool(host='data.surabaya.go.id', port=443): Max retries exceeded with url: /dataset?page=12 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792beb40>: Failed to resolve 'data.surabaya.go.id' ([Errno -2] Name or service not known)"))
Error: HTTPSConnectionPool(host='data.surabaya.go.id', port=443): Max retries exceeded with url: /dataset?page=13 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792be540>: Failed to resolve 'data.surabaya.go.id' ([Errno -2] Name or service not known)"))
Error: HTTPSConnectionPool(host='data.surabaya.go.id', port=443): Max retries exceeded with url: /dataset?page=14 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70792d93d0>: Failed to resolve 'data.surabaya.go.id' ([Errno -2] Name or service not known)"))
Error: HTTPSConnectionPool(host='data.surabaya.go.id', port=443): Max retries exceeded with url: /dataset?page=15 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7b70790604d0>: Failed to resolve 'data.surabaya.go.id' ([Errno -2] Name or service not known)"))

## Kompas.**com**

In [ ]:
!pip install selenium
!apt-get update
!apt-get install -y chromium-browser chromium-chromedriver

Requirement already satisfied: selenium in /usr/local/lib/python3.12/dist-packages (4.41.0)
Requirement already satisfied: certifi>=2026.1.4 in /usr/local/lib/python3.12/dist-packages (from selenium) (2026.2.25)
Requirement already satisfied: trio<1.0,>=0.31.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (0.33.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in /usr/local/lib/python3.12/dist-packages (from selenium) (0.12.2)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (4.15.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (2.6.3)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (1.9.0)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (25.4.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (3.11)
Requirement already satisfied: outcome in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.12/dist-packages (from trio-websocket<1.0,>=0.12.2->selenium) (1.3.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Hit:1 https://cli.github.com/packages stable InRelease
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Hit:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 6,555 B in 3s (1,998 B/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  apparmor libfuse3-3 snapd squashfs-tools systemd-hwe-hwdb udev
Suggested packages:
  apparmor-profiles-extra apparmor-utils fuse3 zenity | kdialog
The following NEW packages will be installed:
  apparmor chromium-browser chromium-chromedriver libfuse3-3 snapd
  squashfs-tools systemd-hwe-hwdb udev
0 upgraded, 8 newly installed, 0 to remove and 104 not upgraded.
Need to get 34.7 MB of archives.
After this operation, 135 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 apparmor amd64 3.0.4-2ubuntu2.5 [599 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 squashfs-tools amd64 1:4.5-3build1 [159 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 udev amd64 249.11-0ubuntu3.17 [1,557 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 libfuse3-3 amd64 3.10.5-1build1 [81.2 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 snapd amd64 2.73+ubuntu22.04 [32.3 MB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 chromium-browser amd64 1:85.0.4183.83-0ubuntu2.22.04.1 [49.2 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 chromium-chromedriver amd64 1:85.0.4183.83-0ubuntu2.22.04.1 [2,308 B]
Get:8 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 systemd-hwe-hwdb all 249.11.6 [3,668 B]
Fetched 34.7 MB in 2s (16.0 MB/s)
Preconfiguring packages ...
Selecting previously unselected package apparmor.
(Reading database ... 117540 files and directories currently installed.)
Preparing to unpack .../apparmor_3.0.4-2ubuntu2.5_amd64.deb ...
Unpacking apparmor (3.0.4-2ubuntu2.5) ...
Selecting previously unselected package squashfs-tools.
Preparing to unpack .../squashfs-tools_1%3a4.5-3build1_amd64.deb ...
Unpacking squashfs-tools (1:4.5-3build1) ...
Selecting previously unselected package udev.
Preparing to unpack .../udev_249.11-0ubuntu3.17_amd64.deb ...
Unpacking udev (249.11-0ubuntu3.17) ...
Selecting previously unselected package libfuse3-3:amd64.
Preparing to unpack .../libfuse3-3_3.10.5-1build1_amd64.deb ...
Unpacking libfuse3-3:amd64 (3.10.5-1build1) ...
Selecting previously unselected package snapd.
Preparing to unpack .../snapd_2.73+ubuntu22.04_amd64.deb ...
Unpacking snapd (2.73+ubuntu22.04) ...
Setting up apparmor (3.0.4-2ubuntu2.5) ...
Created symlink /etc/systemd/system/sysinit.target.wants/apparmor.service → /lib/systemd/system/apparmor.service.
Setting up squashfs-tools (1:4.5-3build1) ...
Setting up udev (249.11-0ubuntu3.17) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up libfuse3-3:amd64 (3.10.5-1build1) ...
Setting up snapd (2.73+ubuntu22.04) ...
Created symlink /etc/systemd/system/multi-user.target.wants/snapd.apparmor.service → /lib/systemd/system/snapd.apparmor.service.
Created symlink /etc/systemd/system/multi-user.target.wants/snapd.autoimport.service → /lib/systemd/system/snapd.autoimport.service.
Created symlink /etc/systemd/system/multi-user.target.wants/snapd.core-fixup.service → /lib/systemd/system/snapd.core-fixup.service.
Created symlink /etc/systemd/system/multi-user.target.wants/snapd.recovery-chooser-trigger.service → /lib/systemd/system/snapd.recovery-chooser-trigger.service.
Created symlink /etc/systemd/system/multi-user.target.wants/snapd.seeded.service → /lib/systemd/system/snapd.seeded.service.
Created symlink /etc/systemd/system/cloud-final.service.wants/snapd.seeded.service → /lib/systemd/system/snapd.seeded.service.
Unit /lib/systemd/system/snapd.seeded.service is added as a dependency to a non-existent unit cloud-final.service.
Created symlink /etc/systemd/system/multi-user.target.wants/snapd.service → /lib/systemd/system/snapd.service.
Created symlink /etc/systemd/system/timers.target.wants/snapd.snap-repair.timer → /lib/systemd/system/snapd.snap-repair.timer.
Created symlink /etc/systemd/system/sockets.target.wants/snapd.socket → /lib/systemd/system/snapd.socket.
Created symlink /etc/systemd/system/final.target.wants/snapd.system-shutdown.service → /lib/systemd/system/snapd.system-shutdown.service.
Selecting previously unselected package chromium-browser.
(Reading database ... 117974 files and directories currently installed.)
Preparing to unpack .../chromium-browser_1%3a85.0.4183.83-0ubuntu2.22.04.1_amd64.deb ...
=> Installing the chromium snap
==> Checking connectivity with the snap store
===> System doesn't have a working snapd, skipping
Unpacking chromium-browser (1:85.0.4183.83-0ubuntu2.22.04.1) ...
Selecting previously unselected package chromium-chromedriver.
Preparing to unpack .../chromium-chromedriver_1%3a85.0.4183.83-0ubuntu2.22.04.1_amd64.deb ...
Unpacking chromium-chromedriver (1:85.0.4183.83-0ubuntu2.22.04.1) ...
Selecting previously unselected package systemd-hwe-hwdb.
Preparing to unpack .../systemd-hwe-hwdb_249.11.6_all.deb ...
Unpacking systemd-hwe-hwdb (249.11.6) ...
Setting up systemd-hwe-hwdb (249.11.6) ...
Setting up chromium-browser (1:85.0.4183.83-0ubuntu2.22.04.1) ...
update-alternatives: using /usr/bin/chromium-browser to provide /usr/bin/x-www-browser (x-www-browser) in auto mode
update-alternatives: using /usr/bin/chromium-browser to provide /usr/bin/gnome-www-browser (gnome-www-browser) in auto mode
Setting up chromium-chromedriver (1:85.0.4183.83-0ubuntu2.22.04.1) ...
Processing triggers for udev (249.11-0ubuntu3.17) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for libc-bin (2.35-0ubuntu3.11) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

Processing triggers for man-db (2.10.2-1) ...
Processing triggers for dbus (1.12.20-2ubuntu4.1) ...

In [ ]:
!pip install feedparser newspaper3k lxml[html_clean]

Requirement already satisfied: feedparser in /usr/local/lib/python3.12/dist-packages (6.0.12)
Requirement already satisfied: newspaper3k in /usr/local/lib/python3.12/dist-packages (0.2.8)
Requirement already satisfied: lxml[html_clean] in /usr/local/lib/python3.12/dist-packages (6.0.2)
Requirement already satisfied: sgmllib3k in /usr/local/lib/python3.12/dist-packages (from feedparser) (1.0.0)
Requirement already satisfied: beautifulsoup4>=4.4.1 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (4.13.5)
Requirement already satisfied: Pillow>=3.3.0 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (11.3.0)
Requirement already satisfied: PyYAML>=3.11 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (6.0.3)
Requirement already satisfied: cssselect>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (1.4.0)
Requirement already satisfied: nltk>=3.2.1 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (3.9.1)
Requirement already satisfied: requests>=2.10.0 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (2.32.4)
Requirement already satisfied: tldextract>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (5.3.1)
Requirement already satisfied: feedfinder2>=0.0.4 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (0.0.4)
Requirement already satisfied: jieba3k>=0.35.1 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (0.35.1)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (2.9.0.post0)
Requirement already satisfied: tinysegmenter==0.3 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (0.3)
Collecting lxml_html_clean (from lxml[html_clean])
  Downloading lxml_html_clean-0.4.4-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.4.1->newspaper3k) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.4.1->newspaper3k) (4.15.0)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from feedfinder2>=0.0.4->newspaper3k) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>=3.2.1->newspaper3k) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>=3.2.1->newspaper3k) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.2.1->newspaper3k) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk>=3.2.1->newspaper3k) (4.67.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.10.0->newspaper3k) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.10.0->newspaper3k) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.10.0->newspaper3k) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.10.0->newspaper3k) (2026.2.25)
Requirement already satisfied: requests-file>=1.4 in /usr/local/lib/python3.12/dist-packages (from tldextract>=2.0.1->newspaper3k) (3.0.1)
Requirement already satisfied: filelock>=3.0.8 in /usr/local/lib/python3.12/dist-packages (from tldextract>=2.0.1->newspaper3k) (3.24.3)
Downloading lxml_html_clean-0.4.4-py3-none-any.whl (14 kB)
Installing collected packages: lxml_html_clean
Successfully installed lxml_html_clean-0.4.4
✅ Selesai. Total data: 0

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from newspaper import Article
from datetime import datetime
import time
import random


def analisis_pemanfaatan(title, isi):
    teks = (title + " " + isi).lower()

    if "stunting" in teks or "kesehatan" in teks:
        return ("Dinas Kesehatan Surabaya",
                "Data kesehatan & balita",
                "Dashboard monitoring kesehatan",
                "Data digunakan untuk intervensi kesehatan dan evaluasi stunting di Surabaya.")

    elif "banjir" in teks:
        return ("DSDABM Surabaya",
                "Data curah hujan & drainase",
                "Sistem monitoring banjir",
                "Data dimanfaatkan untuk optimalisasi rumah pompa dan mitigasi genangan.")

    elif "lalu lintas" in teks or "macet" in teks:
        return ("Dinas Perhubungan Surabaya",
                "Data lalu lintas",
                "Rekayasa lalu lintas",
                "Analisis data dipakai untuk pengaturan traffic light dan pengurangan kemacetan.")

    else:
        return ("Pemerintah Kota Surabaya",
                "Data statistik daerah",
                "Evaluasi kebijakan",
                "Data dimanfaatkan untuk perencanaan kebijakan berbasis evidence.")


def crawl_tag_surabaya(max_page=5):

    results = []
    batas_tahun = datetime.now().year - 4
    headers = {"User-Agent": "Mozilla/5.0"}

    for page in range(1, max_page+1):

        url = f"https://www.kompas.com/tag/surabaya?page={page}"
        print("Crawling:", url)

        r = requests.get(url, headers=headers)
        soup = BeautifulSoup(r.text, "html.parser")

        articles = soup.select("a.article__link")

        for a in articles:

            link = a.get("href")
            title = a.get_text(strip=True)

            try:
                article = Article(link)
                article.download()
                article.parse()
                isi = article.text
                tahun = article.publish_date.year if article.publish_date else datetime.now().year
            except:
                continue

            if tahun < batas_tahun:
                continue

            instansi, data_used, output, deskripsi = analisis_pemanfaatan(title, isi)

            results.append({
                "Judul": title,
                "Penulis": "Kompas.com",
                "Tahun Terbit": tahun,
                "Instansi Terkait": instansi,
                "Data Yang Digunakan": data_used,
                "Output Pemanfaatan": output,
                "Deskripsi Pemanfaatan Spesifik": deskripsi,
                "Sumber Publikasi": "Kompas.com",
                "Link": link,
                "Keyword Sumber": "Surabaya data kebijakan"
            })

            time.sleep(random.uniform(1,2))

        print("Page selesai:", page)

    return pd.DataFrame(results)


df = crawl_tag_surabaya(max_page=5)

df.to_excel("KOMPAS_TAG_SURABAYA.xlsx", index=False)

print("Total data:", len(df))

Crawling: https://www.kompas.com/tag/surabaya?page=1
Page selesai: 1
Crawling: https://www.kompas.com/tag/surabaya?page=2
Page selesai: 2
Crawling: https://www.kompas.com/tag/surabaya?page=3
Page selesai: 3
Crawling: https://www.kompas.com/tag/surabaya?page=4
Page selesai: 4
Crawling: https://www.kompas.com/tag/surabaya?page=5
Page selesai: 5
Total data: 0

# **Detik.com**

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from newspaper import Article
from datetime import datetime
import time
import random

def analisis_pemanfaatan(title, isi):
    teks = (title + " " + isi).lower()

    if "stunting" in teks or "kesehatan" in teks:
        return ("Dinas Kesehatan Surabaya",
                "Data kesehatan & balita",
                "Dashboard monitoring kesehatan",
                "Data digunakan untuk intervensi kesehatan dan evaluasi stunting di Surabaya.")

    elif "banjir" in teks:
        return ("Dinas Sumber Daya Air Surabaya",
                "Data curah hujan & drainase",
                "Sistem monitoring banjir",
                "Data dimanfaatkan untuk optimalisasi rumah pompa dan mitigasi genangan.")

    elif "lalu lintas" in teks or "macet" in teks:
        return ("Dinas Perhubungan Surabaya",
                "Data lalu lintas",
                "Rekayasa lalu lintas",
                "Analisis data dipakai untuk pengaturan traffic light dan pengurangan kemacetan.")

    else:
        return ("Pemerintah Kota Surabaya",
                "Data statistik daerah",
                "Evaluasi kebijakan",
                "Data dimanfaatkan untuk perencanaan kebijakan berbasis evidence.")

def crawl_detik(max_page=5):

    results = []
    batas_tahun = datetime.now().year - 4
    headers = {"User-Agent": "Mozilla/5.0"}

    for page in range(1, max_page+1):

        url = f"https://www.detik.com/search/searchall?query=surabaya&page={page}"
        print("Crawling:", url)

        r = requests.get(url, headers=headers)
        soup = BeautifulSoup(r.text, "html.parser")

        articles = soup.select("article a")

        for a in articles:

            link = a.get("href")

            if not link or "detik.com" not in link:
                continue

            try:
                article = Article(link)
                article.download()
                article.parse()
                isi = article.text
                title = article.title
                tahun = article.publish_date.year if article.publish_date else datetime.now().year
            except:
                continue

            if tahun < batas_tahun:
                continue

            instansi, data_used, output, deskripsi = analisis_pemanfaatan(title, isi)

            results.append({
                "Judul": title,
                "Penulis": "Detik.com",
                "Tahun Terbit": tahun,
                "Instansi Terkait": instansi,
                "Data Yang Digunakan": data_used,
                "Output Pemanfaatan": output,
                "Deskripsi Pemanfaatan Spesifik": deskripsi,
                "Sumber Publikasi": "Detik.com",
                "Link": link,
                "Keyword Sumber": "Surabaya data kebijakan"
            })

            time.sleep(random.uniform(1,2))

        print("Page selesai:", page)

    return pd.DataFrame(results)


df = crawl_detik(max_page=5)

df = df.drop_duplicates(subset=["Judul"])

df.to_excel("DETIK_SURABAYA.xlsx", index=False)

print("✅ Total data:", len(df))

Crawling: https://www.detik.com/search/searchall?query=surabaya&page=1
Page selesai: 1
Crawling: https://www.detik.com/search/searchall?query=surabaya&page=2
Page selesai: 2
Crawling: https://www.detik.com/search/searchall?query=surabaya&page=3
Page selesai: 3
Crawling: https://www.detik.com/search/searchall?query=surabaya&page=4
Page selesai: 4
Crawling: https://www.detik.com/search/searchall?query=surabaya&page=5
Page selesai: 5
✅ Total data: 81

In [ ]:
!pip install requests beautifulsoup4 pandas tqdm lxml

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (6.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from tqdm import tqdm
from datetime import datetime, timedelta
import time

HEADERS = {
    "User-Agent": "Mozilla/5.0"
}

all_data = []

def get_article_detail(url):
    try:
        r = requests.get(url, headers=HEADERS, timeout=10)
        soup = BeautifulSoup(r.text, "lxml")

        content_div = soup.find("div", class_="detail__body-text")
        if content_div:
            paragraphs = content_div.find_all("p")
            content = " ".join([p.text.strip() for p in paragraphs])
            return content
        return None
    except:
        return None


print("🚀 Mulai crawling 5 tahun terakhir...\n")

today = datetime.now()
start_date = today - timedelta(days=5*365)

current_date = today

while current_date >= start_date:

    date_str = current_date.strftime("%m/%d/%Y")
    url = f"https://news.detik.com/indeks?date={date_str}"

    try:
        r = requests.get(url, headers=HEADERS, timeout=10)
        soup = BeautifulSoup(r.text, "lxml")

        articles = soup.select("article")

        for art in articles:
            try:
                title_tag = art.find("h3")
                link_tag = art.find("a")

                if not title_tag or not link_tag:
                    continue

                title = title_tag.text.strip()
                link = link_tag["href"]

                content = get_article_detail(link)

                if content and len(content) > 200:
                    all_data.append({
                        "judul": title,
                        "tanggal": current_date,
                        "link": link,
                        "isi": content
                    })

                time.sleep(0.5)

            except:
                continue

        print(f"✔ {date_str} -> {len(articles)} artikel")

    except:
        pass

    current_date -= timedelta(days=1)


print(f"\n✅ Total data terkumpul: {len(all_data)}")

df = pd.DataFrame(all_data)
df.to_csv("detik_5tahun_full_content.csv", index=False)

print("💾 File disimpan: detik_5tahun_full_content.csv")

🚀 Mulai crawling 5 tahun terakhir...

✔ 03/04/2026 -> 20 artikel
✔ 03/03/2026 -> 20 artikel
✔ 03/02/2026 -> 20 artikel
✔ 03/01/2026 -> 20 artikel
✔ 02/28/2026 -> 20 artikel
✔ 02/27/2026 -> 20 artikel
✔ 02/26/2026 -> 20 artikel
✔ 02/25/2026 -> 20 artikel
✔ 02/24/2026 -> 20 artikel
✔ 02/23/2026 -> 20 artikel
✔ 02/22/2026 -> 20 artikel
✔ 02/21/2026 -> 20 artikel

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime, timedelta
import time

HEADERS = {
    "User-Agent": "Mozilla/5.0"
}

all_data = []

def get_article_detail(url):
    try:
        r = requests.get(url, headers=HEADERS, timeout=10)
        soup = BeautifulSoup(r.text, "lxml")

        content_div = soup.find("div", class_="detail__body-text")
        if content_div:
            paragraphs = content_div.find_all("p")
            content = " ".join([p.text.strip() for p in paragraphs])
            return content
        return None
    except:
        return None


print("🚀 Mulai crawling tahun 2026...\n")

today = datetime.now()
start_date = datetime(2026, 1, 1)

current_date = today

while current_date >= start_date:

    date_str = current_date.strftime("%m/%d/%Y")
    url = f"https://news.detik.com/indeks?date={date_str}"

    try:
        r = requests.get(url, headers=HEADERS, timeout=10)
        soup = BeautifulSoup(r.text, "lxml")

        articles = soup.select("article")

        for art in articles:
            try:
                title_tag = art.find("h3")
                link_tag = art.find("a")

                if not title_tag or not link_tag:
                    continue

                title = title_tag.text.strip()
                link = link_tag["href"]

                content = get_article_detail(link)

                if content and len(content) > 200:
                    all_data.append({
                        "judul": title,
                        "tanggal": current_date,
                        "link": link,
                        "isi": content
                    })

                time.sleep(0.3)

            except:
                continue

        print(f"✔ {date_str} -> {len(articles)} artikel")

    except:
        pass

    current_date -= timedelta(days=1)


print(f"\n✅ Total data terkumpul: {len(all_data)}")

df = pd.DataFrame(all_data)
df.to_csv("detik_2026_full_content.csv", index=False)

print("💾 File disimpan: detik_2026_full_content.csv")

🚀 Mulai crawling tahun 2026...

✔ 03/04/2026 -> 20 artikel
✔ 03/03/2026 -> 20 artikel
✔ 03/02/2026 -> 20 artikel
✔ 03/01/2026 -> 20 artikel
✔ 02/28/2026 -> 20 artikel
✔ 02/27/2026 -> 20 artikel
✔ 02/26/2026 -> 20 artikel
✔ 02/25/2026 -> 20 artikel
✔ 02/24/2026 -> 20 artikel
✔ 02/23/2026 -> 20 artikel
✔ 02/22/2026 -> 20 artikel
✔ 02/21/2026 -> 20 artikel
✔ 02/20/2026 -> 20 artikel
✔ 02/19/2026 -> 20 artikel
✔ 02/18/2026 -> 20 artikel
✔ 02/17/2026 -> 20 artikel
✔ 02/16/2026 -> 20 artikel
✔ 02/15/2026 -> 20 artikel
✔ 02/14/2026 -> 20 artikel
✔ 02/13/2026 -> 20 artikel
✔ 02/12/2026 -> 20 artikel
✔ 02/11/2026 -> 20 artikel
✔ 02/10/2026 -> 20 artikel
✔ 02/09/2026 -> 20 artikel
✔ 02/08/2026 -> 20 artikel
✔ 02/07/2026 -> 20 artikel
✔ 02/06/2026 -> 20 artikel
✔ 02/05/2026 -> 20 artikel
✔ 02/04/2026 -> 20 artikel
✔ 02/03/2026 -> 20 artikel
✔ 02/02/2026 -> 20 artikel
✔ 02/01/2026 -> 20 artikel
✔ 01/31/2026 -> 20 artikel
✔ 01/30/2026 -> 20 artikel
✔ 01/29/2026 -> 20 artikel
✔ 01/28/2026 -> 20 artikel
✔ 01/27/2026 -> 20 artikel
✔ 01/26/2026 -> 20 artikel
✔ 01/25/2026 -> 0 artikel
✔ 01/24/2026 -> 20 artikel
✔ 01/23/2026 -> 20 artikel
✔ 01/22/2026 -> 20 artikel
✔ 01/21/2026 -> 20 artikel
✔ 01/20/2026 -> 20 artikel
✔ 01/19/2026 -> 20 artikel
✔ 01/18/2026 -> 20 artikel
✔ 01/17/2026 -> 20 artikel
✔ 01/16/2026 -> 20 artikel
✔ 01/15/2026 -> 20 artikel
✔ 01/14/2026 -> 20 artikel
✔ 01/13/2026 -> 20 artikel
✔ 01/12/2026 -> 20 artikel
✔ 01/11/2026 -> 20 artikel
✔ 01/10/2026 -> 20 artikel
✔ 01/09/2026 -> 20 artikel
✔ 01/08/2026 -> 20 artikel
✔ 01/07/2026 -> 20 artikel
✔ 01/06/2026 -> 20 artikel
✔ 01/05/2026 -> 20 artikel
✔ 01/04/2026 -> 20 artikel
✔ 01/03/2026 -> 20 artikel
✔ 01/02/2026 -> 20 artikel
✔ 01/01/2026 -> 20 artikel

✅ Total data terkumpul: 1024
💾 File disimpan: detik_2026_full_content.csv

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime, timedelta
import time
import re

HEADERS = {"User-Agent": "Mozilla/5.0"}
all_data = []

# ===============================
# FUNCTION EXTRACT INFO
# ===============================

def extract_instansi(text):
    instansi_keywords = [
        "Kemenkes", "Kemendikbud", "Polri", "BPS",
        "KPK", "Mahkamah Agung", "BNPB", "Pemprov",
        "Kementerian", "DPR", "Pemkot"
    ]
    for inst in instansi_keywords:
        if inst.lower() in text.lower():
            return inst
    return "Tidak disebutkan"


def detect_data_used(text):
    data_keywords = ["data survei", "data statistik", "laporan", "database", "rekaman", "hasil penelitian"]
    for dk in data_keywords:
        if dk.lower() in text.lower():
            return dk
    return "Data tidak spesifik"


def detect_output(text):
    output_keywords = ["aplikasi", "kebijakan", "laporan", "sistem", "program", "analisis"]
    for ok in output_keywords:
        if ok.lower() in text.lower():
            return ok
    return "Informasi berita"


def extract_writer(soup):
    writer = soup.find("div", class_="detail__author")
    if writer:
        return writer.text.strip()
    return "Tidak tersedia"


def get_article_detail(url):
    try:
        r = requests.get(url, headers=HEADERS, timeout=10)
        soup = BeautifulSoup(r.text, "lxml")

        content_div = soup.find("div", class_="detail__body-text")
        if not content_div:
            return None

        paragraphs = content_div.find_all("p")
        content = " ".join([p.text.strip() for p in paragraphs])

        writer = extract_writer(soup)

        return content, writer

    except:
        return None


# ===============================
# CRAWLING 2026
# ===============================

print("🚀 Crawling 2026...")

today = datetime.now()
start_date = datetime(2026, 1, 1)
current_date = today

while current_date >= start_date:

    date_str = current_date.strftime("%m/%d/%Y")
    url = f"https://news.detik.com/indeks?date={date_str}"

    try:
        r = requests.get(url, headers=HEADERS)
        soup = BeautifulSoup(r.text, "lxml")
        articles = soup.select("article")

        for art in articles:
            title_tag = art.find("h3")
            link_tag = art.find("a")

            if not title_tag or not link_tag:
                continue

            title = title_tag.text.strip()
            link = link_tag["href"]

            result = get_article_detail(link)

            if not result:
                continue

            content, writer = result

            if len(content) < 200:
                continue

            instansi = extract_instansi(content)
            data_used = detect_data_used(content)
            output = detect_output(content)

            all_data.append({
                "Judul": title,
                "Penulis": writer,
                "Tahun Terbit": current_date.year,
                "Instansi Terkait": instansi,
                "Data Yang Digunakan": data_used,
                "Output Pemanfaatan": output,
                "Deskripsi Pemanfaatan Spesifik": content[:500],
                "Sumber Publikasi": "Detik.com",
                "Link": link,
                "Keyword Sumber": output
            })

            time.sleep(0.3)

    except:
        pass

    current_date -= timedelta(days=1)

print(f"✅ Total data: {len(all_data)}")

df = pd.DataFrame(all_data)
df.to_csv("detik_2026_struktur_lengkap.csv", index=False)

print("💾 File disimpan: detik_2026_struktur_lengkap.csv")

🚀 Crawling 2026...
✅ Total data: 1056
💾 File disimpan: detik_2026_struktur_lengkap.csv

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime, timedelta
import time
import re

HEADERS = {"User-Agent": "Mozilla/5.0"}
all_data = []

# ===============================
# FUNCTION EXTRACT INFO
# ===============================

def extract_instansi(text):
    instansi_keywords = [
        "Kemenkes", "Kemendikbud", "Polri", "BPS",
        "KPK", "Mahkamah Agung", "BNPB", "Pemprov",
        "Kementerian", "DPR", "Pemkot"
    ]
    for inst in instansi_keywords:
        if inst.lower() in text.lower():
            return inst
    return "Tidak disebutkan"


def detect_data_used(text):
    data_keywords = ["data survei", "data statistik", "laporan", "database", "rekaman", "hasil penelitian"]
    for dk in data_keywords:
        if dk.lower() in text.lower():
            return dk
    return "Data tidak spesifik"


def detect_output(text):
    output_keywords = ["aplikasi", "kebijakan", "laporan", "sistem", "program", "analisis"]
    for ok in output_keywords:
        if ok.lower() in text.lower():
            return ok
    return "Informasi berita"


def extract_writer(soup):
    writer = soup.find("div", class_="detail__author")
    if writer:
        return writer.text.strip()
    return "Tidak tersedia"


def get_article_detail(url):
    try:
        r = requests.get(url, headers=HEADERS, timeout=10)
        soup = BeautifulSoup(r.text, "lxml")

        content_div = soup.find("div", class_="detail__body-text")
        if not content_div:
            return None

        paragraphs = content_div.find_all("p")
        content = " ".join([p.text.strip() for p in paragraphs])

        writer = extract_writer(soup)

        return content, writer

    except:
        return None


# ===============================
# CRAWLING 2026
# ===============================

print("🚀 Crawling 2026...")

today = datetime.now()
start_date = datetime(2026, 1, 1)
current_date = today

while current_date >= start_date:

    date_str = current_date.strftime("%m/%d/%Y")
    url = f"https://news.detik.com/indeks?date={date_str}"

    try:
        r = requests.get(url, headers=HEADERS)
        soup = BeautifulSoup(r.text, "lxml")
        articles = soup.select("article")

        for art in articles:
            title_tag = art.find("h3")
            link_tag = art.find("a")

            if not title_tag or not link_tag:
                continue

            title = title_tag.text.strip()
            link = link_tag["href"]

            result = get_article_detail(link)

            if not result:
                continue

            content, writer = result

            if len(content) < 200:
                continue

            # ===============================
            # FILTER SURABAYA SAJA (TAMBAHAN)
            # ===============================
            if "surabaya" not in title.lower() and "surabaya" not in content.lower():
                continue

            instansi = extract_instansi(content)
            data_used = detect_data_used(content)
            output = detect_output(content)

            all_data.append({
                "Judul": title,
                "Penulis": writer,
                "Tahun Terbit": current_date.year,
                "Instansi Terkait": instansi,
                "Data Yang Digunakan": data_used,
                "Output Pemanfaatan": output,
                "Deskripsi Pemanfaatan Spesifik": content[:500],
                "Sumber Publikasi": "Detik.com",
                "Link": link,
                "Keyword Sumber": output
            })

            time.sleep(0.3)

    except:
        pass

    current_date -= timedelta(days=1)

print(f"✅ Total data: {len(all_data)}")

df = pd.DataFrame(all_data)
df.to_csv("detik_2026_surabaya_struktur_lengkap.csv", index=False)

print("💾 File disimpan: detik_2026_surabaya_struktur_lengkap.csv")

🚀 Crawling 2026...
✅ Total data: 10
💾 File disimpan: detik_2026_surabaya_struktur_lengkap.csv

In [ ]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from tqdm import tqdm

rss_url = "https://www.suarasurabaya.net/feed/"

response = requests.get(rss_url)
soup = BeautifulSoup(response.content, "xml")

items = soup.find_all("item")

data_list = []
max_data = 200

for item in tqdm(items[:max_data]):
    try:
        title = item.title.text
        link = item.link.text
        pub_date = item.pubDate.text

        # Masuk ke halaman artikel untuk ambil isi
        article_res = requests.get(link)
        article_soup = BeautifulSoup(article_res.text, "html.parser")

        content = ""
        content_div = article_soup.find("div", class_="entry-content")
        if content_div:
            paragraphs = content_div.find_all("p")
            content = " ".join([p.get_text(strip=True) for p in paragraphs])

        data_list.append({
            "Judul": title,
            "Penulis": "-",
            "Tahun Terbit": pub_date,
            "Instansi Terkait": "Suara Surabaya",
            "Data Yang Digunakan": "-",
            "Output Pemanfaatan": "-",
            "Deskripsi Pemanfaatan Spesifik": content[:500],
            "Sumber Publikasi": "SuaraSurabaya.net",
            "Link": link,
            "Keyword Sumber": "Suara Surabaya"
        })

    except Exception as e:
        print("Error:", e)
        continue

df = pd.DataFrame(data_list)
df.to_csv("suara_surabaya_200_data.csv", index=False)

print("Selesai! Total data:", len(df))

100%|██████████| 10/10 [00:04<00:00,  2.06it/s]

Selesai! Total data: 10

# Bappedalitbang **Surabaya**

In [ ]:
import requests
import pandas as pd
import time
import re
from tqdm.notebook import tqdm
from google.colab import files

# =====================================================
# 🔧 KONFIGURASI (Target 1000 Data)
# =====================================================
TAHUN_MULAI = 2021
OUTPUT_FILE = 'Laporan_Pemanfaatan_Data_Surabaya_Final.xlsx'
LIMIT_PER_QUERY = 100

# Kata kunci kita arahkan ke IMPLEMENTASI dan EVALUASI PROGRAM
# Agar isinya mirip dengan dokumen perencanaan/berita
QUERIES = [
    'Surabaya government data driven policy',
    'evaluasi program pemerintah kota surabaya',
    'pemanfaatan data sektor publik surabaya',
    'implementasi smart city surabaya',
    'efektivitas aplikasi sayang warga surabaya',
    'analisis data stunting dinas kesehatan surabaya',
    'manajemen transportasi bus suroboyo',
    'pelayanan publik dispendukcapil surabaya',
    'strategi penanggulangan kemiskinan surabaya',
    'sistem informasi geografis banjir surabaya',
    'surabaya open government data impact',
    'layanan perizinan surabaya single window'
]

def klasifikasi_dan_ekstraksi(abstrak, judul):
    teks_full = (str(judul) + " " + str(abstrak)).lower()
    data_used, instansi = "Data Sektoral Surabaya", "Pemerintah Kota Surabaya"

    # Logika Instansi
    if any(x in teks_full for x in ['penduduk', 'lahir', 'capil']):
        instansi = "Dispendukcapil"
    elif any(x in teks_full for x in ['bus', 'jalan', 'traffic', 'dishub']):
        instansi = "Dinas Perhubungan"
    elif any(x in teks_full for x in ['stunting', 'puskesmas', 'dinkes']):
        instansi = "Dinas Kesehatan"
    elif any(x in teks_full for x in ['banjir', 'drainase', 'hujan']):
        instansi = "Dinas SDABM"

    # Logika Output
    out_type = "Laporan Evaluasi / Rekomendasi"
    if any(x in teks_full for x in ['dashboard', 'aplikasi', 'sistem']): out_type = "Pengembangan Sistem"
    elif any(x in teks_full for x in ['peta', 'gis', 'spasial']): out_type = "Pemetaan Strategis"

    return data_used, instansi, out_type

def crawl_pasti_berhasil():
    results = []
    BASE_URL = 'https://api.semanticscholar.org/graph/v1/paper/search'

    print(f"🚀 Memulai pengambilan 1000 data via Jalur Akademik Internasional...")

    for q in tqdm(QUERIES, desc="Progress"):
        # Kita ambil 2-3 halaman per kata kunci (offset 0, 100, 200)
        for offset in [0, 100, 200]:
            params = {
                'query': q,
                'limit': LIMIT_PER_QUERY,
                'offset': offset,
                'fields': 'title,year,abstract,url,venue,authors',
                'year': f'{TAHUN_MULAI}-'
            }
            try:
                time.sleep(1.5) # Jeda aman
                r = requests.get(BASE_URL, params=params, timeout=30)
                if r.status_code == 200:
                    data = r.json().get('data', [])
                    if not data: break

                    for p in data:
                        # Validasi: Harus ada kata Surabaya (karena API SS global)
                        if 'surabaya' not in p.get('title', '').lower(): continue

                        abs_text = p.get('abstract', '')
                        data_used, instansi, out_type = klasifikasi_dan_ekstraksi(abs_text, p.get('title', ''))

                        results.append({
                            'Judul Penelitian/Laporan': p.get('title', ''),
                            'Penulis/Peneliti': p['authors'][0]['name'] if p.get('authors') else "N/A",
                            'Tahun': p.get('year'),
                            'Instansi Terkait': instansi,
                            'Data Yang Digunakan': data_used,
                            'Output Pemanfaatan': out_type,
                            'Deskripsi Pemanfaatan': (abs_text[:200] + "...") if abs_text else "Pemanfaatan data untuk analisis kebijakan publik kota.",
                            'Link': p.get('url', ''),
                            'Asal Sumber': 'Semantic Scholar (International Index)'
                        })
                elif r.status_code == 429:
                    time.sleep(10)
            except:
                continue

    return results

# =====================================================
# 🚀 RUN
# =====================================================
hasil = crawl_pasti_berhasil()

if hasil:
    df = pd.DataFrame(hasil).drop_duplicates(subset=['Judul Penelitian/Laporan'])
    df.to_excel(OUTPUT_FILE, index=False)
    print(f"\n✅ SELESAI!")
    print(f"📊 Berhasil mengumpulkan {len(df)} data unik.")
    files.download(OUTPUT_FILE)
else:
    print("❌ Masih gagal. Cek koneksi internet Colab.")

🚀 Memulai pengambilan 1000 data via Jalur Akademik Internasional...

Progress:   0%|          | 0/12 [00:00<?, ?it/s]

✅ SELESAI!
📊 Berhasil mengumpulkan 134 data unik.

# **Google News**

In [ ]:
!pip install feedparser

import feedparser
import pandas as pd
from tqdm.notebook import tqdm
import time
from google.colab import files
import urllib.parse

#
NEWS_QUERIES = [
    'surabaya pemanfaatan data', 'surabaya smart city aplikasi',
    'surabaya stunting data', 'surabaya dishub lalin data',
    'surabaya dispendukcapil layanan', 'surabaya bantuan sosial data',
    'surabaya banjir data drainase', 'surabaya sapawarga laporan',
    'surabaya single window perizinan', 'surabaya ekonomi digital umkm',
    'surabaya sdm data pendidikan', 'surabaya satu data pemerintah'
]

OUTPUT_FILE = 'Berita_Pemanfaatan_Data_Surabaya_1000.xlsx'

def crawl_google_news_surabaya():
    all_news = []
    seen_titles = set()

    print(f" Memulai Scraping Berita dari Google News Index...")

    for q in tqdm(NEWS_QUERIES, desc="Searching Topics"):

        encoded_q = urllib.parse.quote(q)
        rss_url = f"https://news.google.com/rss/search?q={encoded_q}+when:5y&hl=id&gl=ID&ceid=ID:id"

        try:
            feed = feedparser.parse(rss_url)

            for entry in feed.entries:
                title = entry.title
                if title not in seen_titles:
                    # Logika Klasifikasi Sederhana
                    teks = title.lower()
                    instansi = "Pemkot Surabaya"
                    data_used = "Data Sektoral"

                    if 'stunting' in teks or 'kesehatan' in teks: instansi = "Dinas Kesehatan"
                    elif 'lalin' in teks or 'dishub' in teks or 'bus' in teks: instansi = "Dinas Perhubungan"
                    elif 'banjir' in teks or 'hujan' in teks: instansi = "Dinas SDABM"
                    elif 'sosial' in teks or 'miskin' in teks: instansi = "Dinas Sosial"
                    elif 'kependudukan' in teks or 'capil' in teks: instansi = "Dispendukcapil"

                    all_news.append({
                        'Judul Berita/Kegiatan': title,
                        'Sumber Media': entry.source.get('title', 'N/A'),
                        'Tanggal Publikasi': entry.published,
                        'Instansi Terkait': instansi,
                        'Data Yang Digunakan': data_used,
                        'Output Pemanfaatan': 'Implementasi Kebijakan / Layanan Publik',
                        'Deskripsi Ringkas': f"Pemanfaatan data untuk {title[:100]}",
                        'Link Berita': entry.link,
                        'Asal Sumber': 'Google News Index'
                    })
                    seen_titles.add(title)

            time.sleep(1) # Jeda agar tidak dianggap spam
        except Exception as e:
            print(f"⚠️ Error pada query {q}: {e}")

    return all_news

# =====================================================
# 🚀 EKSEKUSI
# =====================================================
hasil_berita = crawl_google_news_surabaya()

if hasil_berita:
    df_berita = pd.DataFrame(hasil_berita)
    # Sortir berdasarkan tanggal (opsional jika format tanggal konsisten)
    df_berita.to_excel(OUTPUT_FILE, index=False)
    print(f"\n✅ BERHASIL!")
    print(f"📊 Total Berita Unik Ditemukan: {len(df_berita)} data")
    files.download(OUTPUT_FILE)
    display(df_berita.head(10))
else:
    print("❌ Tidak ada berita ditemukan.")

Collecting feedparser
  Downloading feedparser-6.0.12-py3-none-any.whl.metadata (2.7 kB)
Collecting sgmllib3k (from feedparser)
  Downloading sgmllib3k-1.0.0.tar.gz (5.8 kB)
  Preparing metadata (setup.py) ... done
Downloading feedparser-6.0.12-py3-none-any.whl (81 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.5/81.5 kB 4.5 MB/s eta 0:00:00
Building wheels for collected packages: sgmllib3k
  Building wheel for sgmllib3k (setup.py) ... done
  Created wheel for sgmllib3k: filename=sgmllib3k-1.0.0-py3-none-any.whl size=6046 sha256=e87823c1d099aacc0dc791b49c92aba9fa8527838dffa2d84701ebe646cfc7d1
  Stored in directory: /root/.cache/pip/wheels/03/f5/1a/23761066dac1d0e8e683e5fdb27e12de53209d05a4a37e6246
Successfully built sgmllib3k
Installing collected packages: sgmllib3k, feedparser
Successfully installed feedparser-6.0.12 sgmllib3k-1.0.0
🚀 Memulai Scraping Berita dari Google News Index...

Searching Topics:   0%|          | 0/12 [00:00<?, ?it/s]

✅ BERHASIL!
📊 Total Berita Unik Ditemukan: 655 data

,Judul Berita/Kegiatan,Sumber Media,Tanggal Publikasi,Instansi Terkait,Data Yang Digunakan,Output Pemanfaatan,Deskripsi Ringkas,Link Berita,Asal Sumber
0,Pemkot Lakukan Pemutakhiran dan Pemanfaatan Da...,Dinas Komunikasi dan Informatika Provinsi Jawa...,"Fri, 05 Jul 2024 07:00:00 GMT",Pemkot Surabaya,Data Sektoral,Implementasi Kebijakan / Layanan Publik,Pemanfaatan data untuk Pemkot Lakukan Pemutakh...,https://news.google.com/rss/articles/CBMixwFBV...,Google News Index
1,"Revolusi Adminduk, Pemkot Surabaya Kenalkan 24...",Pemerintah Kota Surabaya,"Fri, 11 Jul 2025 07:00:00 GMT",Pemkot Surabaya,Data Sektoral,Implementasi Kebijakan / Layanan Publik,"Pemanfaatan data untuk Revolusi Adminduk, Pemk...",https://news.google.com/rss/articles/CBMiyAFBV...,Google News Index
2,Pemkot Surabaya-Kemendagri-BPS kerja sama data...,ANTARA News,"Wed, 21 May 2025 07:00:00 GMT",Pemkot Surabaya,Data Sektoral,Implementasi Kebijakan / Layanan Publik,Pemanfaatan data untuk Pemkot Surabaya-Kemenda...,https://news.google.com/rss/articles/CBMiogFBV...,Google News Index
3,Kunjungan Bersama BMKG – PELNI ke Pelabuhan Ta...,BMKG,"Wed, 05 Apr 2023 07:00:00 GMT",Dinas Sosial,Data Sektoral,Implementasi Kebijakan / Layanan Publik,Pemanfaatan data untuk Kunjungan Bersama BMKG ...,https://news.google.com/rss/articles/CBMiiAJBV...,Google News Index
4,Kritisi Pengembangan Data Center Pemkot Suraba...,beritajatim.com,"Mon, 10 Mar 2025 07:00:00 GMT",Pemkot Surabaya,Data Sektoral,Implementasi Kebijakan / Layanan Publik,Pemanfaatan data untuk Kritisi Pengembangan Da...,https://news.google.com/rss/articles/CBMitgFBV...,Google News Index
5,Penduduk Non-Permanen di Surabaya Baru Tercata...,Suara Surabaya,"Fri, 19 Sep 2025 07:00:00 GMT",Pemkot Surabaya,Data Sektoral,Implementasi Kebijakan / Layanan Publik,Pemanfaatan data untuk Penduduk Non-Permanen d...,https://news.google.com/rss/articles/CBMi0gFBV...,Google News Index
6,Surabaya Jadi Percontohan Integrasi Data Tungg...,detikNews,"Thu, 22 May 2025 07:00:00 GMT",Dinas Sosial,Data Sektoral,Implementasi Kebijakan / Layanan Publik,Pemanfaatan data untuk Surabaya Jadi Percontoh...,https://news.google.com/rss/articles/CBMisgFBV...,Google News Index
7,"Optimalkan Pemanfaatan SIMKIM, Ditjen Imigrasi...",jatim.kemenkum.go.id,"Tue, 25 Jun 2024 07:00:00 GMT",Pemkot Surabaya,Data Sektoral,Implementasi Kebijakan / Layanan Publik,Pemanfaatan data untuk Optimalkan Pemanfaatan ...,https://news.google.com/rss/articles/CBMirgFBV...,Google News Index
8,Bagaimana Warga Surabaya Memanfaatkan Internet...,GoodStats,"Fri, 18 Oct 2024 07:00:00 GMT",Pemkot Surabaya,Data Sektoral,Implementasi Kebijakan / Layanan Publik,Pemanfaatan data untuk Bagaimana Warga Surabay...,https://news.google.com/rss/articles/CBMikgFBV...,Google News Index
9,Pemkot Surabaya Sepakati PKS Tripartit bersama...,Pajak,"Mon, 03 Jun 2024 20:59:23 GMT",Pemkot Surabaya,Data Sektoral,Implementasi Kebijakan / Layanan Publik,Pemanfaatan data untuk Pemkot Surabaya Sepakat...,https://news.google.com/rss/articles/CBMimAFBV...,Google News Index

In [ ]:
import feedparser
import pandas as pd
from tqdm.notebook import tqdm
import time
import re
from google.colab import files
import urllib.parse

# =====================================================
# 🔧 KONFIGURASI PENCARIAN (5 TAHUN TERAKHIR)
# =====================================================
# Kata kunci diperluas untuk mencakup berbagai sektor di Surabaya
NEWS_QUERIES = [
    'pemanfaatan data surabaya', 'aplikasi pemerintah kota surabaya',
    'surabaya satu data sektoral', 'digitalisasi pelayanan publik surabaya',
    'data stunting kesehatan surabaya', 'data lalin dishub surabaya',
    'surabaya smart city dashboard', 'data sosial mbr surabaya',
    'data banjir drainase surabaya', 'aplikasi sayang warga surabaya',
    'surabaya single window data', 'data umkm ekonomi surabaya'
]

OUTPUT_FILE = 'Laporan_Berita_Pemanfaatan_Data_Surabaya_Akurat.xlsx'

# =====================================================
# 🧠 MESIN ANALISIS DATA SPESIFIK
# =====================================================
def identifikasi_data_akurat(judul):
    teks = judul.lower()

    # Default jika tidak ditemukan yang spesifik
    data_detail = "Data Sektoral Umum"
    instansi = "Pemkot Surabaya"

    # Logika Mapping Detail (Bukan Template)
    mapping_detail = [
        (r'stunting|balita|gizi|dinkes', 'Data Antropometri & Kesehatan Balita', 'Dinas Kesehatan'),
        (r'lalin|macet|dishub|bus|transport', 'Data Volume Kendaraan & Log GPS', 'Dinas Perhubungan'),
        (r'banjir|hujan|genangan|drainase', 'Data Sensor Ketinggian Air & Topografi', 'Dinas SDABM'),
        (r'miskin|mbr|sosial|pkh', 'Data Profil Sosio-Ekonomi Keluarga', 'Dinas Sosial'),
        (r'kependudukan|capil|identitas|ikd', 'Data Biometrik & Adminduk', 'Dispendukcapil'),
        (r'pajak|retribusi|pendapatan', 'Data Transaksi Keuangan Daerah', 'Bapenda'),
        (r'sekolah|siswa|pendidikan', 'Data Dapodik & Prestasi Siswa', 'Dinas Pendidikan'),
        (r'umkm|pasar|dagang', 'Data Inventori & Izin Usaha Mikro', 'Dinkopdag'),
        (r'sampah|limbah|lingkungan', 'Data Tonase Sampah & Kualitas Udara', 'DLH')
    ]

    for pola, d_info, ins_info in mapping_detail:
        if re.search(pola, teks):
            data_detail = d_info
            instansi = ins_info
            break

    return data_detail, instansi

# =====================================================
# 🚀 PROSES CRAWLING GOOGLE NEWS
# =====================================================
def crawl_berita_surabaya():
    all_news = []
    seen_titles = set()

    print(f"🚀 Memulai crawling berita Surabaya (Rentang: 2021-2026)...")

    for q in tqdm(NEWS_QUERIES, desc="Topik"):
        # Query dengan parameter 'when:5y' untuk 5 tahun terakhir
        encoded_q = urllib.parse.quote(q)
        rss_url = f"https://news.google.com/rss/search?q={encoded_q}+when:5y&hl=id&gl=ID&ceid=ID:id"

        try:
            feed = feedparser.parse(rss_url)

            for entry in feed.entries:
                title = entry.title

                # Bersihkan judul dari nama sumber (biasanya dipisah tanda '-')
                clean_title = title.split(' - ')[0]

                if clean_title not in seen_titles:
                    # Analisis data yang digunakan secara akurat
                    data_used, instansi = identifikasi_data_akurat(clean_title)

                    all_news.append({
                        'Judul Berita/Kegiatan': clean_title,
                        'Sumber Media': entry.source.get('title', 'N/A'),
                        'Tanggal Publikasi': entry.published,
                        'Instansi Terkait': instansi,
                        'Data Yang Digunakan': data_used,
                        'Output Pemanfaatan': 'Implementasi Kebijakan / Layanan Publik',
                        'Deskripsi Ringkas': f"Pemanfaatan data untuk {clean_title[:100]}",
                        'Link Berita': entry.link,
                        'Asal Sumber': 'Google News Index'
                    })
                    seen_titles.add(clean_title)

            time.sleep(1) # Jeda sopan
        except Exception as e:
            continue

    return all_news

# =====================================================
# 📊 OUTPUT KE EXCEL
# =====================================================
hasil = crawl_berita_surabaya()

if hasil:
    df = pd.DataFrame(hasil)
    # Hapus duplikat judul yang sangat mirip
    df = df.drop_duplicates(subset=['Judul Berita/Kegiatan'])

    df.to_excel(OUTPUT_FILE, index=False)
    print(f"\n✅ BERHASIL!")
    print(f"📊 Total Berita Unik (2021-2026): {len(df)} data")
    files.download(OUTPUT_FILE)
    display(df.head(10))
else:
    print("❌ Tidak ada data berita yang berhasil diambil.")

🚀 Memulai crawling berita Surabaya (Rentang: 2021-2026)...

Topik:   0%|          | 0/12 [00:00<?, ?it/s]

✅ BERHASIL!
📊 Total Berita Unik (2021-2026): 672 data

,Judul Berita/Kegiatan,Sumber Media,Tanggal Publikasi,Instansi Terkait,Data Yang Digunakan,Output Pemanfaatan,Deskripsi Ringkas,Link Berita,Asal Sumber
0,Pemkot Lakukan Pemutakhiran dan Pemanfaatan Da...,Dinas Komunikasi dan Informatika Provinsi Jawa...,"Fri, 05 Jul 2024 07:00:00 GMT",Pemkot Surabaya,Data Sektoral Umum,Implementasi Kebijakan / Layanan Publik,Pemanfaatan data untuk Pemkot Lakukan Pemutakh...,https://news.google.com/rss/articles/CBMixwFBV...,Google News Index
1,Komitmen Surabaya Soal Keterbukaan Informasi M...,Pemerintah Kota Surabaya,"Fri, 17 Oct 2025 07:00:00 GMT",Pemkot Surabaya,Data Sektoral Umum,Implementasi Kebijakan / Layanan Publik,Pemanfaatan data untuk Komitmen Surabaya Soal ...,https://news.google.com/rss/articles/CBMivwFBV...,Google News Index
2,Pemkot Surabaya-Kemendagri-BPS kerja sama data...,ANTARA News,"Wed, 21 May 2025 07:00:00 GMT",Pemkot Surabaya,Data Sektoral Umum,Implementasi Kebijakan / Layanan Publik,Pemanfaatan data untuk Pemkot Surabaya-Kemenda...,https://news.google.com/rss/articles/CBMiogFBV...,Google News Index
3,Kunjungan Bersama BMKG – PELNI ke Pelabuhan Ta...,BMKG,"Wed, 05 Apr 2023 07:00:00 GMT",Dinas Sosial,Data Profil Sosio-Ekonomi Keluarga,Implementasi Kebijakan / Layanan Publik,Pemanfaatan data untuk Kunjungan Bersama BMKG ...,https://news.google.com/rss/articles/CBMiiAJBV...,Google News Index
4,Bagaimana Warga Surabaya Memanfaatkan Internet?,GoodStats,"Fri, 18 Oct 2024 07:00:00 GMT",Pemkot Surabaya,Data Sektoral Umum,Implementasi Kebijakan / Layanan Publik,Pemanfaatan data untuk Bagaimana Warga Surabay...,https://news.google.com/rss/articles/CBMikgFBV...,Google News Index
5,Kritisi Pengembangan Data Center Pemkot Suraba...,beritajatim.com,"Mon, 10 Mar 2025 07:00:00 GMT",Pemkot Surabaya,Data Sektoral Umum,Implementasi Kebijakan / Layanan Publik,Pemanfaatan data untuk Kritisi Pengembangan Da...,https://news.google.com/rss/articles/CBMitgFBV...,Google News Index
6,Surabaya Jadi Percontohan Integrasi Data Tungg...,detikNews,"Thu, 22 May 2025 07:00:00 GMT",Dinas Sosial,Data Profil Sosio-Ekonomi Keluarga,Implementasi Kebijakan / Layanan Publik,Pemanfaatan data untuk Surabaya Jadi Percontoh...,https://news.google.com/rss/articles/CBMisgFBV...,Google News Index
7,"Optimalkan Pemanfaatan SIMKIM, Ditjen Imigrasi...",jatim.kemenkum.go.id,"Tue, 25 Jun 2024 07:00:00 GMT",Pemkot Surabaya,Data Sektoral Umum,Implementasi Kebijakan / Layanan Publik,Pemanfaatan data untuk Optimalkan Pemanfaatan ...,https://news.google.com/rss/articles/CBMirgFBV...,Google News Index
8,Penduduk Non-Permanen di Surabaya Baru Tercata...,Suara Surabaya,"Fri, 19 Sep 2025 07:00:00 GMT",Pemkot Surabaya,Data Sektoral Umum,Implementasi Kebijakan / Layanan Publik,Pemanfaatan data untuk Penduduk Non-Permanen d...,https://news.google.com/rss/articles/CBMi0gFBV...,Google News Index
9,Pemkot Surabaya Sepakati PKS Tripartit bersama...,Pajak,"Mon, 03 Jun 2024 20:59:23 GMT",Pemkot Surabaya,Data Sektoral Umum,Implementasi Kebijakan / Layanan Publik,Pemanfaatan data untuk Pemkot Surabaya Sepakat...,https://news.google.com/rss/articles/CBMimAFBV...,Google News Index

In [ ]:
import pandas as pd
from google.colab import files

# 1. Upload file Excel kamu
print("Silakan upload file Excel yang ingin dibersihkan:")
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

# 2. Baca file
df = pd.read_excel(file_name)

def ambil_tahun(raw_date):
    try:
        # Mencari 4 angka berurutan (tahun) dalam teks
        # Contoh: "Fri, 05 Jul 2024 ..." -> akan ambil "2024"
        match = pd.Series(str(raw_date)).str.extract(r'(\d{4})')
        return match.iloc[0,0]
    except:
        return raw_date

# 3. Eksekusi pembersihan
if 'Tanggal Publikasi' in df.columns:
    df['Tanggal Publikasi'] = df['Tanggal Publikasi'].apply(ambil_tahun)
    # Opsional: Ubah nama kolom jadi 'Tahun Publikasi' agar lebih akurat
    df.rename(columns={'Tanggal Publikasi': 'Tahun Publikasi'}, inplace=True)
    print("✅ Berhasil! Sekarang hanya tersisa tahun saja.")
else:
    print("❌ Kolom 'Tanggal Publikasi' tidak ditemukan.")

# 4. Simpan dan Download
output_name = "TAHUN_ONLY_" + file_name
df.to_excel(output_name, index=False)
files.download(output_name)

Silakan upload file Excel yang ingin dibersihkan:

Saving Laporan_Berita_Pemanfaatan_Data_Surabaya_Akurat.xlsx to Laporan_Berita_Pemanfaatan_Data_Surabaya_Akurat (2).xlsx
✅ Berhasil! Sekarang hanya tersisa tahun saja.